### ISSUE TITLE
Registrant API: add admin and technical contact info to domain info response

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1000]
Domain details response has currently only the name of the registrant and is missing the references to admin and tech contacts.

Registrant name is not enough to pinpoint the exact contact object as name of the contact is not unique.

Therefore it is necessary to return UUIDs or codes of registrant, admin and technical contact objects.

**Comment by maciej-szlosarczyk** [comment]
Fixed in #997 

Registrant is returned as both name and id:

```json
// ...
  "registrant":{
    "name":"John Smith",
    "id":"acadf23e-47c4-4606-8f67-76e071a1cca2"
  },
// ...
```

Similarly are contacts, they are two separate arrays now:

```json
/// ...
  "admin_contacts":[
    {
      "name":"John Smith",
      "id":"62015e7d-42c8-4d68-8164-e9b71680fd95"
    },
    {
      "name":"William Smith",
      "id":"a041c5b6-7772-4fac-83cd-fbce3b2c8867"
    }
  ],
  "tech_contacts":[
    {
      "name":"John Smith",
      "id":"62015e7d-42c8-4d68-8164-e9b71680fd95"
    },
    {
      "name":"William Smith",
      "id":"a041c5b6-7772-4fac-83cd-fbce3b2c8867"
    }
  ],
/// ...
```
