### ISSUE TITLE
VAT exemption should not be visible on invoices

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1006]
https://github.com/internetee/registry/issues/623

> if address country code is not EE and VAT no. value is filled, vat% value is optional. VAT is not applied nor displayed on the invoice.

"nor displayed on the invoice." part is not implemented for some reason.

@vohmar I guess the absence of VAT means VAT exemption?

**Comment by vohmar** [comment]
Closer analysis revealed that there is no case in our business where vat is not applied. It is always applied the question is only whether it is 0% or more (no vat and 0% vat are different things legally).

So the initial specification stating VAT is not applied nor displayed on the invoice is incorrect that vat should be always applied and in the case described the value is 0%.
