### ISSUE TITLE
Update Apache

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1015]
Check that ID-card authentication works (https://kuutorvaja.eenet.ee/wiki/Apache'i_veebiserver#ID_kaardiga_kasutaja_autentimine).

https://github.com/mod-epp/mod-epp/issues/2
https://github.com/internetee/rest-whois/pull/139#issuecomment-436913721

**Comment by maciej-szlosarczyk** [comment]
I spent a few days trying to update mod_epp to be compatible with Apache 2.4 without success. Key problems compared with 2.2:

Without SSL (not standard), it is extremely slow. Producing a static greeting takes more than 5 seconds, making it effectively unusable.

With SSL, it produces a 403 while trying to get static greeting, and consequently shows the following message. Exactly same configuration works perfectly on Apache 2.2

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><epp xmlns="urn:ietf:params:xml:ns:epp-1.0"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd">
<response><result code="2400"><msg>Internal%20error%20producing%20greeting.</msg>
</result><trID></trID></response></epp>
```

Funnily enough, if you go and ignore that, you can still execute commands, as the connection is kept. I tried debugging it to see the source of it, but it seems to be some interaction between `mod_epp` and `mod_ssl` that I don't understand well. I tried removing that check altogether, but that again renders it extremely slow comparing with Apache 2.2.

**Comment by brynhood** [comment]
> I spent a few days trying to update mod_epp to be compatible with Apache 2.4 without success. Key problems compared with 2.2:
> 
> Without SSL (not standard), it is extremely slow. Producing a static greeting takes more than 5 seconds, making it effectively unusable.
> 
> With SSL, it produces a 403 while trying to get static greeting, and consequently shows the following message. Exactly same configuration works perfectly on Apache 2.2
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="no"?><epp xmlns="urn:ietf:params:xml:ns:epp-1.0"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd">
> <response><result code="2400"><msg>Internal%20error%20producing%20greeting.</msg>
> </result><trID></trID></response></epp>
> ```
> 
> Funnily enough, if you go and ignore that, you can still execute commands, as the connection is kept. I tried debugging it to see the source of it, but it seems to be some interaction between `mod_epp` and `mod_ssl` that I don't understand well. I tried removing that check altogether, but that again renders it extremely slow comparing with Apache 2.2.

would you mind sharing the code adaptions that you tried for that?

**Comment by vohmar** [comment]
Hi @brynhood thank you for your interest. We have dropped mod-epp and developed an alternative found [here](https://github.com/internetee/epp_proxy). Unfortunately @maciej-szlosarczyk is not involved with this project any more and I cannot help you with the code tweaks he tested.

**Comment by maciej-szlosarczyk** [comment]
Hey @brynhood, I checked if I still have the code somewhere, but unfortunately I don't. The best I can offer is that I remember the code failed somewhere there:

https://github.com/mod-epp/mod-epp/blob/master/mod_epp.c#L1040-L1049

**Comment by brynhood** [comment]
hi @maciej-szlosarczyk and @vohmar thanks for your reply....we are looking at our options here @centralnic to see what direction does make the most sense for us to go.

**Comment by teadur** [comment]
As of we have moved to https://github.com/internetee/epp_proxy and don't have hard version dep with apache anymore, i will close this issue.
