### ISSUE TITLE
Unified rate limiting system

### ISSUE THREAD

**Issue by teadur** [internetee/registry#1017]
We need to come up with a solution to make unified query rate limiting system.
Current rate limiting system forces the application to one machine and is far from ideal for ipv6.

Every registrar has a set limit x of allowed queries.
Every request to EPP or REPP should go to one token bucket.
Rate limiting should be configurable per registrar if needed ( disable or amount ) 
Rate limiting system should emit metrics about query load globally and per registrar, 
failed and completed queries.

The rate, query and session limiting should be done on application level instead of FW level like its done now.

**Comment by teadur** [comment]
#983 defines that we should allow prefixes

**Comment by artur-beljajev** [comment]
#813

**Comment by teadur** [comment]
The problem is that EPP/REPP should have combined limit so it kind of makes sense to implement them together.

**Comment by artur-beljajev** [comment]
My point was that both tickets in question duplicate each other, at least partly. Correct me if I am wrong.

**Comment by teadur** [comment]
Yep a bit, but as of the new ticket already has more information i would close the older one if any.
The real question here is how we are going to solve the problem.

**Comment by yulgolem** [comment]
Implemented by https://github.com/yulgolem/shunter , gem needs to be transfered to internetee repo.
Gem lacks documentation & integration with registry.
On hold until 25-06-2021.

**Comment by vohmar** [comment]
covered by https://github.com/yulgolem/shunter
