### ISSUE TITLE
Assets is Not Found

### ISSUE THREAD

**Issue by aEvgenn** [internetee/registry#1022]
I did
```
bundle exec rake db:setup:all # for production, please follow deployment howto
bundle exec rake bootstrap
bundle exec rake assets:precompile
```
But on pages *.css and *.js is Not Found net::ERR_ABORTED 404
```
/assets/admin-manifest-a69...a5b.css net::ERR_ABORTED 404 (Not Found)
/assets/admin-manifest-c20...ba3.js net::ERR_ABORTED 404 (Not Found)
```

**Comment by aEvgenn** [comment]
I use docker (https://github.com/internetee/docker-images/blob/master/docker-compose.yml) and open the page by ip (not by name like example.com).

`config.serve_static_files = true` in `config/environments/production.rb` solve this problem.

Another solution is to add a name inside `/etc/hosts`.

There is a good comment: `# Disable Rails's static asset server (Apache or nginx will already do this)`. It would be great to add a few words about the ip access case.

**Comment by maciej-szlosarczyk** [comment]
That docker setup is for local development only, I have never tested it against running on a different address than localhost. It also uses self-signed ssl certificates that I'm pretty certain won't work from a different address.

 But yes, you can use Rails to serve static assets in such a setup and at least that part of the problem should disappear.
