### ISSUE TITLE
VAT should always apply

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1031]
> Closer analysis revealed that there is no case in our business where vat is not applied. It is always applied the question is only whether it is 0% or more (no vat and 0% vat are different things legally).
> 
> So the initial specification stating VAT is not applied nor displayed on the invoice is incorrect that vat should be always applied and in the case described the value is 0%.

https://github.com/internetee/registry/issues/1006#issuecomment-434629656

Needed for #329

**Comment by artur-beljajev** [comment]
```
registry=# select count(*) from registrars where vat_rate is null
registry-# ;
 count 
-------                                                                                                                                                            
    55                                                                                                                                                             
(1 row)                                                                                                                                                            
                                                                                                                                                                   
registry=# select count(*) from invoices where vat_rate is null;
 count 
-------
    41
(1 row)
```

**Comment by artur-beljajev** [comment]
@vohmar See https://github.com/internetee/registry/pull/1174 and https://github.com/internetee/registry/pull/1175.

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/pull/1175

**Comment by vohmar** [comment]
Adding credit fails. To reproduce:

* foreign registrar with vat nr filled (vat rate = null)
* add credit ends with validation error - Validation failed: VAT rate is not a number

![image](https://user-images.githubusercontent.com/7734747/57933932-28cf2580-78c7-11e9-8884-bbc30fac14f1.png)

**Comment by artur-beljajev** [comment]
It is not ready yey... You probably forgot to reassign it back to me since the last issue...
