### ISSUE TITLE
Warning: Fixnum is deprecated

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1050]
message in deploy log, has been there for a while now:

`/root/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/mina-0.3.7/lib/mina/ssh_helpers.rb:118: warning: constant ::Fixnum is deprecated`

**Comment by maciej-szlosarczyk** [comment]
Deprecation comes from Mina and Ruby 2.4, not from software we wrote.

We are using an extremely outdated version of Mina. 0.3.7 was released in 2015, current one is 1.x. Updating that should allow us to get rid of the issue, but we need to update our deploy scripts:

https://github.com/mina-deploy/mina/blob/master/docs/migrating.md

FYI @teadur, @ratM1n

**Comment by artur-beljajev** [comment]
@teadur I heard we're getting rid of `mina`?

**Comment by teadur** [comment]
@artur-beljajev yep will happen soon
