### ISSUE TITLE
Contact details are not available in admin portal

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1059]
Contact details are not available in admin portal if a contact was updated from registrant portal (which in turn communicates via API) 

Originally discovered in https://github.com/internetee/registry/issues/992#issuecomment-447769886

```

Showing /media/sf_registry/app/views/admin/contacts/partials/_general.haml where line #41 raised:
undefined method `admin_registrant_user_path' for #<#<Class:0x00007f44b2b4b358>:0x00007f44b39d8290>

```

**Comment by artur-beljajev** [comment]
Normally, a link in `Updated` section points to API user, who updated a contact, but in the given case, `RegistrantUser` is the person who makes update, so it is not clear where it should point then...

http://prntscr.com/lw1pai

**Comment by vohmar** [comment]
we could specify the personal id there (ident code) of the user that made the update. Or create anonymous record a'la registrant. Although I have no idea what to put in the view - we could put name and ident what we get from the eID, but id would be OK if in this case it would be ok if we do not add any view at all (remove the link from the updater reference)
