### ISSUE TITLE
Upgrade bundler to 2.x

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1078]
https://bundler.io/v2.0/guides/bundler_2_upgrade.html

> Version autoswitching means that Bundler will automatically run the correct 1.x or 2.x version based on your lockfile

Existing app cannot be updated via `bundle update --bundler`, since Rails 4 supports Ruby >= 1.9.3, whereas bundler 2.x does not support Ruby < 2.3.
https://github.com/rails/rails/blob/v4.2.11/rails.gemspec#L10
https://github.com/rails/rails/pull/34925

Rails 5 does not have such limitation.
https://github.com/rails/rails/blob/master/rails.gemspec#L36

---
Run on every deployment:

1. `gem update --system` 
Updates RubyGems
2. `gem install bundler` 
Updates bundler
---
Blocked by #377

**Comment by teadur** [comment]
Tests seem to run fine https://travis-ci.org/internetee/registry/builds/580155989

**Comment by artur-beljajev** [comment]
Not relevant anymore.

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/pull/1275#issuecomment-527408401

**Comment by teadur** [comment]
Fixed by #1280
