### ISSUE TITLE
Improve company register component

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1079]
- Extract to a gem (https://github.com/internetee/company_register)
- Use API v6 (https://www.rik.ee/sites/www.rik.ee/files/elfinder/article_files/xml_descriptionv6_eng.pdf)
- Database setting  `days_to_keep_business_registry_cache` now resides in `application.yml` under `company_register_cache_period_days` key.
- `arireg_username`, `arireg_password` settings renamed to `company_register_username` and `company_register_password` respectively.
- `arireg_wsdl` and `arireg_host` settings have been hardcoded in gem and removed from `application.yml`
- Settings `company_register_cache_period_days`, `company_register_test_mode` added (see sample file for description).

Functional changes:
- `/api/v1/registrant/contacts` now returns direct contacts only, if company register is unavailable.
- Domain list at `/registrant/domains/x/contacts/x` no longer returns current registrant user's domains.

Fixes #916, #1077.

**Comment by vohmar** [comment]
connecting to business registry fails on staging. Configuration should be OK, but there are even no connection attempts going out from regsitrant to business registry made according to logs. The portal returns: Company register is unavailable. Domains and contacts associated via organizations are not shown.

**Comment by artur-beljajev** [comment]
Configuration on staging is not updated.
