### ISSUE TITLE
Topping up credit account without an invoice

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1101]
Implement option to add funds to credit account without creating an invoice first. Creating invoice prior instant payment is unnecessary. Allowing topping up credit balance using payment cards, bank link, or for example electronic wallets should only ask for the sum from the registered registrar user and in the result of successful transaction create receipt that is saved in the portal for registrars and automatically sent to registrar's accounting email and registries accounting system.

Additionally one could also support bank transfers for adding funds to credit balance. This would require automatic interface with e-bank that would automatically notify of new received payment and if reference number, description and registrar name match create a receipt (in case there is no matching invoice) and again send it to registrar's accounting email and registries accounting system.

**Comment by artur-beljajev** [comment]
This probably makes invoice cancellation at in Registrar portal obsolete.

**Comment by vohmar** [comment]
we canot drop invoice creating functionality altogether as some companies have strict process for making payments - so registrar specialist creates an invoice and forwards it to someone that has authority to make the payment. But for receipts there is indeed no need for cancellations in registrar portal nor admin. Also we are developing automatic e-invoice payment functionality that creates invoice first and then it may turn out that payments fails and cancellation option might be necessary.

PS: One option to improve invoice payments is to add direct payment options into the email used to forward the invoice file - bank link and card payment links

**Comment by artur-beljajev** [comment]
> we cannot drop invoice creating functionality

I mentioned invoice cancellation feature. It has nothing to do with invoice generation.

**Comment by vohmar** [comment]
There are companies that cannot or will not use direct payment or electronic invoicing options and prefer to use bank transfer requiring invoice for accounting . And if invoice is created prior to payment it might be left unpaid as well so invoice cancellation is still necessary.

**Comment by artur-beljajev** [comment]
Well, yeah, if we keep manual payments then it makes sense to keep cancellation as well...

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/blob/ce9a1811155271ea6fb69b324c4575eeb0a9b773/app/models/registrar.rb#L91
