### ISSUE TITLE
WHOIS does not return statuses for domains in auction process

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1105]
1. It appears that after running domains:release rake task only some domains are written into whois_records table in registry db. No errors are returned anywhere.
2. auctions ending with no_bids status are not removed from whois_records table and remain there with AtAuction status
3. domain names that had successful bids and have status awaiting payment to not get update in whois_records and remain in whois with AtAuction status while they should have status "Pending regsitration"

**Comment by vohmar** [comment]
Trying to identify the difference between the domains that were added to whois_records it seems that domains that were in the whois table before running the rake task are now missing and domains that were not in whois table because they had deletecandidate status applied are successfully added to the table

**Comment by vohmar** [comment]
domain:release rake task fails

registry@staging:~$ /bin/bash -l -c 'export PATH="$HOME/.rbenv/bin:$PATH";eval "$(rbenv init -)"; cd /home/registry/registry/current && RAILS_ENV=staging bin/bundle exec rake domains:release'
rake aborted!
ActiveRecord::RecordNotFound: Couldn't find Whois::Record
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/core.rb:196:in `find_by!'
/home/registry/registry/releases/709/app/models/dns/domain_name.rb:87:in `update_whois_from_auction'
/home/registry/registry/releases/709/app/models/dns/domain_name.rb:39:in `sell_at_auction'
/home/registry/registry/releases/709/app/models/concerns/domain/releasable.rb:39:in `block in release'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:220:in `transaction'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:277:in `transaction'
/home/registry/registry/releases/709/app/models/concerns/domain/releasable.rb:38:in `release'
/home/registry/registry/releases/709/app/models/concerns/domain/releasable.rb:9:in `block in release_domains'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
/home/registry/registry/releases/709/app/models/concerns/domain/releasable.rb:8:in `release_domains'
/home/registry/registry/releases/709/lib/tasks/domains/release.rake:10:in `block (2 levels) in <top (required)>'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/airbrake-6.0.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/registry/registry/releases/709/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
bin/bundle:3:in `load'
bin/bundle:3:in `<main>'
Tasks: TOP => domains:release
(See full trace by running task with --trace)

**Comment by artur-beljajev** [comment]
`ActiveRecord::RecordNotFound` exception is expected, since at the time `domains:release` task is run a domain must have a WHOIS record.

https://github.com/internetee/registry/issues/1111 may help.
