### ISSUE TITLE
ForceDelete: domains are not set for release nor sent to the auction

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1119]
domain:release rake task does not handle domains with forceDelete status set.

ForceDelete sets separate delete date for the domain and does not touch delete_at value. So if both are set the one that arrives earlier takes an effect.

Delete process ends the same way for all forms of releasing the domain - expiration, epp domain:delete or adminstrative forceDelete. If auction is disabled deletecandidate status is set and delayed job is created to release the domain name at random time within next approximately 24 hours. If auction is enabled then all the released domains including the ones with forceDelete set must be auctioned off

https://github.com/internetee/registry/blob/e4305e78656ad6610f5c85d9263eef93360a133d/app/models/domain_cron.rb#L82

**Comment by artur-beljajev** [comment]
Check #253
