### ISSUE TITLE
ForceDelete: new autoemail templates

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1178]
As we plan to use forcedelete more actively as a measure to improve data quality in the registry we need new FD email templates for invalid contact data
* invalid email address
* invalid phone nr (low priority - as we do not have phone nr validations yet)

current templates:
https://st-adm.infra.tld.ee/rails/mailers/domain_delete_mailer/forced_legal_person
https://st-adm.infra.tld.ee/rails/mailers/domain_delete_mailer/forced_private_person

**Comment by vohmar** [comment]
requires text for the new templates

**Comment by yulgolem** [comment]
Text for the templates https://docs.google.com/document/d/1bIlo-2q5PX2QLOg2jCSLDu47GK0Y9gjBGqLhZvzjQto/edit
paragraph Kustutusmenetluse teade (vigased kontaktandmed)

**Comment by vohmar** [comment]
New remplates have been added and are enabled for use in bulk forceDelete (https://github.com/internetee/registry/issues/1177)
