### ISSUE TITLE
EPP: poll delete notifications are not sent

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1196]
New domain:release rake task does not send delete poll notifications to registrars. It is important to notify owning registrar about deleting a domain registration, but with new refactored rake task this does not happen any more.

**Comment by artur-beljajev** [comment]
It has nothing to do with `domains.release` task nor any refactoring. The problem is that a new kind of deletion procedure was introduced with auction, and registrar notification was just absent there.
