### ISSUE TITLE
Unify/refactor domain delete procedures (auction on/off, delete/force delete)

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1198]

**Comment by yulgolem** [comment]
So in order to incapsulate domain managing (at least deletion) procedures we are to use Interactor design pattern (https://mkdev.me/en/posts/a-couple-of-words-about-interactors-in-rails).

**Comment by yulgolem** [comment]
Everything is done, the task might be closed now.

**Comment by vohmar** [comment]
done, thank you!
