### ISSUE TITLE
Auction - make registration deadline available for registrars over WHOIS and REST-WHOIS

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1201]
Currently there is no way to query the auctioned domain's registration deadline to verify how critical is the registration application in case registrar has not automated the registration process.

I see two option shere:
~~* domain:check - add the registration deadline in the reason description~~
* whois - return current registration deadline for all auctioned doimains with waiting for payent or waiting for registration statuses.

**Comment by artur-beljajev** [comment]
`reason` can only be returned when domain is unavailable, but a domain with in `pending_registration?` registration state is considered available.

**Comment by vohmar** [comment]
correct - that leaves domain:check option out and we have only whois to use in this case

**Comment by vohmar** [comment]
to make the solution consistent with regular whois output for registered domains it might be a good idea to use term delete and return registration due +1 to mark the date domain is back in auction if not paid or registered

**Comment by yulgolem** [comment]
so the main question is to:
1) Modify registry WhoisRecord to contain the auctioned domain's registration deadline
2) Make sure that this record contains actual deadline from the auction
3) Make sure that this record is available via whois/restwhois outputs

the deadline might be:
1) invoice due date if invoice is not paid yet
2) registration due (+1?) if invoice is paid

**Comment by yulgolem** [comment]
The plan is:
1) Add a field to Auction model in registry.
2) Fill this field with data during usual auction/registry integration in Api::V1::AuctionsController#update
3) update whois data via #1561 update_whois_from_auction
4) show this data in whois/restwhois
