### ISSUE TITLE
Make address_state and address_zip optional

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1206]
Related to https://github.com/internetee/registry/pull/1195

state and zip should be optional address parameters

postal address is required on invoices by law, but some address details like state are not strictly required in most countries especially smaller ones. Also zip is technical requirement for actual letter/parcel delivery and as we do not send anything to these addresses this info can also be viewed as optional.

**Comment by artur-beljajev** [comment]
I wonder why they are needed at all.

**Comment by vohmar** [comment]
state and zip are still mandatory in the admin registrar add/edit form ie /admin/registrars/new

**Comment by artur-beljajev** [comment]
Fixed.
