### ISSUE TITLE
Automatically check for proceeds on bank account

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1232]
Implement connection to LHV Connect service and enable automatic balance and incoming transfer checks to mark invoices paid by bank transfer (incl e-invoice standing order) as paid without human interaction.

connection details for LHV test Connect env are in Redmine

Tech spec: https://partners.lhv.ee/en/connect/

If possible rely on Debit Credit Notification service (alternatively there are automatic account statement and account report options).

**Comment by vohmar** [comment]
test results @ staging - failed
1. created payment in LHV test: rake dev:create_bank_transactions (success)
2. created an invoice for a registrar with invoice nr 1, total sum 0.1 and regsitrar's ref nr 13
3. run rake invoices:process_payments (Transactions processed: 0)

**Comment by vohmar** [comment]
problem solved - registry iban was incorrect for lhv test to work

**Comment by artur-beljajev** [comment]
And it was documented in internal Redmine.
