### ISSUE TITLE
Auto-invoicing fails after canceled invoice

### ISSUE THREAD

**Issue by teadur** [internetee/registry#1247]
If user enables auto-invoicing and cancels the invoice produced by auto-invoicing no new auto-invoices are generated until user "reconfigures" auto-invoicing - submit with zero changes in registrar portal is enough.
#329

**Comment by vohmar** [comment]
that is known behavior. System raises flag for the registrar once an automatic invoice is generated to stop double generation. The flag is removed on first successful payment so if a user cancels auto invoice they are still expected to make a payment so presumably the user creates manual invoice makes the payment and thus unlocks the account for new auto invoice. Logic here is that by raising auto invoice flag user is expecte to raise the balance above the limit before another auto-invoice can be issued.

**Comment by teadur** [comment]
Maybe it would make sense to describe the behviour somewhere for the end user ?
