### ISSUE TITLE
Upgrade paper_trail to Rails 5.x/6.X compatible version

### ISSUE THREAD

**Issue by teadur** [internetee/registry#1288]
We need to upgrade paper_trails to more modern version so we can upgrade Rails and Ruby.
This upgrade surely introduces many breaking changes to our code and will involve big effort  in verifying end result, but according to #536  we don't have good alternative solution.

Some of the effort is already documented in #426 but surely there is more.

4.2.0 Current version
- [ ] 5.2.3 (2016-11-29)
- [ ] 6.0.0 (2016-12-03) Rails 5.1
- [ ] 8.1.2 (2017-12-22) 
- [ ] 9.0.0 (2018-03-26) Rails 5.2
- [ ] 10.0.0 (2018-09-01) 
- [ ] 10.2.0 (2019-01-31) Ruby 2.6 / Rails 6.0 beta
- [ ] 10.3.0 (2019-04-09) latest

Currently this issue is blocking #377

**Comment by artur-beljajev** [comment]
Our current version (4.2.0) already supports all Rails versions prior to 6 (https://github.com/paper-trail-gem/paper_trail/blob/v4.2.0/paper_trail.gemspec#L22). So it actually doesn't block #377.

**Comment by teadur** [comment]
@artur-beljajev https://github.com/paper-trail-gem/paper_trail/pull/689 was fixed in papertrail 5.x aswell there are some other rails 5.x related fixes in 5.x in paeptrail 5.x but if you are certain they wont affect us keep this ticket closed.

**Comment by artur-beljajev** [comment]
I reviewed the PR in question. There is indeed Rails 5.0 compatibility change, but it only concerns reifying `has_one` association, and only a domain has one single `has_one  :whois_record` which is not visible in UI, as far as I know. 

So at least based on above mentioned gemspec, I guess it's safe to assume that currently used version (4.2.x) still supports Rails to some decent extent. In the worst case some info will be unavailable in UI, but nothing harmful should happen in terms of versioning and data.

Thanks for pointing out!

**Comment by teadur** [comment]
@artur-beljajev 
rather then just closing the issue could you point to a commit/issue what solves it currently it's impossible to trail how/what fixed the issue and that seems like bad practice

**Comment by artur-beljajev** [comment]
Solves what? :)
