### ISSUE TITLE
glue record's requirement is not based on full domain name

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1291]
Glue record - nameserver record in which second level domain name matches the domain name it serves

Apparently the matching is done with partial domain names. For example

domain name one.ee
and ns host ns.bone.ee

as the last three chars match the domain name registry classifies the host record as glue and refuses to attach it in case no ip address is specified for the ns record.

Second problem here is error handling - its not handled properly and following message is returned:
`handle_errors was executed when there were actually no errors`

**Comment by artur-beljajev** [comment]
Introduced in #661.

**Comment by artur-beljajev** [comment]
> Second problem here is error handling - its not handled properly and following message is returned:
handle_errors was executed when there were actually no errors
https://github.com/internetee/registry/issues/539
