### ISSUE TITLE
EPP hello command does not require authentication

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1323]
> An EPP client MAY request a <greeting> from an EPP server at any time between a successful <login> command and a <logout> command by sending a <hello> to a server

https://tools.ietf.org/html/rfc5730#section-2.3

Failing test: https://github.com/internetee/registry/blob/99e24c70d8efa34296da761b572b442a2a1c37a8/test/integration/epp/hello.rb#L17

**Comment by vohmar** [comment]
as a result server does not respond with greeting to successful connection as well authentication error is returned instead. Server must respond with proper greeting to successful connection and authenticated hello elements (https://tools.ietf.org/html/rfc5730#section-2.4)

**Comment by vohmar** [comment]
there also seems to be a bug with the hello element itself. Request:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd">
  <hello/>
</epp>`

gets this response:
`<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="lib/schemas/epp-ee-1.0.xsd">
  <response>
    <result code="2000">
      <msg lang="en">Unknown command.</msg>
    </result>
    <trID>
      <svTRID>ccReg-1237002386</svTRID>
    </trID>
  </response>
</epp>`

that is before and after authentication. Instead this request works:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd">
  <command>
    <hello/>
  </command>
</epp>`

hello is not a command

**Comment by teadur** [comment]
I think this whole issue is a bit misleading, if you consider EPP server state machine: https://tools.ietf.org/html/rfc5730#section-2 i would say that client can ask for a greeting before auth and after auth.

**Comment by artur-beljajev** [comment]
@vohmar https://github.com/internetee/registry/issues/1323#issuecomment-533521069 I am not sure I understand what is wrong. Anyway, please review the description and Georg's comment.

**Comment by vohmar** [comment]
@artur-beljajev as per [rfc5730 2.3](https://tools.ietf.org/html/rfc5730#section-2.3) greeting can be requested by the client by sending hello to epp server only between succcessful login and logout commands. but then again as @teadur correctly pointed out looking at [protocol description](https://tools.ietf.org/html/rfc5730#section-2) it is revealed that a user could also ask for greeting via hello before login, but it looks to me that the latter is true in case epp server works in connection-less mode that is not true in our case, but I may be wrong here and thus I'd say this problem can be closed as it seems everything is fine except the expected hello format that is addressed in epp_proxy  [#25](https://github.com/internetee/epp_proxy/issues/25)

**Comment by artur-beljajev** [comment]
> problem can be closed

Closed = revert authentication for EPP hello?
