### ISSUE TITLE
EPP contact:renew incorrect response

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#1362]
Currently `Unimplemented command` is returned. The specification states:

>  Renewal semantics do not apply to contact objects, so there is no
   mapping defined for the EPP <renew> command.

https://tools.ietf.org/html/rfc5733#section-3.2.3

Consider returning `Unknown command` instead.

**Comment by vohmar** [comment]
2000 unknown command is the correct response here

**Comment by artur-beljajev** [comment]
I think it makes no sense (or rather impossible) to handle such command on `registry` app level, since there is just no such command/request defined.

**Comment by vohmar** [comment]
I do agree that handling this scenario specifically is unnecessary, but at the same time I do not agree that unhandled internal error is better here - 2000 unknown command seems better aproach for any correctly structured request with unknown command - Exceptions are in my mind meant for unexpected result not unsupported input.

so could we implement error handling for unknown commands?

**Comment by vohmar** [comment]
contact:renew returns 2001 xml schema error
