### ISSUE TITLE
Records in registrant_verifications are not archived

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1425]
Blocks release of https://github.com/internetee/registry/issues/377

Records in registrant_verifications are never archived. As a result there are records in the table that point to domain registrations that do not exist any more violating constraints that new release candidate is trying to enforce.

As there is no archival mechanism for the table there in no log_* table.

There are two way to resolve this issue - use papertrail like similarly to other archived tables. Or implement new papertrail free method developed specifically for domain registry.

Latter option is preferred as we have planned to drop papertrail, but in this instance to move forward with updates kept back by this issue the papertrail approach is probably much faster.

**Comment by ratM1n** [comment]
`
       PG::ForeignKeyViolation: ERROR:  insert or update on table "registrant_verifications" violates foreign key constraint "fk_rails_f41617a0e9"
       DETAIL:  Key (domain_id)=(19) is not present in table "domains".
       : ALTER TABLE "registrant_verifications" ADD CONSTRAINT "fk_rails_f41617a0e9"
       FOREIGN KEY ("domain_id")
       REFERENCES "domains" ("id")
`

**Comment by artur-beljajev** [comment]
Thanks for providing additional info, @ratM1n!

**Comment by vohmar** [comment]
the fix provided just deleted orphaned registrant_verification records from the db, That is against our no delete policy. These records should have been archived/copied into archive table ie log_registrant_verification. No such table is created, cannot see where are the records archived.

**Comment by artur-beljajev** [comment]
They are logged into `versions` table, since I saw no reason creating a new table.

**Comment by vohmar** [comment]
in versions table i see only an event of deleting some record with type registrant_verification. This does not comply with no delete policy.

**Comment by vohmar** [comment]
* solution does not follow implemented audit log/archival logic
  * versions table is used instead of using current naming convention of log_registrant_versions
  * archived data is stored in object column with type text instead of json/jsonb

please move audit log data to log_registrant_verification table to follow the established logic and fix the object column type

**Comment by artur-beljajev** [comment]
`versions` this is the default table used by PaperTrail. Why you want dozens of table with the same structure?
