### ISSUE TITLE
Admin: Keyrelay only partially removed

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1426]
There are errors in the logs from admin interface that is looking for keyrelay table.

Related to #715 

> Nov 29 14:00:41 test-reg ADMIN[16214]: [testadm] [7f249aef-e028-4f09-88c0-5dabeef271a5] [172.16.248.5] Completed 500 Internal Server Error in 58ms (ActiveRecord: 20.3ms)
> Nov 29 14:00:41 test-reg ADMIN[16214]: [testadm] [7f249aef-e028-4f09-88c0-5dabeef271a5] [172.16.248.5] #012ActionView::Template::Error (PG::UndefinedTable: ERROR:  relation "keyrelays" does not exist#012LINE 5:                WHERE a.attrelid = '"keyrelays"'::regclass#012                                          ^#012:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),#012                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod#012                FROM pg_attribute a LEFT JOIN pg_attrdef d#012                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum#012               WHERE a.attrelid = '"keyrelays"'::regclass#012                 AND a.attnum > 0 AND NOT a.attisdropped#012               ORDER BY a.attnum#012):#012    11:           %th{class: 'col-xs-2'}= t(:accepter)#012    12:           %th{class: 'col-xs-1'}= t(:status)#012    13:       %tbody#012    14:         - @domain.keyrelays.includes([:requester, :accepter]).order(pa_date: :desc).each do |x|#012    15:           %tr#012    16:             %td= link_to(x.pa_date, [:admin, x])#012    17:             %td= x.expiry#012  app/views/admin/domains/partials/_keyrelays.haml:14:in `_app_views_admin_domains_partials__keyrelays_haml___1172657118214148997_47041031996680'#012  app/views/admin/domains/show.html.erb:62:in `_app_views_admin_domains_show_html_erb___3072294832580202778_47041012755040'

**Comment by vohmar** [comment]
keyrealay reference are in domain detail view and there is separate keyrelay menu also. Missing keyrelay table renders domain detail view unusable

**Comment by artur-beljajev** [comment]
`PG::UndefinedTable: ERROR: relation "keyrelays"` there is no such table in the database. Try to redeploy.
