### ISSUE TITLE
Invoice generation returns Internal error

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1427]
We have a problem in production with internal error returned to user on invoice creation. The invoice is actually created but user does not realise that until going back to billing view

Error in log indicates e-invoice related issue:

> Dec  2 14:47:14 reg-l-rar REGISTRAR[3000]: [registrar] [42a039b7-98b2-453a-b1b8-e5f4ebe8f667] [172.16.249.48] #012Savon::UnknownOperationError (Unable to find SOAP operation: :e_invoice#012Operations provided by your service: []):#012  app/models/registrar.rb:102:in `issue_prepayment_invoice'#012  app/models/deposit.rb:36:in `issue_prepayment_invoice'#012  app/controllers/registrar/deposits_controller.rb:11:in `create'

**Comment by teadur** [comment]
seems related to #1248 missing proper error handling

**Comment by artur-beljajev** [comment]
There was some temporary issue on e-invoice provider side, which is now fixed.
