### ISSUE TITLE
Admin: contact view returns internal error

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1458]
After the last deployment most of the contact views return internal error in admin.

![image](https://user-images.githubusercontent.com/7734747/71668528-f4cf4480-2d71-11ea-9393-755017926426.png)

to reproduce:
1. login to the admin
2. select contacts view
3. open any contact - internal error is returned

same happens when using domains view and trying to open contact view from domain view

error in log;
Jan  2 15:03:52 reg-l-epp ADMIN[4459]: [d8d5e69c-8efe-440c-894b-5915539f2eff] [reg-l-adm.infra] [192.168.2.45] ActionView::Template::Error (undefined method `admin_api_user_path' for #<#<Class:0x00007f1d1921da58>:0x00007f1d17ba2260>#012Did you mean?  admin_api_users_path#012               admin_admin_user_path#012               admin_admin_users_path#012               admin_api_users_url):

**Comment by yulgolem** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [zzz](https://trello.com/c/3d1PPJIS/1-zzz)
