### ISSUE TITLE
RegistrantConfirmation: internal error on confirmation and rejection

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1468]
1. new person wants to take over a domain
2. request is made by registrar
3. Confirmation request is sent to current registrant by the registry system
4. Current registrar opened the email and clicks on the provided link to confirm or reject the change
5. User presses confirmation button on the confirmation page 
6. Internal error is returned and pending Change request is not confirmed nor denied.

log records:
Completed 500 Internal Server Error in 16ms (ActiveRecord: 3.3ms)
ActiveModel::UnknownAttributeError (unknown attribute 'uuid' for RegistrantVerificationVersion.):
app/models/registrant_verification.rb:27:in `domain_registrant_change_reject!'#012[...] [registrant] [...] app/controllers/registrant/domain_update_confirms_controller.rb:25:in `update'

**Comment by vohmar** [comment]
is registrant change with confirmation covered with autotests?

**Comment by vohmar** [comment]
the problem is fixed but missing test coverage

**Comment by yulgolem** [comment]
I'll add it, will try today.

**Comment by vohmar** [comment]
fixed by #1469 and #1472
