### ISSUE TITLE
ForceDelete: poll message on setting force delete

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1478]
Subissue to #1428 

Single type of poll message for setting force delete 

There are currently two types simple version that is sent when either "soft" or "hard" force delete is set
Force delete set on domain timo-4a.ee

And detailed version, that is sent when the last 45 period starts in the soft forcedelete process
For domain timo-4a.ee started 45-days redemption grace period, ForceDelete will be in effect from 2020-01-17 22:00:00 +0200

Propose this message 
Force delete is set on domain timo-4a.ee. 
DNS delegation stop date: 2020-02-02. 
Purge date: 2020-03-03

**Comment by vohmar** [comment]
* outzone date is equal to force_delete_start date. Should be force_delete_start_date + Expire warning period - in case exp date is further than a year away.
* purge date should be +1 as force_delete_start_date + expire warning (15) + redemption grace (30) equals the last day of the registration. Domain name is actually released to auction at the beginning of the next day.

**Comment by vohmar** [comment]
* hard force - purge date without time. Value of force_delete_date should be +1 (currently is start date + exp warning + redemption grace)
* soft force with valid to further than a year away - purge date without time. force_delete_date should be +1
* soft force with valid to closer than a year away - purge date with time. Value OK

PS: force_delete_date can be dropped if this would improve/simplify logic - it can be calculated from force_delete_start or if that is not set then from valid_to date

**Comment by yulgolem** [comment]
Fixed format, added tests for format/values.

**Comment by vohmar** [comment]
I am so sorry, but i made a mistake in date calculation so now purge date in all the scenarios is 1 day too late.  Please remove the +1 and then we can close this one, as I have not spotted any other errors.

**Comment by vohmar** [comment]
fixed by #1483
