### ISSUE TITLE
ForceDelete: clientHold is reset every time the task is run

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1480]
related to #1428 

Once the time to set clientHold is reached in the forceDelete process the clientHold status is reset every time the task is run. So in case of production this is once per day. Upon every such event also polle message is sent to the registrar.

task responsible for setting clientHold status should check if either clientHold or serverHold status is already set and if so it should not try to reset the clientHold status.

**Comment by vohmar** [comment]
the cron job output still returns message about applying clientHold to domains that already had it - no new poll message is sent and domain data is not updated, so it look like the problem is just with the job output.

**Comment by yulgolem** [comment]
> the cron job output still returns message about applying clientHold to domains that already had it - no new poll message is sent and domain data is not updated, so it look like the problem is just with the job output.

Fixed. The only output mandatory now is a message on job start/end, message on status change occurs only on status change.

**Comment by vohmar** [comment]
fixed by #1485
