### ISSUE TITLE
Resend e-invoices if any error occurs

### ISSUE THREAD

**Issue by yulgolem** [internetee/registry#1509]
See https://github.com/internetee/e_invoice/issues/2, resolving on registry side.

**Comment by yulgolem** [comment]
@vohmar , could you, please, describe the situations in which we are sending e-invoices from registry?

I did some additions to registrar#issue_prepayment_invoice method but not 100% sure it's the only occurrence.

**Comment by yulgolem** [comment]
OK, seems what the e-invoice sending is from registrar only.

**Comment by vohmar** [comment]
yes we currently send e-invoices only from registrar portal, but we should add this feature to auction as well in near future - just to keep in mind

**Comment by vohmar** [comment]
closed by #1510
