### ISSUE TITLE
Resolve money gem deprecation warnings

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1513]
Deploy and Travis logs are full of money gem deprecation warnings. Should resolve that to make the output relevant and readable.

`[DEPRECATION] You are using the default localization behaviour that will change in the next major release. Find out more - https://github.com/RubyMoney/money#deprecation`

**Comment by vohmar** [comment]
I see two options here - fix how we use the gem to comply with new versions approach or try to drop using money gem. Latter option has one still failing attempt https://github.com/internetee/registry/pull/1365. Main issue there is the conversion of values from cents to euros (from integers to floats) presumably to avoid converting values to euros and back each time the value is presented to or received from UI.

**Comment by yulgolem** [comment]
Resolved without new code by https://github.com/internetee/registry/pull/1495

**Comment by vohmar** [comment]
fixed by #1495
