### ISSUE TITLE
Verify that ActionController::Parameters is not handled as Hash subclass

### ISSUE THREAD

**Issue by karlerikounapuu** [internetee/registry#1519]
From Rails 5.1, ActionController::Parameters isn't subclass of Hash anymore. To prevent further similar issues such as #1516 , rest of codebase should be checked also for similar pitfalls.

**Comment by yulgolem** [comment]
Cannot find any occurrences of direct using of old-fashioned params in the model code. That's doesn't mean there is no any, so I suppose we shouldn't close this one yet, just use this issue for future PRs if any.
Let's return to this, say, after a month or so.
