### ISSUE TITLE
EPP requests are double saved in archive tables

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1526]
After deploying the latest release to production all new records in log_domains, log_contacts, log_users tables were saved in two copies.

**Comment by vohmar** [comment]
we returned EPP server to previous state and creating double records stopped

The release description: https://github.com/internetee/registry/releases/tag/200211

**Comment by yulgolem** [comment]
Upped papertrail gem version doubles the versions saved on save! method.
I'll continue the investigation.

**Comment by yulgolem** [comment]
Guess I've found it.
Due to some changes in papertrail double-assigning of `has_paper_trail` (in model and in the concern) now creates twice the callbacks on a models.

Fix PR in underway.

**Comment by vohmar** [comment]
the log_users was wrong alarm. It seems only log_contacts and log_users have the double records' problem.

**Comment by yulgolem** [comment]
Yep, log_contacts & log_domains. Will be in a second.
