### ISSUE TITLE
warnings on running cron jobs

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1530]
WARNING: Use strings for Figaro configuration. true was converted to "true".
/home/registry/deploy/releases/20200213114627/app/models/concerns/versions.rb:7: warning: already initialized constant Versions::WITH_CHILDREN
/home/registry/deploy/releases/20200213114627/app/models/concerns/versions.rb:7: warning: previous definition of WITH_CHILDREN was here
/home/registry/deploy/releases/20200213114627/app/models/concerns/versions.rb:7: warning: already initialized constant Versions::WITH_CHILDREN
/home/registry/deploy/releases/20200213114627/app/models/concerns/versions.rb:7:

seen on running DomainCron.start_expire_period, DomainCron.start_redemption_grace_period and domains:release

**Comment by vohmar** [comment]
the first one is still there

WARNING: Use strings for Figaro configuration. true was converted to "true".

**Comment by yulgolem** [comment]
As per [this Figaro issue](https://github.com/laserlemon/figaro/issues/192) we need to store values in application.yml in strings only - just key-value storage with string values (not arrays or so).

Modified application.yml and usage, please, check again. If everything is fine, I'll add changes to application.yml.sample as well, if not - will continue.

**Comment by vohmar** [comment]
the Figaro warning is still there:
WARNING: Use strings for Figaro configuration. true was converted to "true".

spotted new exceptions on deployment that haven't seen before:

undefined method `strip' for nil:NilClass

https://errbit.internet.ee/apps/5bcf2b35d9d1af5a21961be2/problems/5e465133d9d1af29e7e51bb4

the cron jobs fail with the same exception

**Comment by yulgolem** [comment]
Warning occurs on staging only, not in live or test. Suppose it might be because we are generating application.yml by ansible every deploy, and maybe we are passing some non-sting values like boolean or hash or something to the ansible template.

I'll pass this issue to @ratM1n .

**Comment by vohmar** [comment]
fixed by #1531
