### ISSUE TITLE
unable to update nameservers in some cases

### ISSUE THREAD

**Issue by rdk01** [internetee/registry#1562]
It's not very common to use primary domains as nameservers, but theoretically it should work exactly the same way as with subordinate hosts > the zone will have a glue record for the primary domain.

At the moment, the zone will have no glue records in such cases.
The example is illustrated below:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd">
  <command>
    <update>
      <domain:update xmlns:domain="https://epp.tld.ee/schema/domain-eis-1.0.xsd">
        <domain:name>ns1.ee</domain:name>
        <domain:add>
          <domain:ns>
            <domain:hostAttr>
              <domain:hostName>ns1.ee</domain:hostName>
              <domain:hostAddr ip="v4">1.1.1.1</domain:hostAddr>
            </domain:hostAttr>
            <domain:hostAttr>
              <domain:hostName>ns2.ee</domain:hostName>
            </domain:hostAttr>
          </domain:ns>
        </domain:add>
      </domain:update>
    </update>
    <clTRID>request-1583830206-a0d1df0828df934b7a6d90f78347a318</clTRID>
  </command>
</epp>
```

![scr-1](https://user-images.githubusercontent.com/12309591/76301860-aa18fe00-62c7-11ea-8565-e4891702db90.png)

![scr-2](https://user-images.githubusercontent.com/12309591/76301866-adac8500-62c7-11ea-9681-6772988a0d8f.png)

**Comment by vohmar** [comment]
@rdk01 thank you for the detailed report! We'll take a look at it as soon as possible. Is this an urgent task for you?

**Comment by rdk01** [comment]
Our customer will use a workaround until the issue is resolved, so it is not very critical.

**Comment by vohmar** [comment]
@rdk01 the fix is in production. Both issues - the response to adding second level domain as host and adding such glue to zone are working now. Thank you again for such a good and detailed report.
