### ISSUE TITLE
Change settings storage mechanism

### ISSUE THREAD

**Issue by yulgolem** [internetee/registry#1629]
Currently Registry app uses Setting as per rails-settings-cached gem. While good in storing some seldom changing data like settings, this gem is bad in storage of, say, invoice numbers (see https://github.com/internetee/registry/issues/1600) and such due to non-transparent caching system.
We need to change this setting storage mechanist to something similar to system used in Auction app.

**Comment by karlerikounapuu** [comment]
Agreed. The current implementation of settings is not able to track updated settings in a friendly manner. In a nutshell, when setting is updated via UI, it's updated in database. Ocassionally, however it fails to deliver such changes to cache, and the thing with cache is it's queried first via `Setting.st_name` and updates in db are ignored (extremely noticeable when settings are queried-updated from different sources).

I like the current approach implemented in auction app as well. It's not hard to implement. If it goes through, I would ideally keep most-likely-updatable settings in database (directo number, other kinda dynamic data) without cache. And other ones in yml (reloadable)
