### ISSUE TITLE
Registrant API does not return data of contacts that the user owns

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1642]
Registrant API returns only the details of contacts that are directly related to the user either by personal identity nr or the company register (separate request to business registry). The user is obliged to have access also to contacts that are associated with the domains the users owns (being the role of a registrant (directly or through a company) or admin contact).

For example

exampledomain1.ee has three contacts someRegistratn (registrant), theUser (admin contact), someTechContact (tech contact). The user need to be able to query data of the someRegistrant and someTechContact objects as well as their own theUser contact.

exampledomain2.ee has three contacts someCompany (registrant), someAdminContact (admin contact), someTechContact2 (tech contact). The user is  a manager of the someCompany according to the business registry query. The user needs to be able to query date of all three contact objects as a registrant of the exampledomain2.ee

**Comment by yulgolem** [comment]
Need some info.

1) From CompanyRegister we've got an array of some registration numbers. I assume that these registration numbers are contact idents for contacts with ident_type == 'org', right?
2) The registrant domains must be all the domains where registrant/admin contacts are contacts with the same country/id with Registrant, PLUS the domains where registrants are companies from the previous step, correct?
3) The registrant contacts must be all contacts for the domains from the previous step?

**Comment by yulgolem** [comment]
From email:

1) correct - these are company registration numbers where the personal identity number is marked as a board member. So yes contact objects with ident_type org and country code EE

2) Terminology wise there is a difference between registrant and admin contact - first one is the owner, second is representative of the owner. Admin has almost all the privileges and rights of the registrant except changing admin contacts and confirming registrant changes and deletions. Most importantly both have full access to all the data related to a registration they are assigned to. But we should not forget the technical contacts. We have to protect personal data, but domains that belong to organisations do not have personal data, as all the other contacts related to such domains are just representatives of the business registrant and their data in those roles is handled as business data. So the list of domains that a user must have full access to including all the related contact objects consist of
* domains that the user is in the role of registrant or admin contact
* domains that the user is in the board of the registrant with type org (previous step)
* domains that the user is in the role of technical contact and the registrant has ident type org

3) logged in user must have access to all the active (unarchived) contact objects that share their ident code with country code and ident_type = priv, plus all other contact objects associated to the list of domains from the previous step
