### ISSUE TITLE
Postal addresses are saved when address processing is disabled

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1650]
Registry system saves contacts' postal address regardless of the postal address proessing setting.

Correct behavior is ignoring the postal address data sent by the registrar and notifying registrar about it. Disabling address processing makes postal address records in the contact objects optional so registrar can still send the data but registry does not save it and returns notification about it.

**Comment by karlerikounapuu** [comment]
Is it known which actions ignore postal address processing setting? Eg. EPP contact update, via X Portal, via API etc... Or is it global issue?

We used to refactor Contact XML parser some time ago, maybe we missed something while at it.

**Comment by vohmar** [comment]
its contact create and contact update ie the flows that create or edit contact objects over EPP and Rest-EPP.  Also transfer as there are new contact objects potentially created in that process as well.

We tend to return everything we have on any objects on info requests for transparency reasons unless there is an issue in relation to personal data protection.
