### ISSUE TITLE
Registrant TARA integration

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1701]
Mobile-ID auth is not working on registrant portal since 1st of October due to SK switching to new API. Initial plan was to setup registrant to use our on-premise version of tara but as this is not ready yet at users are asking about mID auth we should integrate RIA's TARA

client_id: registrant
callback: https://registrant.internet.ee/registrant/auth/callback

**Comment by karlerikounapuu** [comment]
Closed via #1698
