### ISSUE TITLE
Regsitrant API: return company regsitration number list together with list of domains

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1706]
When registrant portal requests list of domains belongign to logged in user from the registrant API, API requests comapny registration numbers from Estonian Business Regsitry associated to the personal id of the user and then returns to the portal list of domains associated with the user directly or through the companies the users is responsible for.

Returned domains list should also include the list of business registry numbers API used to form the list so portal can return that list as well to inform the user of information used to compose the domains' list

**Comment by karlerikounapuu** [comment]
Not going to happen as we need additional data from business registry to compose 'my companies' view.
