### ISSUE TITLE
Admin - Add new bank transaction: undefined method `paid?' for nil:NilClass 

### ISSUE THREAD

**Issue by OlegPhenomenon** [internetee/registry#1788]
When trying to bind manually new bank transaction in admin panel, there is an error: Add new bank transaction: undefined method `paid?' for nil:NilClass 

Reproducing the error step by step:
1. Go settings and click to Invoice
2. Select some unpaid invoice
3. Click to "Payment received"
4. Click to save
5. Click to add in Bank Transaction sections
6. Fill in the fields
7. Left empty field binded invoice or type something and click "Bind manually"

**Comment by vohmar** [comment]
fixed by #2075
