### ISSUE TITLE
Registrar: Validation contacts name - Special characters instead of letters

### ISSUE THREAD

**Issue by OlegPhenomenon** [internetee/registry#1795]
If during the creation of a new contact you type a different number of characters, for example ¤ # "¤ #" ¤ "?,then the form allows you to create a new contact with that name.

**Comment by yulgolem** [comment]
BTW FYI https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by vohmar** [comment]
fixed by https://github.com/internetee/registry/pull/2074

**Comment by yulgolem** [comment]
Reopened (PR reverted) since one of our clients with name containing "&"-character could not make any changes to the contact name.
Asked Silver on legal limitations we have on this account, let's set this task on hold until we got a knowledge on what characters should we allow/block.

**Comment by yulgolem** [comment]
According to [technical terms and conditions ](https://meedia.internet.ee/files/Appendix%201_Registrar_Contract_EN_01.07.2020.pdf)of our contracts (courtesy of Silver Sõrmus) we got no legal restrictions on any naming whatsoever - so even name of `¤ # "¤ #" ¤ "?` is completely legal. So my proposal is to close this issue.
