### ISSUE TITLE
Registrar: Validation birthday field in Contact - Allow a non-existent date of birth

### ISSUE THREAD

**Issue by OlegPhenomenon** [internetee/registry#1796]
Steps:
1. Go to contacts and create a contact
2. Choose any country instead of Estonia
3. In the type field select the date of birth
4. Type tomorrow or any future day in the birthday field

The form creates a contact with a date of birth that will happen in the future

UPDATE:
Also the form skips non-existent dates, for example 0000-34-35

**Comment by yulgolem** [comment]
@vohmar do we have any legal regulations on correct age? Like "no younger than 18 years old" or smth like that?
