### ISSUE TITLE
Registrar: bulk ns change - domain list is ignored if csv is missing header row

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1813]
If uploaded csv for nameserver bulk change is incorrectly formatted it is ignored and the nameserver change is run for the full list of that registrar's domains.

This creates error prone situation where change potentially affects domains that it is not supposed to.

Instead if incorrectly formatted file is uploaded the whole request should fail or it should be treated as empty list - the change request must not affect any domains.

**Comment by yulgolem** [comment]
Do we still need this? @vohmar

**Comment by vohmar** [comment]
yes, this is still an issue. used csv file with missing header row and bulk change was applied to all domain registrations of the registrar. Tested on current master branch.

Expected result is that if csv file is attached to the bulk request the change can be applied only to the domainregistrations in that list. That means if the csv file is malformed or empty no domains should be affected by the change
