### ISSUE TITLE
EPP: domain:delete does not fill outzone_at

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#182]
successful domain:delete query leaves outzone_at blank. The delete_at field is filled and onHold status is set.

System has to fill the outzone_At with time and date the onHold status was set.

**Comment by artur-beljajev** [comment]
@vohmar Is it about this action?

app/controllers/epp/domains_controller.rb:73

**Comment by artur-beljajev** [comment]
Please check the code

**Comment by vohmar** [comment]
@artur-beljajev this code seems to update the outzone_at value every time onhold is set. The issue at hand is only in relation to domain:delete operation where the outzone date is left blank. On other cases like expiration the outzone_at value is precalculated from valid_to date - not sure if this might be a problem when this value is overwritten on setting the serverHold status. But lets test this - merge to staging if you are sure this works.

**Comment by artur-beljajev** [comment]
I am not sure what code is meany by "expiration", but Domain#set_server_hold is also called here app/jobs/domain_delete_confirm_job.rb:11

**Comment by artur-beljajev** [comment]
Merged with staging

**Comment by vohmar** [comment]
@artur-beljajev good job, works like a charm! But Can’t automatically merge. Please fix the merge conflicts to master.

**Comment by artur-beljajev** [comment]
There are no conflicts. Merged. If possible, please create separate tickets for releases.

**Comment by vohmar** [comment]
each ticket is a separate release. I could not merge https://github.com/internetee/registry/tree/registry-182 into master. Please revert the staging commit to master and fix branch 182 so it could be merged separately into master branch.

**Comment by artur-beljajev** [comment]
"Please revert the staging commit to master and fix branch 182 so it could be merged separately into master branch."

If I do this, we lost changes that were committed directly to staging and the changes that were merged from other feature branches.

**Comment by vohmar** [comment]
@artur-beljajev you need to resolve merge conflicts of branch https://github.com/internetee/registry/tree/registry-182 to master

**Comment by vohmar** [comment]
@artur-beljajev does not work

```
undefined method `on_hold_time=' for #<Epp::Domain:0x007f4c80511e80>
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.5.2/lib/active_model/attribute_methods.rb:433:in `method_missing'
/home/registry/registry/releases/97/app/models/domain.rb:702:in `set_server_hold'
/home/registry/registry/releases/97/app/models/epp/domain.rb:588:in `set_pending_delete!'
/home/registry/registry/releases/97/app/models/epp/domain.rb:547:in `apply_pending_delete!'
/home/registry/registry/releases/97/app/jobs/domain_delete_confirm_job.rb:11:in `block in run'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:220:in `transaction'
/home/registry/registry/releases/97/app/jobs/domain_delete_confirm_job.rb:5:in `run'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/job.rb:15:in `_run'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/job.rb:99:in `block in work'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/adapters/active_record.rb:5:in `block in checkout'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/adapters/active_record.rb:34:in `checkout_activerecord_adapter'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/adapters/active_record.rb:5:in `checkout'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/job.rb:82:in `work'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/worker.rb:78:in `block in work_loop'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/worker.rb:73:in `loop'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/worker.rb:73:in `work_loop'
/home/registry/registry/releases/97/vendor/bundle/ruby/2.2.0/gems/que-0.10.0/lib/que/worker.rb:17:in `block in initialize'
```

**Comment by vohmar** [comment]
branch https://github.com/internetee/registry/tree/registry-182 merged to master and deleted.
Closed
