### ISSUE TITLE
Domain delete is prohibited when *UpdateProhibited status is set

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1844]
client/serverUpdateProhibited status on a domain object affects only domain:update requests (registrant change, adding/removing admin and tech contacts, nameservers and dnssec keys). It does not affect other EPP/REPP operations like renew, transfer and delete.

Issue: domain:delete request for a domain registration with client/serverUpdateProhibited results with 2304

    <result code="2304">
      <msg lang="en">Object status prohibits operation</msg>
    </result>

**Comment by vohmar** [comment]
after this update even domain update is allowed for domains with serverUpdateProhibited status. So yes delete works now, but domain:update should be still denied. *UpdateProhibited status should affect only domain:update requests in case of EPP.

**Comment by yulgolem** [comment]
Suppose because there was no tests on this for some reason.
Tests added, as well as fix.
