### ISSUE TITLE
Consider removing "et" locale support

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#185]
- https://github.com/internetee/registry/blob/master/config/locales/et.yml is outdated
- There is no language selector in UI

**Comment by vohmar** [comment]
locale support is important for portal for registrars and registrant and ee direkt. The locale support is just not implemented jet, but is in todo list. First priority is implementing it to portal for registrants.

**Comment by artur-beljajev** [comment]
@vohmar I consider bad practice having half-done code in master (=production) branch.

**Comment by vohmar** [comment]
@artur-beljajev agreed, I cannot comment on why this half done code is in master, but lets put the efforts in making it work

**Comment by artur-beljajev** [comment]
app/models/directo.rb:65

**Comment by artur-beljajev** [comment]
app/views/mailers/contact_mailer/email_updated.html.erb:12

**Comment by artur-beljajev** [comment]
Estonian locale is/will be used in Directo and mailers, hence closing.
