### ISSUE TITLE
Consider removing "rubocop" tags

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#187]

**Comment by teadur** [comment]
I think we should continue using rubocop and if we want to disable some checks what wont make sense, we should push them to project wide rubocopy configuration yml and after that we can start removing them from source files.

**Comment by artur-beljajev** [comment]
1. This ticket is about tags in the codebase, not rubocop itself. 
2. Such configuration does already exist at `.rubocop.yml` and it is full of such comments as

- "annoying to maintain, small thing, no real problem"
- "let's save  space in spec", 
- "a bit too annoying requirement"
- "turn off comment intention check during development"
- "It did not alayws suggested good format"
- "No need fancy style of numbers such as 1_000_000"
- "not working perfectly or not important enough to care"

What's the point of employing code checker, and then eventually turn off the majority of checks? I consider this as a waste of time with no value and propose to really think about the value we get from this tool.

**Comment by teadur** [comment]
1. I agree that we could remove the tags from code, im merely sayng we should disable checks what we want in global level rather then in source files.

2. I agree that there is no point in employng code checker and turning off majority of checks, i think we should only disable check what make sense.

So in your end sentence you are proposing we should drop rubocop or just sayng we should re-enable checks what are disabled at global level ?

**Comment by artur-beljajev** [comment]
That's a good question. My experience of using such linters as rubycop is that we get the best return if we installed and configured it once and forget about it. If you end up with relaxing the majority of checks and especially start tagging classes and methods just to satisfy linter's requirements (like our case), it's not worth it, IMHO.

It's also important to make it run on every build, or otherwise it will be just ignored most of the time.

**Comment by artur-beljajev** [comment]
@teadur Current rubocop config violates our established coding conventions. I would like to run codeclimate against feature branch to test new rules, but I cannot see any configs. I guess I don't have permissions?

**Comment by artur-beljajev** [comment]
Fixed by #187

**Comment by artur-beljajev** [comment]
Oh, I linked the wrong ticket, now it is correct. See https://github.com/internetee/registry/commit/a7ea80a9345755251d0063f70590faa6a5ceedf7 for details
