### ISSUE TITLE
Install mailcatcher on staging

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#188]
- https://mailcatcher.me
- Change SMTP in config/environments/staging.rb
- Remove whie-list https://github.com/internetee/registry/search?utf8=%E2%9C%93&q=whitelist

NB! "Please don't put mailcatcher into your Gemfile. It will conflict with your applications gems at some point."

**Comment by teadur** [comment]
Mailcatcher installed.

**Comment by vohmar** [comment]
@artur-beljajev is this now part of standard deployment as development environment? It has to be. If it cannotbe deployed automatically there has to be guide in the documentation: https://github.com/internetee/registry/blob/master/doc/application_build_doc.md

**Comment by artur-beljajev** [comment]
In general, MailCatcher acts as a dedicated SMTP server, and our app knows nothing about it. Other registry may or may not use it. @teadur configured it on staging env, so he can provide further info if needed.

**Comment by teadur** [comment]
I would have to agree that its just a choice of solution, not something that is needed for the dev/staging env to work. Someone else could be running something else for this or maybe they want to actualy deliver the email, as information we can include it in documentation but for sure it isnt dependency what is actualy needed for the dev env.

**Comment by artur-beljajev** [comment]
@teadur , you configured mailcatcher on staging using application.yml?

**Comment by teadur** [comment]
@artur-beljajev no its configured in enviroinments/staging.rb

**Comment by artur-beljajev** [comment]
Really? Didn't we just removed it and let Mina does its job?

As I see, application.yml has smtp config, and I wonder why it is not configured there.

**Comment by teadur** [comment]
@artur-beljajev we removed it from git, that doesnot mean it isnt used in deployment procedure.
You asked if we use applicaiton.yml for that i answered no.
In theory we could use application.yml aswell but  enviroinments/staging.rb overwrites application.yml values anyways if you are running staging env.

**Comment by teadur** [comment]
Updated the docs to mention mailcatcher

**Comment by vohmar** [comment]
@teadur thank you, but cannot find the branch to merge changes to master

**Comment by vohmar** [comment]
closed
