### ISSUE TITLE
Admin: Domain history - search results with internal error

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1889]
On test and production (current master branch)
/admin/domain_versions

any kind of search attempt including also changing the value of results per page results in internal error

issue present on prod and test envs
log:
https://gist.github.com/ratM1n/e9b52c13299c6fe34c2c43a41bb8e611

**Comment by yulgolem** [comment]
Cannot reproduce on staging/master branch, looks like fix is already in master.

**Comment by vohmar** [comment]
was resolved with https://github.com/internetee/registry/pull/1886
