### ISSUE TITLE
Implement regular and automated gem version updating

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1891]
We are updating gems mostly when there are some security issues published that GitHub picks up or to get rid of deprecation warnings meaning that we use a lot of old and outdated software components. This creates security risks and makes updating core components like Ruby or Rails that much more difficult due to loads of gems requiring updates.

To solve this issue we should implement regular and if possible automated process of keeping gems up to date.

one option for automating gem version updates: bummr (https://github.com/lpender/bummr), but there are other options available as well like gemnasium 
article on the topic: https://thoughtbot.com/blog/keep-your-gems-up-to-date

**Comment by yulgolem** [comment]
Implemented in registry & auction center via Github Dependabot, will continue on another projects.
