### ISSUE TITLE
REPP: consider moving auth key value from header to body in transfer request

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1895]
https://internetee.github.io/repp-apidoc/#transfers

in REPP transfer request the auth-code is placed in the header of the request. This is the only request where any request elements are placed in header in stead of request body (incl. domains register and change ).

Cannot explain why this approach is better here so suggest to consider changing the auth_code to be set in request body similarly to the logic of other REPP requests.

**Comment by yulgolem** [comment]
Well, unfortunately we are using GET request there.
From the HTTP 1.1 2014 Spec:
```
A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.
```

So we should not use a body with any GET request.

**Comment by vohmar** [comment]
No change needed here
