### ISSUE TITLE
There has inconsistency in WHOIS plain text body.

### ISSUE THREAD

**Issue by tanelj** [internetee/registry#19]
There has inconsistency in WHOIS plain text body. All WHOIS response section headers are ending with colon except the "Administrative contact".

https://github.com/internetee/registry/blob/322d7e64e729cbd761fe9b583831f23863639e90/app/views/for_models/whois.erb

**Comment by kritik** [comment]
@tanelj  Thanks for note. Will fix soon

**Comment by teadur** [comment]
indeed, thank you should arrive to production soonish
