### ISSUE TITLE
Domain Disputes: status is not closed after registrant change nor is the pw required

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1927]
Disputed list is for domains that have gone through the domain dispute committee and got the decision to the detriment of the current owner. The decision is in force for 3 years and is removed from the disputed list once the registrant has been changed or the dispute decision expires.

Problems:
* disputed decision is not automatically removed once the registrant has been changed.
* was able to successfully change registrant of the disputed domain without valid password
* epp schema is missing disputed status causing errors in case of response validation: 

`Invalid response to -> Info_Domain (some-domain-name.ee) - Corrupted: DOMDocument::schemaValidate(): Element '{https://epp.tld.ee/schema/domain-eis-1.0.xsd}status', attribute 's': [facet 'enumeration'] The value 'disputed' is not an element of the set {'clientDeleteProhibited', 'clientHold', 'clientRenewProhibited', 'clientTransferProhibited', 'clientUpdateProhibited', 'inactive', 'ok', 'expired', 'pendingCreate', 'pendingDelete', 'pendingRenew', 'pendingTransfer', 'pendingUpdate', 'pendingDeleteConfirmation', 'serverDeleteProhibited', 'serverHold', 'serverRenewProhibited', 'serverTransferProhibited', 'serverUpdateProhibited', 'serverForceDelete', 'serverManualInzone', 'serverRegistrantChangeProhibited', 'serverAdminChangeProhibited', 'serverTechChangeProhibited', 'deleteCandidate'}.`

**Comment by yulgolem** [comment]
Since we are migrating from Que to Sidekiq, I'm afraid the command used to run `DisputeStatusUpdateJob` must be changed.

```
registry@staging:~/deploy/current$ bin/rails r -e staging "DisputeStatusUpdateJob.run"
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

Please specify a valid ruby command or the path of a script to run.
Run 'rails runner -h' for help.

undefined method `run' for DisputeStatusUpdateJob:Class
```
```
registry@staging:~/deploy/current$ bin/rails r -e staging "DisputeStatusUpdateJob.perform_now"
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

I, [2021-04-16T11:00:14.170802 #24250]  INFO -- : DisputeStatusUpdateJob - Found 0 closable disputes
I, [2021-04-16T11:00:14.173309 #24250]  INFO -- : DisputeStatusUpdateJob - Found 0 activatable disputes
I, [2021-04-16T11:00:14.174863 #24250]  INFO -- : DisputeStatusUpdateJob - All done. Closed 0 and activated 0 disputes.
```

@ratM1n so the correct command now is `bin/rails r -e staging "DisputeStatusUpdateJob.perform_now`, let's check it on prod.

**Comment by vohmar** [comment]
There is still some issue here - steps to reproduce @ staging

1. add a domain to disputed list in admin (start date - today)
2. run DisputeStatusUpdateJob.perform_now - result
I, [2021-04-20T16:25:36.503560 #26530]  INFO -- : DisputeStatusUpdateJob - Found 1 activatable disputes
I, [2021-04-20T16:25:37.186326 #26530]  INFO -- : DisputeStatusUpdateJob - Failed toactivate dispute for 'timoajalugu15.ee'
3. check that disputed status is still set on the domain
4. domain:update to change registrant (verified - no, reserve, pw missing) - registrant change is successful (no error for required password, no registrant confirmation), domain has still the disputed status
5. re-run DisputeStatusUpdateJob.perform_now
I, [2021-04-20T16:38:18.911203 #27633]  INFO -- : DisputeStatusUpdateJob - Found 1 activatable disputes
I, [2021-04-20T16:38:19.642834 #27633]  INFO -- : DisputeStatusUpdateJob - Failed toactivate dispute for 'timoajalugu15.ee'

**Comment by yulgolem** [comment]
@ staging atm:
```
I, [2021-04-21T14:10:39.358140 #2192]  INFO -- : DisputeStatusUpdateJob - activated dispute  for '16366.ee'
I, [2021-04-21T14:10:39.358358 #2192]  INFO -- : DisputeStatusUpdateJob - All done. Closed 0 and activated 1 disputes.
```

**Comment by yulgolem** [comment]
On dispute creation date must be explicitly set as today.

**Comment by yulgolem** [comment]
Date set as today. Still cannot reproduce registrar change without pw.
