### ISSUE TITLE
Establish coding style guides

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#194]
https://google.github.io/styleguide/htmlcssguide.xml
https://google.github.io/styleguide/javascriptguide.xml
https://google.github.io/styleguide/xmlstyle.html
https://github.com/bbatsov/ruby-style-guide
https://github.com/bbatsov/rails-style-guide

**Comment by artur-beljajev** [comment]
@ratM1n @teadur 

As you also make some changes, we need to agree on some code style standard. My suggestion is to to stick to above mentioned ones.

**Comment by vohmar** [comment]
@artur-beljajev please use wiki (https://github.com/internetee/registry/wiki) for this kind of information, an issue might not be the best thing to use for agreements that one might need to reference back some time later.

**Comment by artur-beljajev** [comment]
Done
