### ISSUE TITLE
Investigate logging

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#196]
STDOUT << "#{Time.zone.now.utc} DomainCron.start_expire_period: ##{domain.id} (#{domain.name}) #{domain.changes}\n" unless Rails.env.test?

**Comment by artur-beljajev** [comment]
@ratM1n @teadur Could you explain the reason of having above mentioned checks?

**Comment by teadur** [comment]
@artur-beljajev this task is ran from CRON and its stdout is written to seperate logfile not to syslog like other logs.
I dont know why it works differently when tests are ran or whats the reasoning behind it.

**Comment by artur-beljajev** [comment]
@teadur Do we really need this? What was the reason of introducing this feature? Was it because something was buggy or wasn't working properly?

**Comment by teadur** [comment]
if the facility/application name is set correctly, it would make more sense to log it into syslog like everything else.

**Comment by artur-beljajev** [comment]
Why do we need to log this at all?

**Comment by teadur** [comment]
Because we want to.

**Comment by artur-beljajev** [comment]
@teadur I would like to know the reason, if possible.

`STDOUT << "#{Time.zone.now.utc} Contact.destroy_orphans: ##{contact.id} (#{contact.name})\n"`

Such statements produce messy test results (http://prntscr.com/cy8zr4) and I think we should find a better way to solve this problem, but first I need to know the problem this logging solves.

**Comment by mlensment** [comment]
Cron table logging was originally designed to be be ignored in test environment. This line is missing Rails.env.test? check.
