### ISSUE TITLE
Migrate to Sidekiq

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#198]
- Check if it supports keyword arguments in jobs
- Use Rails adapter (ActiveJob)

que gem's drawbacks:
- SQL (with table name) is hardcoded (https://github.com/chanks/que/blob/master/lib/que/sql.rb)
- Active Job is not supported (https://github.com/chanks/que/issues/127)
- Lack of documentation

**Comment by teadur** [comment]
@artur-beljajev the first drawback link is broken.
It seems 1.0.0b does support activejob

To we have any other drawbacks ?

**Comment by artur-beljajev** [comment]
`sidekiq` is the de-facto standard. It uses nosql to manage jobs, which is more efficient. It's really well supported. `que` has 386k downlods, where as `sidekiq` 22M. It is therefore easier to support it.

**Comment by artur-beljajev** [comment]
@vohmar FYI We could start migration step by step

**Comment by maciej-szlosarczyk** [comment]
Migrating to sidekiq introduces redis server which needs is an architecture component that needs to be monitored, managed and updated. This is not really a decision we can make without considering the ops part of it.

**Comment by maciej-szlosarczyk** [comment]
We might be better off with moving to `delayed_job` instead, which supports postgres as the queue backend.

https://github.com/collectiveidea/delayed_job

**Comment by artur-beljajev** [comment]
https://github.com/collectiveidea/delayed_job/blob/master/CHANGELOG.md seems kinda abondoned as well. `sidekiq` is consider de facto standard these days.

**Comment by maciej-szlosarczyk** [comment]
I'd say that [strong second](http://rails-hosting.com/2018/) in popularity and [11 milion downloads](https://rubygems.org/gems/delayed_job) is a good bet if maintaining Postgres as backend is one of our goals. At this point I have no reason to assume that it is not.

![image](https://user-images.githubusercontent.com/2331765/41924434-acf41820-7972-11e8-92be-d60b4128cbf7.png)

**Comment by teadur** [comment]
As of sidekiq would introduce new dependencies to application stack, i would vote for delayed_job.

**Comment by artur-beljajev** [comment]
Closed in favor of https://github.com/internetee/registry/issues/1234.
