### ISSUE TITLE
Admin: Internal error on accessing contact objects

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1990]
Most, not all, contact objects return internal error on attempt to access the detailed view. This issue is reproduceable on prod, staging and test.

Have not yet discovered why some contacts do not have this issue.

One thing instantly noticeable is that in the admin contact list name column is displayed owning registrar name instead of the contact name.

**Comment by yulgolem** [comment]
May be duplicate of  #1987

**Comment by vohmar** [comment]
fixed by #1989
