### ISSUE TITLE
Fix mailers' layout

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#200]
1. Make common layout, so that all emails look the same (cur
2. Consider increasing font size for better accessibility.
3. Unify subject: some are in English, some are in Estonian, some are in both.

**Comment by artur-beljajev** [comment]
@vohmar Do you have any update on this matter?

**Comment by vohmar** [comment]
will put this in todo list. WOuld be nice to solve together with new web interfaces on second half of 2018

**Comment by teadur** [comment]
#243

**Comment by artur-beljajev** [comment]
@vohmar Is there any email template available? (the common one for all outgoing emails).

**Comment by artur-beljajev** [comment]
I am closing this ticket because of inactivity.
