### ISSUE TITLE
check auction status before sending a domain to auction

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#2016]
There needs to be a check before adding a domain to auction table in registry to make sure there is no ongoing auctions for the domain

For example removing domain from disputes list results domain sending to auction, but it might happen that domain has already unfinished auction going on so before adding new record to auction table system must make sure there are no records for the domain in auction table or if there are the latest record must be with status no bids or registered.

**Comment by yulgolem** [comment]
Closed by #2017
