### ISSUE TITLE
Csync crashes on invalid dns records

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#2024]
the registry update process crashes when csync process of monitoring cdnskey records, updating registry and validating the dns record.

**Comment by ratM1n** [comment]
Problem is with "CsyncJob" task. When targeted authoritative DNS is not reachable for some reason, the script will crash. Log from such a crash : https://gist.github.com/ratM1n/3a7bfb657330e1141e736f951b8fb159

**Comment by yulgolem** [comment]
What behaviour we are waiting for?
I could add the timeout processing, but what could we do in that case? Exponential retries?

**Comment by ratM1n** [comment]
We should skip the current record and throw some error to stdoud, stating domain in question and dns which wasn't reachable.
For example:
`[time] <domain name> <dns server's name and|or ip> <reason for error>`

**Comment by ratM1n** [comment]
can you please check what is done in case then log output is as: `I, [2021-06-09T09:16:45.987428 #7353]  INFO -- : CsyncJob: : Reseting state. Reason: Nameserver(s) not reachable / invalid data (secure-empty)`

**Comment by yulgolem** [comment]
Well, what's it, the empty record is unqualified for monitoring.
String generated as per
```
@logger.info "CsyncJob: #{domain}: Reseting state. Reason: " +
                 unqualification_reason(ns_ok, key_ok, result_types)

```
And I see no info about domain in the log message.

**Comment by ratM1n** [comment]
Found one more problem - whois is not updated if dnssec is removed from domain.

**Comment by ratM1n** [comment]
OK, whois updated worked in staging.
