### ISSUE TITLE
orphan message, error ignored: Couldn't find Domain with 'id'=

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#2026]
There are messages like:
orphan message, error ignored: Couldn't find Domain with 'id'=209740

in the epp log.

What is the reason? any way to fix?

**Comment by yulgolem** [comment]
That's from here - https://github.com/internetee/registry/blob/master/app/controllers/epp/polls_controller.rb#L20

According to the code `this could happen if the registrar does not dequeue messages, and then the domain was deleted`.
Looks like system behaves as intended.

**Comment by vohmar** [comment]
So this error happens when registrar requests a poll message (the last one) but the domain referenced has already been deleted?
Do we deque the message automatically if this error occurs?

**Comment by yulgolem** [comment]
Don't think so, but definitely we should.
