### ISSUE TITLE
CI solution

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#203]
we need to set up Continuous Integration solution. GitHub integration is something to keep in mind so that autotest are run on merge/commit to staging for example.

https://github.com/integrations/feature/continuous-integration

deployment guide must also be updated with install and config instructions.

Solutions:
- Travis (https://travis-ci.com/plans, Free for open-source)
- Jenkins

**Comment by artur-beljajev** [comment]
Travis build is set up.

Disadvantages:

- Build starts with random delay, depending on some Travis' resource manager

**Comment by artur-beljajev** [comment]
Travis:

Advantages:
- Cloud solution

Disadvantages:
- Builds start with random delay, depending on some Travis' resource manager. Probably can be solved by changing a plan to paid one

Jenkins

Disadvantages:
- Needs maintaining

**Comment by artur-beljajev** [comment]
Let's see how Travis free plan works.

**Comment by vohmar** [comment]
@artur-beljajev how does this function at the moment? all commits to staging initiate autotests? Why are there so many commits in staging with red cross marking the travis CI build failure - if commit does not pass autotests can it be configured so that commit fails and broken code does not get merged into staging.

**Comment by artur-beljajev** [comment]
Yes, commits to staging initiate all specs running. Build fails since tests are broken, see linked ticket.

**Comment by vohmar** [comment]
@artur-beljajev I cannot find any commits on master branch

**Comment by artur-beljajev** [comment]
See staging.

**Comment by vohmar** [comment]
@artur-beljajev how can i commit this to master?

**Comment by artur-beljajev** [comment]
It is in staging branch

**Comment by vohmar** [comment]
@artur-beljajev that is no use to me - cannot close/accept ticket until it is in master

**Comment by artur-beljajev** [comment]
What I am supposed to do with it then?

**Comment by vohmar** [comment]
cherry-pick the code to separate branch for example

**Comment by artur-beljajev** [comment]
What's the benefit of this additional effort?

**Comment by vohmar** [comment]
finishing the job and closing the ticket

**Comment by artur-beljajev** [comment]
The change is present in staging branch, and I see no reason introducing new feature branch for for 1 file change that does _not_ depend on anything, besides Travis, which is totally external to us.

Please either check it briefly, say, that you see build info in Travis and close it, or please be so kind, explain, what is the _reason_ why you want to extract it to separate branch.

**Comment by artur-beljajev** [comment]
Notifications are sent to developers@tld.ee

**Comment by vohmar** [comment]
@artur-beljajev I don't see any updates to deployment guide (install and config instructions)

**Comment by artur-beljajev** [comment]
What we need to include in this guide?

**Comment by vohmar** [comment]
for example that it is necessary to set correct email address for notifications

**Comment by artur-beljajev** [comment]
Notification email is removed from Travis config. By default it gets sent to committer.

@teadur FYI developers@tld.ee is not used by Travis anymore.

**Comment by vohmar** [comment]
@artur-beljajev please update this: https://github.com/internetee/registry/blob/master/doc/testing.md
add references to Travis as the default CI solutions and point to the applications setup guide if nothing is needed to do just to make it work with the deployment from master.

**Comment by artur-beljajev** [comment]
I don't think it should be under test guide. Travis is CI solution, and new registry may or may not use it.
Can you please also explain, who this guide is aimed for? If it is for technical stuff, they probably know that is Travis and it's enough just to mentioned that we support it out of the box.

**Comment by artur-beljajev** [comment]
I am also thinking of removing branch spec from config at all. It should be specified per Travis instance config, not in repo config, imho.

**Comment by vohmar** [comment]
@artur-beljajev  please update changelog on changes related to this ticket

**Comment by artur-beljajev** [comment]
Done

**Comment by artur-beljajev** [comment]
Merged to staging

**Comment by teadur** [comment]
@artur-beljajev are there any other methods for me to get the travis buildreports automatically ? 
I would prefer to receive them.

**Comment by artur-beljajev** [comment]
According to https://docs.travis-ci.com/user/notifications I don't see any way of neither having dedicated config file for each registry nor configure it in Travis UI.

**Comment by vohmar** [comment]
@artur-beljajev There is a documented way to configure what @teadur asked - 

```
Email notifications #

Specify recipients that will be notified about build results:

notifications:
  email:
    - one@example.com
    - other@example.com
```
Please add reference to the documentation oh how to set this in deployment file.

**Comment by artur-beljajev** [comment]
We had this solution initially, but then removed it since we cannot just hard-code those emails. We also can't git ignore this file, since Travis expects it to exist.

P.S. Actually, there are defaults which will be used in case of absence of travis.yml, but this file has some project-dependent config.

**Comment by vohmar** [comment]
@artur-beljajev document this option in our installation/deployment guide so if someone will deploy the system they will know that if they want travis notifications on some specific email they will have to configure it in yaml file before deploying it.

**Comment by artur-beljajev** [comment]
This file is tracked by Git. If another registry makes changes in this file, it is out of luck.

**Comment by vohmar** [comment]
@artur-beljajev branch https://github.com/internetee/registry/tree/registry-203 has merge conflicts with master. Please resolve the issues.

**Comment by artur-beljajev** [comment]
Done

**Comment by vohmar** [comment]
closed, branch deleted
