### ISSUE TITLE
Check mailers

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#204]
The following mailers seem to be broken:
- pending_update_rejected_notification_for_new_registrant
- pending_update_expired_notification_for_new_registrant
- pending_update_notification_for_new_registrant

`DomainMailer.pending_update_rejected_notification_for_new_registrant(Domain.find(86902)).deliver!`

> ArgumentError: An SMTP To address is required to send a message
#200

**Comment by artur-beljajev** [comment]
@vohmar At least above mentioned mailers are broken, but I would check all of them

**Comment by vohmar** [comment]
@artur-beljajev no they are not broken, tested these on staging and got the email notices as expected: http://staging.infra.tld.ee:447/

**Comment by artur-beljajev** [comment]
It was probably fixed, I cannot reproduce it anymore.
