### ISSUE TITLE
Registrar: domain update ends with internal error

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#2041]
master branch
replicated on staging and test

looks like any kind of domain update results with internal error:

logs:
```
Jun 17 15:53:55 staging st-rar.infra.tld.ee[32016]: Completed 500 Internal Server Error in 364ms (ActiveRecord: 4.0ms | Allocations: 7242)
Jun 17 15:53:55 staging st-rar.infra.tld.ee[32016]: NoMethodError (undefined method `each' for nil:NilClass):#012  #012app/models/depp/domain.rb:93:in `update'#012app/controllers/registrar/domains_controller.rb:114:in `update'
```

errbit:
https://errbit.internet.ee/apps/5bcf4909d9d1af60e9179208/problems/60cb3fb5d9d1af0c46776942
undefined method `each' for nil:NilClass

tested with empty update and with an attempt to add new ns nameserver record.

**Comment by yulgolem** [comment]
![image](https://user-images.githubusercontent.com/7688888/122410450-5eaad080-cf9d-11eb-8c97-45875ae14955.png)
@OlegPhenomenon  looks like epp_xml gem issue.
