### ISSUE TITLE
Configure airbrake & errbit

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#207]
- https://github.com/errbit/errbit
- https://github.com/airbrake/airbrake
- Remove newrelic

**Comment by vohmar** [comment]
We have newrelic allready set up, but probably not configured right, so we do not get much value from it at the moment. We should try to configure it properly and if then we find that some other solution like airbrake would suit our needs better, then switch.

**Comment by artur-beljajev** [comment]
So, @teadur @vohmar , I guess we agreed to install it? I would then prepare everything app-related.

**Comment by artur-beljajev** [comment]
@vohmar btw, it can also be used for production. I messed it up with another gem, which cannot.

**Comment by vohmar** [comment]
@artur-beljajev please also update install/configuration documentation on how, what and where needs to be set for this to work properly. Is everything necessary added to deploy scripts?

**Comment by artur-beljajev** [comment]
It it for development, I don't think there is anything we could document.

**Comment by vohmar** [comment]
staging/dev deployment is part of the deployment guide and scripts we offer. If we see value in these tools there is no reason not to add these to the default stack for anyone interested in developing this system further or cutomise it for own use. It is worth the effort.

**Comment by artur-beljajev** [comment]
Georg, please review

**Comment by teadur** [comment]
@artur-beljajev whats the question ? 
We we include airbrake gem i think we should have example initilizers / reference in documentation for it

**Comment by artur-beljajev** [comment]
airbrake gem is added only to staging env. Other registries may or may not use staging env, and I think we should not force them to do it. It doesn't make sense to include it to all envs, since we only use it on staging.

All info related to airbrake and errbit gems is available at above mentioned links, I also see no reason duplicating this knowledge by copy-pasting. Git has a record when those gems have been added. business people don't care about this. Developers should and probably will be studying git log, rather than reading long manuals, which require additional effort and tend to get outdated soon anyway.

IMHO, we should create new ticket about documentation and discuss it in detail there.

**Comment by vohmar** [comment]
documentation directly related to changes in this ticket do not require separate ticket and is part of standard solution.

**Comment by artur-beljajev** [comment]
Can you shared your thoughts what we should put there?

**Comment by teadur** [comment]
@artur-beljajev  Why i think we should have initilizer example there is that if i remember correctly the application fails to start if there is no initilizer defined.

**Comment by vohmar** [comment]
@artur-beljajev please provide url to the branch and to the doc with initializer example

**Comment by artur-beljajev** [comment]
There is no feature branch for this. It is already in master.

**Comment by vohmar** [comment]
@artur-beljajev please consult with @teadur

**Comment by artur-beljajev** [comment]
@teadur Where it is best to put that info?

**Comment by teadur** [comment]
@artur-beljajev i think we should have example  file in the correct directory with example prefix/suffix

**Comment by artur-beljajev** [comment]
Can you clarify, where is the correct directory and what prefix/suffix do you mean?

**Comment by teadur** [comment]
config/initializers/errbit-example.rb if it isnt loaded automaticaly.
Are only .rb files loaded from initializers directory ?

**Comment by artur-beljajev** [comment]
All .rb. files from that folder get load automatically at Rails startup. I think it isn't good idea to add sample files for every gem we have. Perhaps we should find some another way of providing initial config than rather than sample files. I am a bit worried that the app will be polluted with all that samples one day if we continue adding them.

**Comment by teadur** [comment]
as of not loading the initlizer doesnot brake the app in anyway we could go the route of not adding example of the configuration of airbrake/errbit, anyone who is interested in using it will get the information from aibrakes website. closing the issue.
