### ISSUE TITLE
Regenerate REPP docs

### ISSUE THREAD

**Issue by yulgolem** [internetee/registry#2099]
There is a bug in REPP docs, mark notification as read requires not a GET, but PUT request and vise versa.
https://internetee.github.io/repp-apidoc/#mark-poll-message-as-read

We need to fix/regenerate docs

**Comment by DinSmol** [comment]
fixed
https://github.com/internetee/repp-apidoc/commit/125ac0d0fb06f0d0848e83e226dd58903db1b159

**Comment by vohmar** [comment]
Looks good, can we close this @yulgolem
