### ISSUE TITLE
Investigate migration error

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#210]
artur@registry:~/registry$ bundle exec rake db:migrate
== 20161004101419 AdduuidIndexToEppLogs: migrating ============================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "uuid" does not exist
: CREATE INDEX CONCURRENTLY epp_logs_uuid  ON epp_logs  USING btree (uuid);/media/sf_registry/db/migrate/20161004101419_adduuid_index_to_epp_logs.rb:3:in `change'
/home/artur/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/home/artur/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "uuid" does not exist
: CREATE INDEX CONCURRENTLY epp_logs_uuid  ON epp_logs  USING btree (uuid);
/media/sf_registry/db/migrate/20161004101419_adduuid_index_to_epp_logs.rb:3:in `change'
/home/artur/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/home/artur/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
PG::UndefinedColumn: ERROR:  column "uuid" does not exist
/media/sf_registry/db/migrate/20161004101419_adduuid_index_to_epp_logs.rb:3:in `change'
/home/artur/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/home/artur/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by vohmar** [comment]
@artur-beljajev is there anything to be tested here?

**Comment by artur-beljajev** [comment]
Nope.
