### ISSUE TITLE
Install errbit on staging

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#211]
https://github.com/errbit/errbit

Please get back to me once it is installed. I will update config with the host of errbit (https://github.com/internetee/registry/blob/registry-207/config/initializers/errbit.rb) and merge it with staging so we can test it.
#207

**Comment by artur-beljajev** [comment]
@teadur Is it already configured?

**Comment by teadur** [comment]
@artur-beljajev yep

**Comment by artur-beljajev** [comment]
@teadur Please update ticket's status.

**Comment by teadur** [comment]
@artur-beljajev 
epp is ignoring errbit configuration, most likely the culprit is here:
https://github.com/internetee/registry/blob/master/app/controllers/epp_controller.rb#L67
Could you please change it so the error would go to errbit if errbit is configured.
