### ISSUE TITLE
EPP: domain:delete - automated email is not sent on delete confirmation

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#212]
The automatic email notifying the registrant about confirmed domain deletion is not sent

https://github.com/internetee/registry/blob/master/app/views/mailers/domain_mailer/delete_confirmation.text.erb

message is sent when the request is declined.

**Comment by artur-beljajev** [comment]
Tried with the following statement

`Epp::Domain.last.apply_pending_delete!`

But was unable to reproduce (http://prntscr.com/d9esmg)

**Comment by vohmar** [comment]
does not work on staging in actual in real world use case with domain delete epp request and user confirmation.

**Comment by vohmar** [comment]
tested on staging
1. epp domain:delete request, declined by registrant using link sent to registrants email address -> no email
2. epp domain:delete request, confirmed by registrant using link sent to registrants email address -> no email
3. epp domain:delete request, updated registrant_verification_asked_at value in db by -2 days, run the DomainCron.clean_expired_pendings cron task -> pending status removed, but no email

will put this ticket on hold for now and come back to this when 1. jan tickets are completed.

**Comment by artur-beljajev** [comment]
@vohmar 

There is a new test introduced for this in https://github.com/internetee/registry/pull/1166, which passes:

https://github.com/internetee/registry/blob/719c46c9c2d3772eadd0a943088cef690710ba12/test/integration/registrant_area/domain_delete_confirmations.rb#L11

**Comment by vohmar** [comment]
problem has been resolved.
