### ISSUE TITLE
Configure staging env to use local config

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#219]
@teadur Here is the latest config for staging (config/environments/staging.rb)
https://gist.github.com/artur-beljajev/236a4c8c07a6575832b30fcf1a23a3b7

I removed in this branch: https://github.com/internetee/registry/commits/remove-staging-config.

Please reassign this ticket to me once you're done with config.

**Comment by vohmar** [comment]
@artur-beljajev please also make sure that install/config doc has everything necessary so anyone deploying the system will know that they have to configure staging environment in the staging.rb conf file.

**Comment by artur-beljajev** [comment]
staging.rb has been removed from repo in favor of part of Mina deploy. No additional config is needed.

**Comment by vohmar** [comment]
changes merged to master
