### ISSUE TITLE
EPP: ForceDelete prohibits domain updates

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#220]
ForceDelete prevents any updates to a domain object.

ForceDelete is not a status on its own - it's a group label for list of statuses:
- serverRenewProhibited 
- serverTransferProhibited  
- serverUpdateProhibited  
- pendingDelete 
- serverManualInzone

So by default any updates are prohibited. To enable updates admin has to remove serverUpdateProhibited. Removing this results in new error on domain update

`Object status prohibits operation - pendingDelete [code: 2304]`

pending delete cannot prevent any other requests except domain:delete. Removing this results

`Object status prohibits operation [code: 2304]`

To update domain data one has to remove serverForceDelete.

**Comment by artur-beljajev** [comment]
Please prioritize

**Comment by vohmar** [comment]
todo list prioritised

**Comment by artur-beljajev** [comment]
@vohmar Is it still valid?

**Comment by vohmar** [comment]
we will implement new ForceDelete process this year, we will not do any forcedeletes before this is done so let's postpone dealing with this issue until then

**Comment by vohmar** [comment]
Fixed with new force delete procedure
