### ISSUE TITLE
Nameserver record validation

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#2202]
We are scanning the registry daily for cdnskey record changes (csync). This enables us to also detect invalid ns records in the registry.

we should register nameserver records that
* do not respond
* have no record about the domain it's queried about (is registered to server in the TLD registry)

when such a ns record is detected we should wait for at least 2 additional confirmations by the next scans (identically to csync scans). If three consecutive scans detect the same issue we should flag the record as invalid and notify tech contact via email and registrar via poll message about the issue.

If the issue is still there after a month - notify again

**Comment by ratM1n** [comment]
i was able to create domain with DNS servers which don't have this domain's zone and then add a new nameserver to this domain with non-existing name and without glue IP
