### ISSUE TITLE
Missing error message on contact update with invalid phone nr format

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#2239]
Error message is missing for invalid phone nr format on create and update of a contact object

  <response>
    <result code="2400">
      <msg lang="en"/>

sample request:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd">
  <command>
    <update>
      <contact:update xmlns:contact="https://epp.tld.ee/schema/contact-ee-1.1.xsd">
        <contact:id>BEST:219D698B</contact:id>
        <contact:chg>
          <contact:voice>7035555555</contact:voice>
        </contact:chg>
      </contact:update>
    </update>
    <clTRID>Märi Änn PR-1639401142</clTRID>
  </command>
</epp>

response:
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="lib/schemas/epp-ee-1.0.xsd">
  <response>
    <result code="2400">
      <msg lang="en"/>
    </result>
    <trID>
      <clTRID>Märi Änn PR-1639401142</clTRID>
      <svTRID>ccReg-1841309603</svTRID>
    </trID>
  </response>
</epp>

on contact create the response is:
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="lib/schemas/epp-ee-1.0.xsd">
  <response>
    <result code="2005">
      <msg lang="en">Phone nr is invalid [phone]</msg>
    </result>
    <trID>
      <clTRID>Märi Änn PR-1639402038</clTRID>
      <svTRID>ccReg-3580842031</svTRID>
    </trID>
  </response>
</epp>

**Comment by maricavor** [comment]
Reopened due to modifications for phone number validations
