### ISSUE TITLE
Missing error message after updating contact with disclosed attributes

### ISSUE THREAD

**Issue by maricavor** [internetee/registry#2272]
When updating contact with disclosed attributes no error message is shown and syntax error in the log:

<img width="928" alt="Screenshot 2022-01-13 at 20 08 38" src="https://user-images.githubusercontent.com/4614131/149512334-5c7a45c5-0897-4895-9acb-ab0b11ef3b0d.png">
<img width="596" alt="Screenshot 2022-01-14 at 10 48 18 (2)" src="https://user-images.githubusercontent.com/4614131/149512339-ee56e664-ea6d-4816-9727-ac948a2d41c6.png">

**Comment by vohmar** [comment]
now any attempt to update contact with additional disclosed attributes results in this kind of response:

```
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="lib/schemas/epp-ee-1.0.xsd">
  <response>
    <result code="2005">
      <msg lang="en">Contact contains unsupported attribute(s) [disclosed_attributes]</msg>
    </result>
    <trID>
      <clTRID>Märi Änn ED-1649329505</clTRID>
      <svTRID>ccReg-7424268799</svTRID>
    </trID>
  </response>
</epp>
```

is this expected? i presume the issue was there before and this issue just resolved the blank error message problem?

**Comment by maricavor** [comment]
No need to validate contact on disclosed attributes when updating
