### ISSUE TITLE
WHOIS: filter bad input before query gets to db

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#229]
WHOIS server cannot handle invalid input correctly

`/home/whois/whois/releases/12/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in`exec_prepared': PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xf6 0xf6 0x72 0x69 (ActiveRecord::StatementInvalid)`

server should validate the input so only correclty formated and valid queries reach the db

**Comment by artur-beljajev** [comment]
please provide steps to reproduce.

**Comment by teadur** [comment]
@artur-beljajev 
The poblem is that the input isnt checked to be valid UTF-8 string, the application should either force the encoding to be valid utf-8 or respond to user with encoding error rather then pass the data to db.
I think the second option would be better.

**Comment by artur-beljajev** [comment]
What input? Where? How can I reproduce the problem?

**Comment by teadur** [comment]
@artur-beljajev input sent to unix whois demon (whois query), you can reproduce the error by sending invalid utf-8 strings to whois demon

**Comment by artur-beljajev** [comment]
I am able to reproduce an exception "invalid byte sequence for encoding UTF8", but it comes from logger instead of postgresql_adapter.rb:602.

I kindly ask you to provide exact steps and input to reproduce the problem. Here is good guide to do it: http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by vohmar** [comment]
@artur-beljajev the problem at hand is more general - we need to apply input validation and introduce better exception handling to unix whois server.

**Comment by artur-beljajev** [comment]
So it is not actually a bug? Can you elaborate, how and what exactly should we validate?

**Comment by teadur** [comment]
@artur-beljajev 
Please handle exception PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8":
And send the response to user that the query was in incorrect encoding.

**Comment by artur-beljajev** [comment]
Should we enforce some particular encoding, say utf-8?

**Comment by artur-beljajev** [comment]
Expected behaviour: 
Send the response to user that the query was in not utf8 encoding.

**Comment by artur-beljajev** [comment]
@teadur please test it

**Comment by vohmar** [comment]
@teadur 
https://github.com/internetee/whois/tree/registry-229
merge conflicts with staging, not merged to master

**Comment by teadur** [comment]
@vohmar @artur-beljajev merged to master and deployed.

**Comment by vohmar** [comment]
@teadur I cannot see commits of this ticket in master branch. Please reference the merge commit.

**Comment by vohmar** [comment]
closed, branch deleted
