### ISSUE TITLE
Remove monkey-patching

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#231]
config/initializers/eis_custom_active_model.rb
config/initializers/eis_custom_active_record.rb
config/initializers/eis_custom_flash.rb

**Comment by artur-beljajev** [comment]
@ratM1n @teadur What is point of config/initializers/eis_custom_flash.rb?

**Comment by teadur** [comment]
@artur-beljajev http://api.rubyonrails.org/classes/ActionDispatch/Flash.html

**Comment by artur-beljajev** [comment]
What is the reason of monkey-patching the class we don't own?

**Comment by teadur** [comment]
It logs all the flash messages to syslog/standard logger

**Comment by artur-beljajev** [comment]
I was actually wondering _why_ is that code resides there. If nobody knows the reason why it's there, I about to remove first 3. The latter requires code base change.

**Comment by teadur** [comment]
They all give some extra logging, i wouldnt remove them just yet.
I think it would make sense to look at logs first and see what value they give to us.
Havent looked at active model/record yet, but flash could be beneficial at some cases.

**Comment by artur-beljajev** [comment]
First of all, I am trying to say that monkey patching is dangerous. There should be unbeatable argument to do it. 
Secondly, I don't understand _why_ do you want to log flash messages? These are the messages that are persisted in session until next request to show them to the user. Please explain me.

**Comment by artur-beljajev** [comment]
Example of real WTF http://prntscr.com/f1foaz

**Comment by artur-beljajev** [comment]
Should not affect any production code.

**Comment by vohmar** [comment]
@teadur Is this good by you?

**Comment by teadur** [comment]
How is http://prntscr.com/f1foaz related to issue ?

**Comment by artur-beljajev** [comment]
It is unnecessary. `contact.errors.full_messages` returns what you want.

**Comment by teadur** [comment]
I think its far easier to use valid? then this long reference to get the error, what is the actual problem with it, does it brake anything ?

**Comment by artur-beljajev** [comment]
Why do you need that error at all?

**Comment by teadur** [comment]
Its really convient when you want to know why some objects validation failed, sadly you cant check object state from any UI you need to use the actual rails console for it.

**Comment by artur-beljajev** [comment]
This ticket cannot be closed until `config/initializers/eis_custom_active_record.rb` is removed. 

@teadur 
 9293d0996a1bd333e6b8dbef9b85648cbdba7c00 If you mean model errors, then it is only possible in admin (since other areas use EPP) so there no model objects available.

https://github.com/internetee/registry/issues/231#issuecomment-297696812 remains valid. It creates unnecessary noise with no benefit.

**Comment by artur-beljajev** [comment]
@vohmar Any reason why this issue has been closed? 

The code is still there https://github.com/internetee/registry/blob/4786dbb943ecab33190932a48d8969553eb55542/config/initializers/eis_custom_active_record.rb#L5

**Comment by artur-beljajev** [comment]
I might also set `config.log_level` to some higher level to hide all that noise, but I think it opens a possibility that I miss something I need.

**Comment by artur-beljajev** [comment]
The information in question may be obtained using `active_model_object.errors.full_messages`

**Comment by artur-beljajev** [comment]
That monkey-patch can lead to problems with Rails update in the future.

**Comment by vohmar** [comment]
I must have misunderstood that work with config/initializers/eis_custom_active_model.rb, eis_custom_active_record.rb and eis_custom_flash.rb is done.

**Comment by artur-beljajev** [comment]
`eis_custom_active_model.rb` and `eis_custom_flash.rb` have been removed, that's perfect!
`eis_custom_active_record.rb` is the only thing in question.

How is that logging in the latter is useful for us?

**Comment by teadur** [comment]
It's useful when you look at logs, if you think its so big problem and brakes everything remove it.

**Comment by vohmar** [comment]
in production
