### ISSUE TITLE
Admin: setting hard force delete to a domain results in internal error

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#2345]
could be related to sending an email to registrant as when unchecking the notify FD is set as expected

<img width="476" alt="image" src="https://user-images.githubusercontent.com/7734747/162743972-737200e1-c6a2-43e6-aec2-1271b9ccde34.png">

with notifications checked the process fails with internal error.

Produced on staging

**Comment by thiagoyoussef** [comment]
Closing this issue because It seems that this bug it's not happening! I could schedule hard force delete on staging with no error
