### ISSUE TITLE
timezone issues on domain expiry: expire, outzone and delete not saved in utc

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#235]
domain expiration process has bugs on saving timestamps in db in correct timezone, using these values correctly according to timezone of the server/application and calculating the values of valid to, outzone and delete dates.

**valid to calculated and saved in local timezone instead of utc**
```
valid_from: "2016-10-21 11:08:18.872509"
valid_to: "2017-10-22 00:00:00"
```

**outzone_at and delete_at dates are saved in db in local timezone instead of utc:**
```
valid_to: "2016-11-03 22:00:00"
outzone_at: "2016-11-18 00:00:00"
delete_at: "2016-12-18 00:00:00"
```
due to this registrant looses 22hrs of expire warning period

logic:
* all timestamps in db must be in UTC timezone
* application must convert this to the timezone of the application/server (incl cron and Que jobs)
* expire date (valid to) of a domain is set to the **beginning of next day** of registration according local time (ie. reg date 2016-11-04 13:15:00.000+02.00 = exp date 2016-11-05 00:00:00.00+02.00 (in db 2016-11-04 22:00:00.00+00.00)
* outzone_at and delete_at are calculated on domain expiry
  * outzone at = valid to + expire warning period
  * delete at = valid to + expire warning period + redemption grace period
* domain is set as expired when timpestamp now > valid to
* domain is set on hold (removed from zone) when timestamp now > outzone at
* domain is set as delete candidate and random delete time is calculated when timestamp now > delete at
* domain is deleted if domain has delete candidate status set

**Test case 1:**
* domain registered @ 2016-11-04 13:15 (GMT +2)
* create/registration date saved in db 2016-11-04 11:15:00+00.00
* expiration date saved in db 2017-11-04 22:00:00+00.00 - registration for 1 year
* outzone date saved in db on domain expiry 2017-11-19 22:00:00+00.00
* delete date save in db on domain expiry 2017-12-19 22.00.00+00.00
* domain deleted at random time between 2017-12-19 22.00.00+00.00 and 2017-12-20 21:59:59+00.00

**Test case 2:**
* domain registere @ 2016-11-05 01:34 (GMT +2)
* registration date saved in db 2016-11-04 22:34:00+00.00
* expiration date saved in db 2017-11-05 22:00:00+00.00 - registration for 1 year
* outzone date saved in db on domain expiry 2017-11-20 22:00:00+00.00
* delete date save in db on domain expiry 2017-12-20 22.00.00+00.00
* domain deleted at random time between 2017-12-20 22.00.00+00.00 and 2017-12-21 21:59:59+00.00

**Comment by artur-beljajev** [comment]
Timo: "valid to, outzone at and delete at values saved to db in app server tz instead of utc"

**Comment by artur-beljajev** [comment]
@teadur What is the value of "time_zone" setting on prod?

**Comment by artur-beljajev** [comment]
@vohmar How do you know that "valid to, outzone at and delete at values saved to db in app server tz instead of utc"?

**Comment by artur-beljajev** [comment]
Tried to reproduce the problem with dates:
bin/rails c

`Time.zone.now` # Sun, 06 Nov 2016 15:34:23 EET +02:00
`domain = Domain.new(period: 1, period_unit: 'y').save(validate: false)` # true

`Domain.last.registered_at_before_type_cast` # 2016-11-06 13:34:58.321141
`Domain.last.registered_at`  # Sun, 06 Nov 2016 15:34:58 EET +02:00

`Domain.last.valid_from_before_type_cast` # 2016-11-06 13:34:58.321295
`Domain.last.valid_from` # Sun, 06 Nov 2016 15:34:58 EET +02:00

`Domain.last.valid_to_before_type_cast` # 2017-11-07 00:00:00
`Domain.last.valid_to` # Tue, 07 Nov 2017 02:00:00 EET +02:00

Legend:
"*_before_type_cast" method returns the value as it is in DB

**Comment by artur-beljajev** [comment]
it seems the problem is that we just operate UTC in app, instead of operating with app time zone.

**Comment by artur-beljajev** [comment]
@vohmar Which attribute is meant by "registration date": registered_at or valid_from?

**Comment by vohmar** [comment]
@artur-beljajev registered_at and valid_from values should be identical - these are duplicate columns with now special meaning for .ee as we do not allow domain reservations.

yes the concept of tz being in utc in db means that the beginnig of day and end of day values that should be in app tz are saved as such in db. So if you look at the examples in the ticket description valid_to value in the first one should be 

```
valid_from: "2016-10-21 11:08:18.872509"
valid_to: "2017-10-21 21:00:00"
```

and in second example

```
valid_to: "2016-11-03 22:00:00"
outzone_at: "2016-11-18 22:00:00"
delete_at: "2016-12-18 22:00:00"
```

**Comment by artur-beljajev** [comment]
Anything is missing?

**Comment by vohmar** [comment]
@artur-beljajev please add a comment to changelog at 7th of Nov

**Comment by artur-beljajev** [comment]
Done!

**Comment by vohmar** [comment]
* Merge conflict with staging changelog file. Please help to resolve this.
* what does this mean: "Consider domains having current time at expire_time attribute expired" - is it a copy paste typo or does the admin really have to consider something on deploy or system setup?  As currently the system sets the expire_time to the beginning of the next day in the server timezone. So I feel that this sentence in changelog requires rephrasing

**Comment by artur-beljajev** [comment]
Changelog is updated and branch merged into staging

**Comment by vohmar** [comment]
merge conflict also with master:
https://github.com/internetee/registry/pull/261

**Comment by artur-beljajev** [comment]
Merged with master

**Comment by vohmar** [comment]
please fix the merge conflicts once again:
https://github.com/internetee/registry/pull/281

sorry for the mess!

**Comment by artur-beljajev** [comment]
Merged into master and staging

**Comment by vohmar** [comment]
in production, closed, branch deleted
