### ISSUE TITLE
Delay renovate automated ruby version updates

### ISSUE THREAD

**Issue by thiagoyoussef** [internetee/registry#2361]
Change the renovate config file to delay ruby version for 30 days on these projects:

- [x] registry
- [x] rest-whois
- [x] accreditation_center
- [x] eid_manager
- [x] auction_center
- [x] whois
- [x] registrar_center

**Comment by thiagoyoussef** [comment]
Rest whois: https://github.com/internetee/rest-whois/pull/346

**Comment by thiagoyoussef** [comment]
accreditation_center: https://github.com/internetee/accreditation_center/pull/176

**Comment by thiagoyoussef** [comment]
eid_manager: https://github.com/internetee/eid_manager/pull/160

**Comment by thiagoyoussef** [comment]
auction_center: https://github.com/internetee/auction_center/pull/899

**Comment by thiagoyoussef** [comment]
whois: https://github.com/internetee/whois/pull/126

**Comment by thiagoyoussef** [comment]
registrar_center: https://github.com/internetee/registrar_center/pull/59

**Comment by vohmar** [comment]
all tasks done and merged
