### ISSUE TITLE
REPP: Update repp urls in doc

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#2389]
https://internetee.github.io/repp-apidoc/#introduction
environments data in doc is incorrect

correct urls:
test: https://testrepp.internet.ee/
prod: https://repp.internet.ee/

**Comment by vohmar** [comment]
your commit reverted this dinars change: https://github.com/internetee/repp-apidoc/commit/54abc9f210fffd8cd580e9c4964a0666323b0250

that change existed only in gh-pages branch but was missing from the main. So i presume you based your fix in the main and by merging it into gh-pages this happened. Can you please restore the Dinars fixes and maybe merge this in main as well to have those two in sync

**Comment by thiagoyoussef** [comment]
Done I restored Dinars fixes :)

**Comment by vohmar** [comment]
great stuff, thank you!
