### ISSUE TITLE
Calling "reload!" leads to LoadError exception in staging env

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#239]
`bin/rails c staging`
`reload!`

Reloading...
LoadError: Unable to autoload constant Repp::API, expected app/api/repp/api.rb to define it

**Comment by teadur** [comment]
Closed by https://github.com/internetee/registry/commit/39976405c3562940efb3095da23c950941330b10
Because changes staging env to inherit from production and production has config.cache_classes = true what disables reloading.
