### ISSUE TITLE
Mobile-id login leads to exception at registrar/registrant portals

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#240]
Nov  9 10:51:06 reg-l-rar REGISTRAR[4016]: [registrar] [855b0a24-4bf6-4fa6-b14b-a58327d7165f] [195.43.86.5] #012NoMethodError (undefined method `level=' for Syslog::Logger:Class):#012  app/controllers/registrar/sessions_controller.rb:112:in `mid'#012  config/initializers/eis_custom_flash.rb:9:in `call'

**Comment by teadur** [comment]
For some reason the new caption isnt shown on login page, the login buttons caption is "Login Btn"

**Comment by artur-beljajev** [comment]
Fixed

**Comment by vohmar** [comment]
@artur-beljajev which ticket and branch is this fix related to? What broke the m-id login in the first place?
PS: staging is tested and m-id works on registrar and registrant as expected.

**Comment by artur-beljajev** [comment]
This bug once we switched digidoc log to syslog with this commit 3e477b2fb28786b826a4a2bd31f0d9c672bae616.

**Comment by vohmar** [comment]
in production, branch deleted
