### ISSUE TITLE
Registrar: domain list download functionality is missing

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#248]
Domain listi view in the portal for registrars is missing list download functionality.
/registrar/domains

Two options required for domain list download - csv and pdf

CSV - comma separated values
1st row column names, 4 columns: Domain name, registrant, registrant id, valid to

The function is still there in contact list view to use as a reference
/registrar/contacts

The functionality allows registrar to download the list of contacts or domains in the csv or pdf format. The functionality takes into account the filters applied to the list (except pagination).

**Comment by artur-beljajev** [comment]
Additional info is needed (see Skype)

**Comment by vohmar** [comment]
CSV - comma separated values
1st row column names, 4 columns: Domain name, registrant, registrant id, valid to

initial description updated accordingly

**Comment by artur-beljajev** [comment]
@vohmar  what format of valid_to is needed?

**Comment by vohmar** [comment]
@artur-beljajev value must be in the application timezone and only date part is necessary

**Comment by artur-beljajev** [comment]
@vohmar What format?

**Comment by vohmar** [comment]
@artur-beljajev YYYY-MM-DD

**Comment by artur-beljajev** [comment]
It is currently in default format. We could change it later globally, I guess.

**Comment by artur-beljajev** [comment]
Only CSV version has been implemented

**Comment by vohmar** [comment]
unable to merge to staging - merge conflict in rails_helper
https://github.com/internetee/registry/pull/291

**Comment by vohmar** [comment]
there is a db object/record in registrant id column, but should be EPP object id ie code.

**Comment by artur-beljajev** [comment]
Done

**Comment by vohmar** [comment]
autotests fail: 
https://github.com/internetee/registry/pull/334
https://travis-ci.org/internetee/registry/builds/189480002

**Comment by vohmar** [comment]
@artur-beljajev can you replace the "export csv" button with "download" as it is in contact view (registrar/contacts) to keep unified design and logic.

**Comment by artur-beljajev** [comment]
Done

**Comment by vohmar** [comment]
in production, branch deleted
