### ISSUE TITLE
stop saving postal addresses (<contact:addr>)

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#251]
Starting on 1st of January 2017 EIS will stop collecting postal addresses for contact objects in .ee zone. The postal addr data will not be deleted on 1st of January - the system must igonre the data in the db.

the contact:addr part of epp contact schema postalInfoType for create element will be optional (minOccurs="0"). Create nor Update commands must not fail just because registrar adds postal address info in the epp request

If registrar send a contact create query with postal address data query is accepted and result code 1100 is returned with message "Command completed successfully; Postal address data discarded"

same goes for contact update - if contact:addr exists in contact:chg part of contact update request this data is discarded by the system the rest of the query is validated and result code 1100 is returned in case of no errors

contact info request should not return addr element in postalInfoType regardless if there is data saved in DB or not

in case of contact and domain transfers postal address data must be discarded

~~postal addr data rows must be removed from WHOIS results. Data must be deleted from whois db (structure will remain the same)~~

REPP must not return postal address data.

The functionality should be configurable in admin - checkbox for making registry not to save and return postal address data. The default setting is to collect postal address data.

Schemas that need update are (registry/lib/schemas/):
* contact-eis-1.0.xsd > contact-ee-1.1.xsd (optional contact:addr)
* epp-1.0.xsd > epp-ee-1.0.xsd (new result code 1100)
* all-ee.xsd > all-ee-1.1.xsd (references to new versions of contact and epp schemas)

The example requests for contact:create and contact:update in epp-client and xml-console of the portal for registrars must also be updated with the new versions of xml schemas. (The contact:addr element will remain in the examples to support the check box functionality of admin interface - will come back to template switching in the future).

~~hide address block in contact create and update views of the portal for Registrars
/registrar/contacts/new
/registrar/contacts/_CONTACT:ID_~~

**Comment by artur-beljajev** [comment]
@vohmar Can you confirm that the portal address consists of the following fields:
# city
# street
# zip
# country_code
# state

**Comment by vohmar** [comment]
@artur-beljajev as specified in the issue heading and respecified in the description by postal address I mean <contact:addr> element the subelement of <contact:postalInfo> in EPP schema. Please familiraise yourself with the details: https://tools.ietf.org/html/rfc5733. 

You can check the subelements of <contact:addr> element in the rfc or EPP contact schema. These are
* <contact:street>
* <contact:city>
* <contact:sp>
* <contact:pc>
* <contact:cc>

**Comment by artur-beljajev** [comment]
I meant DB fields.

**Comment by vohmar** [comment]
yes these are the db fields

**Comment by artur-beljajev** [comment]
What is meant by "WHOIS results"? http://prntscr.com/dfdhfk Did I just miss the address here?

**Comment by vohmar** [comment]
@artur-beljajev you are correct, we do not publish postal address info of contacts in whois an thus this requirement is invalid. I removed it from the description.

**Comment by vohmar** [comment]
updated the description of the ticket with a requirement:
"The example requests for contact:create and contact:update in epp-client and xml-console of the portal for registrars must also be updated with the new versions of xml schemas."

**Comment by vohmar** [comment]
updated the description with references to necessary schema updates:
"Schemas that need update"

**Comment by vohmar** [comment]
added requirement to remove address blocks from contact update and create views of the portal for registrars

**Comment by artur-beljajev** [comment]
Timo, it's not just a matter of hiding something, but rather make it optional/required in accordance with corresponding setting. At the first sight looking at repp contacts I discovered a lot of duplication, so it is definitely time consuming and I suggest extracting it to a separate ticket.

**Comment by artur-beljajev** [comment]
The original ticket itself is basically ready but there is one problem I was unable to solve without your assistance:

config/initializers/load_schemas.rb now loads lib/schemas/all-ee-1.1.xsd (instead of old one) and when the system tries to validate all other EPP requests (the ones with xmlns:contact="https://epp.tld.ee/schema/contact-eis-1.0.xsd) against that schema (app/controllers/epp_controller.rb:20), it fails, new all-ee-1.1 does not define old contacts namespace. 

Should I migrate all other requests such as delete and check to new version or perhaps you have another solution?

**Comment by vohmar** [comment]
removed the hiding requirement from the description. will make a separate ticket for that.

yes, all the requests and replys should be updated for the newest schema versions.

**Comment by artur-beljajev** [comment]
Done

**Comment by vohmar** [comment]
merge conflicts with staging
https://github.com/internetee/registry/pull/294
```
spec/factories/api_user.rb
spec/models/admin_user_spec.rb
spec/support/requests/session_helpers.rb
```

**Comment by artur-beljajev** [comment]
Merged with no conflicts

**Comment by vohmar** [comment]
contact details view in the portal for registrars is broken (click on any contact at /registrar/contacts - "Not found" is returned; same happens when clicking on registrant name in domain list view (/registrar/domains))

**Comment by artur-beljajev** [comment]
#1 Are you sure it was introduced by this branch?

**Comment by artur-beljajev** [comment]
#2 Fails because you send old version of schema "https://epp.tld.ee/schema/contact-eis-1.0.xsd"

**Comment by vohmar** [comment]
#1 yes I am sure it is this branch; #2 and #3 are queries generated by the portal for registrars - I did not send any version of schema. views:
* /registrar/contacts/new
* /registrar/contacts/_CONTACT:CODE_/edit

**Comment by artur-beljajev** [comment]
#1, #2, #3 Fixed by #5, 6, 7
#4 Cannot reproduce. Check "address_processing" setting in admin and provide additional info if the issue remains
#5, 6, 7 Good catch, fixed. Please review this part thoroughly.

Also note related changes:
https://github.com/internetee/epp/issues/1
https://github.com/internetee/depp/issues/1
https://github.com/internetee/EPP-web-client/issues/10
https://github.com/internetee/epp-xml/issues/3

P.S. GEMFILE dependencies are currently pointed to master branch, so it will not work unless merged.

**Comment by vohmar** [comment]
* there is an error message on registrar portal's poll page (/registrar/poll)
`Element '{urn:ietf:params:xml:ns:epp-1.0}epp': No matching global declaration available for the validation root. [code: 2001]` EPP login fails (https://staging-adm.infra.tld.ee:444/admin/epp_logs/40715)

**Comment by artur-beljajev** [comment]
See my last comment

**Comment by vohmar** [comment]
The postal address is still required in the portal for registrars in the contact create and update forms (local validation)
* /registrar/contacts/new
* /registrar/contacts/_CONTACT:ID_/edit

**Comment by artur-beljajev** [comment]
"local validation" = client-side?

**Comment by artur-beljajev** [comment]
№1 Is a known issue and you have extracted it to a separate ticket https://github.com/internetee/registry/issues/290.

**Comment by vohmar** [comment]
yes, local validation means client side - portal validates form data before sendint it to epp.
#290 is about hiding postal address form fields - this is not critical at the moment. No1 issue here is that in current form the postal address data is mandatory from client side - this is critical to solve and should be done in this ticket before it could be closed. Simple solution is to remove postal address field validations from the portal for registrars and epp web client.

**Comment by artur-beljajev** [comment]
Not sure you noticed this comment https://github.com/internetee/registry/issues/251#issuecomment-266939432

**Comment by artur-beljajev** [comment]
№ 1 is fixed.

**Comment by vohmar** [comment]
the Address Processing chekcbox seems to have lost its function now. After enabling it I was still able to register a contact without postal address data

https://staging-adm.infra.tld.ee:444/admin/epp_logs/41221

**Comment by artur-beljajev** [comment]
What CRON?

**Comment by vohmar** [comment]
Setting.reload_settings!

**Comment by artur-beljajev** [comment]
Oh, good to know that such thing does exist.

**Comment by vohmar** [comment]
in production, branch deleted, closed
