### ISSUE TITLE
ForceDelete: force_delete_at saved to db in server tz instead of utc

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#253]
on setting forcedelete to a domain the force_delete_at value saved must be the utc value of the beginning of a day according to server timezone - ie 

"2016-12-18 22:00:00"

to represent 2016-12-19 00:00:00+02

but instead "2016-12-19 00:00:00" is saved.

**Comment by artur-beljajev** [comment]
@vohmar As I see, it is still valid. Can we move this up?

**Comment by artur-beljajev** [comment]
@vohmar It seems the same applies to `delete_at`. Can you check this?

**Comment by vohmar** [comment]
delete_at gets its value from valid_to value +45 days. as valid_to value is in datetime format and timed to the end of the day according Estonian timezone (ie 2019-02-04 21:00:00) then delete_at has the same format and time 45 days later. Removing time here would case the domain to be release a day too early unless all delete_at values are incremented by 1.

this tickets pullrequest is merged and in production so I will close this ticket now.
