### ISSUE TITLE
Admin: domain history filter with registrar and action selection returns "no results"

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#2552]
/admin/domain_versions

if a registrar and an action are simultaneously specified in the filter options the request tends to return "no results"

some examples:
registrar + action (auction=destroy works, but create and update return "no results")

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7734747/227940920-96ebbd68-3608-49bc-9010-d79a4c655679.png">

<img width="659" alt="image" src="https://user-images.githubusercontent.com/7734747/227940967-e644646b-d7c5-4a11-a408-a069f211dc0d.png">

**Comment by OlegPhenomenon** [comment]
@vohmar https://github.com/internetee/registry/issues/2510 duplicate?
PR: https://github.com/internetee/registry/pull/2513

**Comment by vohmar** [comment]
dupliate of https://github.com/internetee/registry/issues/2510
