### ISSUE TITLE
remove 90 days limit on Days To Renew Domain Before Expire

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#260]
Current .ee domain regulations set a limit that a domain can be renewd when there is 90 days or less left until the expiration date (valid to). From 1st of January 2017 there is no such requirement.

There is a setting in admin interface called Days To Renew Domain Before Expire, setting this to 0 enables to renew domain indefinitely.

To enforce the limits on supported registration periods we need to limit the max value of valid_to in comparison to current time so the valid_to must always be less than today + max registration period (currently 3 years) + 1 year.

validation must be added to epp domain:renew 

ie
it is now 25.11.2016
so the max valid_to value of any domain must be < 25.11.2020
datetime example: now 19.12.2016 8:36 (Tallinn TZ)
max valid_to value must be less than 19.12.2020 6:36 (UTC) - datetime values in db must be in UTC

If the validation fails the operation must fail by returning result code 
2105    "Object is not eligible for renewal; Expiration date must be less than [ max registration period + 1 year]"

Max and min periods for any zone is currently set in pricelist.

**Comment by artur-beljajev** [comment]
https://internet.ee/domeenid/2017-ee-domeenireeglite-muudatused-ja-selgitused

**Comment by vohmar** [comment]
just do not forget that 10 year registration will be available from 1st of May but the 90 days renewal limit will be removed on 1st of January. Hence the validation formula 
`valid_to < max registration period + 1 year`

**Comment by artur-beljajev** [comment]
As I understand, above mentioned admin setting can be already set to 0. What happens in such case? i.e. what is the current limitation?

**Comment by artur-beljajev** [comment]
What is the expected behaviour if validation fails?

**Comment by vohmar** [comment]
no max reigistration period length is set currently. So if you set this to 0 now, you can stack up as many renewals from 1 to 3 years as you like and push the valid to date to next century. We do allow currently only registrations and renewals for up to 3 years so setting validation as described above will atchive that allowing to renew a domain for next 3 years if less than a year is left to expiration date.

validation must be applied on every domain:renew operation and if the validation fails the operation must fail by returning result code 
2105    "Object is not eligible for renewal; Expiration date must be less than [ max registration period + 1 year]"

**Comment by artur-beljajev** [comment]
"so the valid_to must always be less than today" You meant than current time?

**Comment by artur-beljajev** [comment]
valid_to and valid_from are datetime columns/attributes

**Comment by artur-beljajev** [comment]
Do you want "[max registration period + 1 year]" to be substituted with the date? If so, can we change the error msg "less than" to "earlier than" or just "before"?

**Comment by vohmar** [comment]
today seems more appropriate here meaning only the date part.
yes this  "[max registration period + 1 year]" should be substituted with a date value. and yes we can modify the wording of the error message.

**Comment by artur-beljajev** [comment]
"so the max valid_to value of any domain must be < 25.11.2020" < 25.11.2010 23:59:59 or < 26.11.2010 00:00:00?

Please do _not_ use dates in case of "valid_to" and "valid_from" columns, since as I mentioned, they are datetime columns/attributes, and it is very confusing when you refer to just dates.

**Comment by vohmar** [comment]
you should take a look at how valid_to is filled today - it is the utc value of start of the next day in Tallinn TZ. So if today is 25.11.2016 the validation should make sure that valid_to < 26.11.2020 00.00.00 Tallinn TZ (25.11.2020 22.00.00 UTC). The datetime values in DB are in UTC , you should always compare data in the same TZ so if it were now 25.11.2016 23.20.00 Tallinn TZ you should convert this to UTC you'll get 25.11.2016 21.20.00 now add 4 years to that and you'll be on 25.11.2020 21.20.00. In the end it really does not matter if you use the whole datateime value or just the date part - if you verify that new valid_to value after a domain renew is less than  25.11.2020 or 25.11.2020 21.20.00 you will get the same result as all the domains registered on 25.11 with valid_to value as 25.11.2019 22.00 in case of 1 year renew  would get new valid_to value of 25.11.2020 22.00 which is equal to 25.11.2020 or more than 25.11.2020 21.20.00 and validations should fail on both cases.

**Comment by artur-beljajev** [comment]
I am not sure I understood your point. My question wasn't about time zone or how it is filled today. And actually it doesn't matter in this case.  Can you just confirm that the latter is correct?

**Comment by vohmar** [comment]
you should try to understand because you have to take into account how data is saved into db. Updated the description with datetime alternative of the validation.

**Comment by artur-beljajev** [comment]
Please update the description (see Skype)

**Comment by artur-beljajev** [comment]
Ready for testing

**Comment by vohmar** [comment]
tests failed: https://travis-ci.org/internetee/registry/builds/185087426
https://github.com/internetee/registry/pull/301

**Comment by vohmar** [comment]
still fails: https://travis-ci.org/internetee/registry/builds/185091877
why did you merge it with failing tests?

**Comment by vohmar** [comment]
in production, branch together with sub branch https://github.com/internetee/registry/tree/add-rspec-factories deleted, closed
