### ISSUE TITLE
Domain search form in registrar area fails in some cases

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#262]
URL: 
/registrar/domains?utf8=✓&q%5Bname_matches%5D=&q%5Bregistrant_ident_eq%5D=&q%5Bcontacts_ident_eq%5D=345345345&q%5Bnameservers_hostname_eq%5D=&statuses_contains%5B%5D=clientHold&statuses_contains%5B%5D=clientRenewProhibited&q%5Bvalid_to_gteq%5D=2016-11-01&q%5Bvalid_to_lteq%5D=2016-11-15&results_per_page=

Exception: 
ActiveRecord::StatementInvalid in Registrar::DomainsController#index
PG::AmbiguousColumn: ERROR: column reference "statuses" is ambiguous LINE 1: ...tact_id" WHERE "domains"."registrar_id" = $1 AND (statuses @... ^ : SELECT COUNT(DISTINCT count_column) FROM (SELECT "domains"."id" AS count_column FROM "domains" LEFT OUTER JOIN "domain_contacts" ON "domain_contacts"."domain_id" = "domains"."id" LEFT OUTER JOIN "contacts" ON "contacts"."id" = "domain_contacts"."contact_id" WHERE "domains"."registrar_id" = $1 AND (statuses @> '{clientHold,clientRenewProhibited}'::varchar[]) AND ("contacts"."ident" = '56785768' AND "domains"."valid_to" >= '2016-10-31 22:00:00.000000' AND "domains"."valid_to" <= '2016-11-15 21:59:59.999999') LIMIT 75 OFFSET 0) subquery_for_count

**Comment by vohmar** [comment]
received internal error when I combined 
* registrant ident and status 
* registrant ident and contact ident in a search'

errbit reports:
https://errbit.internet.ee/apps/5bcf4909d9d1af60e9179208/problems/5f9a8d06d9d1af3c3a791cf1
https://errbit.internet.ee/apps/5bcf4909d9d1af60e9179208/problems/5f9a8e76d9d1af3c3a791cf8
https://errbit.internet.ee/apps/5bcf4909d9d1af60e9179208/problems/5f9a8e87d9d1af3c3a791cfb
