### ISSUE TITLE
WHOIS: return business registry info for business registrants

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#266]
starting from 1. January 2016 EIS will display business registry code with country code for all business registrants in WHOIS and Rest WHOIS.

* WHOIS db will need three new pieces of data for registrants - ident, ident type and ident cc. 
* Ident and ident country code will be copyed to WHOIS db only if the ident type is "org". All the other registrants will have type "priv" but no ident nor ident country data.
* other types of contacts (admin, tech) will have no ident data in WHOIS db

-----
- ident
- ident_type
- ident_country_code

**Comment by artur-beljajev** [comment]
"cc" = contacts.ident_country_code?

**Comment by vohmar** [comment]
yes ident cc means ident country code (contact.ident_country_code)

**Comment by artur-beljajev** [comment]
How new info should be displayed in WHOIS output?

**Comment by artur-beljajev** [comment]
> Ident and ident country code will be copyed to WHOIS db only if the ident type is "org". All the other registrants will have type "priv" but no ident nor ident country data.

Wouldn't it be better to save all of the above mentioned attributed and decide whether to display it in results or not.

**Comment by vohmar** [comment]
Unix whois:
```
Registrant:
name:    Eesti Interneti Sihtasutus
org id:  90010019
country: EE
email:   Not Disclosed - Visit www.internet.ee for webbased WHOIS
changed: 2010-11-29 13:32:16 +02:00
```

RestWHOIS output is the same.

Private persons identity code should not be copoed to WHOIS db for security reasons. WHOIS is public db and we do not put there anything we are not willing to disclose.

**Comment by vohmar** [comment]
please hide 'org id:' and 'country:' rows from the whois output if the contact type is priv.

**Comment by artur-beljajev** [comment]
Updated

**Comment by vohmar** [comment]
in production, branch deleted, closed
