### ISSUE TITLE
EPP: support for 0 or 2 nameserver minimum for any domain

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#267]
Starting from 1. January 2017 there will be no nameserver requirement on domain registration.. Registrant can register a domain without specifying any nameservers.

* domain names with no nameservers will have status inactive as per rfc (https://tools.ietf.org/html/rfc5731#section-2.3). With no pending and prohibited statuses both OK and INACTIVE statuses are present for domains with no valid ns records.
* domain names with inactive status will not be propagated to zone file.
* to activate a domain the registrant has to add at least 2 nameserver records to the domain. If there is only 1 valid ns element present error must be returned
`2308 "Data management policy violation; Nameservers count must be between 2-11 for active domains"`
* epp domain update to add/remove nameserver records will have to verify that as a result there cannot reamin only 1 nameserver record for that domain. Error code:
`2308 "Data management policy violation; Nameservers count must be between 2-11 for active domains"`
<del> * application admin can remove any number of nameservers for any domain using admin interface (the no 1 host does not apply here).</del>
* the 1 host/nameserver check has to be added to domain validations - if there is only one host presents the domain renew must fail, also domain update must fail if as a result the remaining number of hosts is still 1. Error code
`2304 "Object status prohibits operation; Invalid count of nameserver records"`
* It is OK if there are no nameservers left after the epp domain update - domain will get inactive status in the case and will be removed from the zone

<del>in admin interface settings there is a setting "Nameserver minimum count" this will be set to 0. We have to add another setting to set the minimum count for epp for active domains "Nameserver minimum count for active domains". At the end of 31th of December we will set these settings to 0 and 2 respectively. </del>

new checkbox type setting must be added to admin interface "Nameservers optional" to enable or disable  registering domains wihtout nameservers or removing all nameserver records. The default state is 'enabled' as stated in RFC5731.
Current "Nameserver minimum count" option will remain set to 2 to state the number of nameservers required to activate a domain.

Domain.md documentation must be updated for domain create
`<domain:ns>            1`  -> `<domain:ns>            0-1`

**Comment by artur-beljajev** [comment]
> `Registrant can register a domain without specifying any nameservers.`
Does this mean absence of `<domain:ns>` element?

> `domain names with inactive status will not be propagated to zone file.`
How and where does the propagation happen?

> `epp domain update to add/remove nameserver records will have to verify that as a result there cannot reamin only 1 nameserver record for that domain.`
What is the expected behaviour if such validation fails?

> the 1 host/nameserver check has to be added to domain validations - if there is only one host presents the domain renew must fail, also domain update must fail if as a result the remaining number of hosts is still 1
What is the expected behaviour if such validation fails?

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/blob/master/doc/epp/domain.md states this: http://prntscr.com/dmy2yu, while lib/schemas/domain-eis-1.0.xsd specifies 
`<element name="ns" type="domain:nsType" minOccurs="0"/>`
Is it a misprint?

**Comment by vohmar** [comment]
* yes domain:ns can be absent
* zonefile generation is handled by cronjob: ZonefileSetting.generate_zonefiles
* if a registrar updates domain object resulting only one valid ns record the result error 
`2308    "Data management policy violation; Nameservers count must be between 2-11 for active domains"`

**Comment by vohmar** [comment]
updated ticket description for approach on how to solve the admin settings issue to support innactive domains and require minimum two ns records for active domains. Also added doc update request.

**Comment by vohmar** [comment]
just to be clear the domain with no pending statuses, prohibitions and ns elements will have statuses 'ok' and 'inactive'. Updated the ticket description as well with this clarification..

**Comment by artur-beljajev** [comment]
> to activate a domain the registrant has to add at least 2 nameserver records to the domain. If there is only 1 valid ns element present error must be returned
> 2308 "Data management policy violation; Nameservers count must be between 2-11 for active domains"

Do we really need different response codes for required and optional settings? Currently the following response is returned:

```
  <response>
    <result code="2004">
      <msg lang="en">Nameservers count must be between 2-11 [nameservers]</msg>
    </result>
```

**Comment by artur-beljajev** [comment]
@ratM1n Please prepare SQL for

> domain names with inactive status will not be propagated to zone file.

**Comment by artur-beljajev** [comment]
"application admin can remove any number of nameservers for any domain using admin interface (the no 1 host does not apply here)."

Is it completely new feature?

**Comment by vohmar** [comment]
Current result code 2004 is invalid - 2004 means "Parameter value range error" and points to incompatibility with ranges specified in protocol, the nameserver count is policy thing.  But the new codes 2304 and 2308 need to be different as one points to an error directly connected to the transform command and the other points to problems with current data that needs to be fixed.

> Is it completely new feature? Would you like to remove them one by one? (i.e. to add "delete" button to each nameserver row)

we are behind the schedule - this feature is dropped from this ticket.

**Comment by artur-beljajev** [comment]
So code 2004 should be completely replaced by 2308?

**Comment by vohmar** [comment]
> So code 2004 should be completely replaced by 2308?

Lets not deal with this in this ticket, but yes eventually we should stop using this response code for nameserver count errors.

**Comment by ratM1n** [comment]
updated generate_zonefile function so it will not include domains with 'inactive' status
sql:
https://gist.github.com/ratM1n/73127562ce3f29d865b4c1aa4867fc7d

**Comment by artur-beljajev** [comment]
"generate_zonefile" should be updated by migration.

**Comment by vohmar** [comment]
merge to staging fails:
https://github.com/internetee/registry/pull/315

**Comment by artur-beljajev** [comment]
Registrar creation in admin needs to be tested.

**Comment by vohmar** [comment]
registrar portal does not allow removing all nameserver records nor create a domain without nameservers - form based validation 
/registrar/domains/update
/registrar/domains/new

**Comment by artur-beljajev** [comment]
Can you collect all issued at once? Or it is the only one?

**Comment by vohmar** [comment]
* Updating an inactive domain (with statuses 'OK' and 'Inactive') by not activating it looses the OK status from the domain
https://staging-adm.infra.tld.ee:444/admin/epp_logs/41781
https://staging-adm.infra.tld.ee:444/admin/epp_logs/41785 (empty update, but the same result is with changing contacts or adding dnskey)
https://staging-adm.infra.tld.ee:444/admin/epp_logs/41789

**Comment by artur-beljajev** [comment]
Up

**Comment by vohmar** [comment]
in production, branch together with subbranches 
https://github.com/internetee/registry/tree/update-log-db-schema
https://github.com/internetee/registry/tree/improve-registrar
https://github.com/internetee/registry/tree/improve-rspec

deleted, closed
