### ISSUE TITLE
ForceDelete: support for multiple email templates

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#268]
The system currently has only on ForceDelete auto notification template designed for businesses not active in respective business registry. We need to have support for multiple templates

* dead private registrant
* other domain rules violation

ForceDelete can only be set using admin interface.  If admin sets the ForceDelete staus on a domain he/she must have an option to choose the reason: organisation ended, person dead, other domain rules violation.

Registry system must send the appropriate email to the registrant and admin contacts of the domain.

**Comment by artur-beljajev** [comment]
Template content is needed for both options

**Comment by vohmar** [comment]
example text for dead registrant

```
Lugupeetud domeeni [domain_name] kontaktisik
.ee domeeniregistrisse on domeeni [domain_name] kohta kantud järgmised andmed:

Registreerija nimi: [Registrant Name]
Registrikood: [ident code]

Eesti Interneti Sihtasutusele (EIS) on saanud teatavaks, et füüsiline isik isikukoodiga [ident code] on surnud.

Kuivõrd domeeni registreerijat enam ei eksisteeri, siis algatas EIS 02.01.17 vastavalt Domeenireeglite (http://www.internet.ee/domeenid/) punktile 6.6 domeeni [domain name] suhtes [30] päeva pikkuse kustutusmenetluse. Kustutamise käigus jääb domeen internetis kättesaadavaks.

Domeenireeglite punktist 6.6 tulenevalt on domeeni suhtes õigust omaval registreerijal võimalus esitada domeeni [domain name] registripidajale Registrar Second AS domeeni üleandmise taotlus Domeenireeglite p 5.3.6.2 kohaselt. Taotlusele tuleb lisada pärimisõiguse dokumendid, mis asendavad Domeenireeglite punktis 5.3.6.3 sätestatud üleandva registreerija nõusolekut. Vastav dokumentatsioon tuleb esitada Registripidajale esimesel võimalusel.

Kui üleandmine ei ole [30] päeva jooksul toimunud, kustub domeen [domain name] [24] tunni jooksul [02.02.17] juhuslikult valitud ajahetkel. Soovi korral on võimalik domeen pärast selle kustumist registrist “kes ees, see mees” põhimõttel uuesti registreerida.

Lisaküsimuste korral võtke palun ühendust oma registripidajaga:

[Registrar Second AS]
Email: [registrar2@example.com]
Telefon: []
Veebileht: []
```

**Comment by artur-beljajev** [comment]
What about "other domain rules violation"?

**Comment by artur-beljajev** [comment]
Which template should be selected in dropdown by default?

**Comment by vohmar** [comment]
current one - non-existent company

**Comment by artur-beljajev** [comment]
"other domain rules violation" template will be added as soon as text is ready.

**Comment by vohmar** [comment]
waiting for russian translation

**Comment by artur-beljajev** [comment]
This branch has some changes needed for #269

**Comment by vohmar** [comment]
Translations are in Gdocs, please update email temaplates

**Comment by vohmar** [comment]
last minute request from styling committee. Please make the 

- Lugupeetud/Dear/Уважаемый
- Lugupidamisega/Best Regards,/С уважением,

in bold in html version of the email

**Comment by vohmar** [comment]
in production
