### ISSUE TITLE
EPP: drop support for ddoc format legaldocs

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#270]
legaldocs in ddoc digital signature container format are not accepted by the registry any more. (deprecated and replaced by bdoc container format).

* schema to update: https://github.com/internetee/registry/blob/master/lib/schemas/eis-1.0.xsd
  * remove ddoc from allowed value list and update the version of the schema file.

some other updates might be necessary on the registry side as well. ie epp doc
* https://github.com/internetee/registry/blob/master/doc/epp/domain.md
* https://github.com/internetee/registry/blob/master/doc/epp/contact.md

**Comment by artur-beljajev** [comment]
I guess docs should be updated as well? At least this one https://github.com/internetee/registry/blob/master/doc/epp/contact.md

**Comment by vohmar** [comment]
@artur-beljajev Yes you are correct, any reference to ddoc as supported legaldoc file format should be removed. Updated the description.

**Comment by artur-beljajev** [comment]
What browsers do we support?

**Comment by vohmar** [comment]
Good questions - all the latest and greatest: Chrome, Safari, Firefox, MS Edge

**Comment by artur-beljajev** [comment]
- https://epp.tld.ee/schema/ee-1.1.xsd should be created
- epp-xml should have updated version in master to be able to point all gem consumers to the new version

**Comment by vohmar** [comment]
* https://epp.tld.ee/schema/ee-1.1.xsd - done
* for new schema file in master I need it in a separate branch that I can merge without affecting the rest of the code until all updates related to this are tested and approved.

**Comment by artur-beljajev** [comment]
№ 2: Agree. It is pointed to epp-xml#6

**Comment by vohmar** [comment]
@artur-beljajev please move schema and schema validation updates to separate branch so we could move only registry level validation updates to production and keep schema updates back until we have more reasons to require updates on registrars' side.

**Comment by artur-beljajev** [comment]
https://epp.tld.ee/schema/ee-1.1.xsd must be removed as well.

**Comment by vohmar** [comment]
@artur-beljajev does not work. I was able to send legaldoc in ddoc format via EPP and GUI (portal for registrars, web client)

staging/admin/epp_logs/43684

**Comment by artur-beljajev** [comment]
Branch "registry-270-no-schema-update" has no EPP-related changes, since it requires schema change which we wanted to avoid as far as I remember.

Though the app itself should not allow to add it via UI because of model-level validation. @teadur or @ratM1n can you check if any instance has "legal_document_types" in application.yml configured.

**Comment by ratM1n** [comment]
no, "legal_document_types" is not set in application.yml . its there but commented out.

**Comment by artur-beljajev** [comment]
1. http://prntscr.com/e9hq0r This is what I got when I tried to create new contact using .ddoc file. Tested against branch "registry-270-no-schema-update" in registrar area.
2. Please create additional tickets in corresponding projects if needed.

**Comment by vohmar** [comment]
everything merged and deployed on staging, but still can send legaldocs in ddoc format using the portal for registrars.

**Comment by vohmar** [comment]
steps to reproduce:
1. login to the portal for registrars
2. select list of domains
3. click edit action after any domain that does not have updaterProhibited, registrantChangeProhibited or deleteCandidate status
4. do a registrant change with verified option selected
5. add a ddoc format legaldoc
5. press save = success

**Comment by artur-beljajev** [comment]
"ddoc" format is now removed from registrar UI (from domains and contacts). It turns out that I actually can only apply this change to front-end, since removing ddoc from backend also affects EPP schema.

Front-end validation is guaranteed to work in the latest versions of Chrome and Firefox.

**Comment by artur-beljajev** [comment]
See branch "registry-270-no-schema"

**Comment by vohmar** [comment]
merge conflicts on staging:
https://github.com/internetee/registry/pull/408

**Comment by artur-beljajev** [comment]
Merged

**Comment by vohmar** [comment]
still the same, can add legaldocs in ddoc format using the portal for registrars (/registrar/domains/edit?domain_name=...) no problem. The branch is merged and deployed - portal version 6a090ab - that is the latest staging version.

**Comment by vohmar** [comment]
partly solved and in production
