### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#273]
- "SSLCARevocationCheck chain" should probably be commented out under repp.conf, to retain Apache < 2.4 support 
- EPP instance apache config is missing (the one that listens 8080)

https://github.com/internetee/registry/blob/master/README.md

**Comment by artur-beljajev** [comment]
@teadur @ratM1n FYI

**Comment by vohmar** [comment]
Cannot merge to staging: https://github.com/internetee/registry/pull/382

**Comment by artur-beljajev** [comment]
Merged.

**Comment by vohmar** [comment]
in production
