### ISSUE TITLE
Remove "api_users" db table

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#274]
Unused, empty on prod

**Comment by vohmar** [comment]
this requires some thought - as having admin and api users in the same table is not ideal. So hopefully the result will be vice versa with userinfo in the api_users table.

**Comment by artur-beljajev** [comment]
Makes sense.

**Comment by artur-beljajev** [comment]
Done in #599

**Comment by teadur** [comment]
Dropping the table done in #599 the correct solution will be implemented in #520
