### ISSUE TITLE
Check schemas

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#276]
In ticket #251 three schema files got updated
* contact-ee-1.1.xsd
* epp-ee-1.0.xsd
* all-ee-1.1.xsd

all references to the previous versions of these schemas 
* contact-eis-1.0.xsd
* epp-1.0.xsd
* all-ee.xsd

must be updated to the newest version

Update is necessary in example requests in xml_console of the portal for regustrars and epp-we-client
Some of the epp requests and responses to be updated are contact:delete, epp hello

also documentatsion for epp requires appropriate updates:
* https://github.com/internetee/registry/tree/master/doc/epp
* https://github.com/internetee/registry/blob/master/doc/epp/contact.md
* etc

**Comment by artur-beljajev** [comment]
Done by #251

**Comment by artur-beljajev** [comment]
Those are the only references of above mentioned schema files (among all projects):

http://prntscr.com/duqwzj

**Comment by vohmar** [comment]
nothing changed, all done in other tickets like #251
