### ISSUE TITLE
Directo monthly registrar report script checks invoice nr range only on start

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#277]
Registry system send reports to EISs accounting system at the start of each month  - one per registrar - that shows all transactions done on the prepayment account  - adding credit, removing credit for domain creates and renews.

The script to create theser reports cheks the invoice number range in the config (Directo Monthly Number Max (/admin/settings)), but does this only once when the script starts. As there are 40 different reports to send (one per registrar) this becomes a problem when the remaining number of invoice numbers is less than required. This can lead to conflicts in the accounting system Directo

I see two options to solve this:
* check the max value before creating any invoices/reports
* check the number of active registrars (the number of invoices/reports to be sent out) at the start of the script and verify that there are enough numbers available to create an invoice for all the registrars.

**Comment by artur-beljajev** [comment]
See #509

**Comment by vohmar** [comment]
fixed by #1524
