### ISSUE TITLE
Admin: registrar profile is missing website

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#279]
the admin interface is missing an option to enter or change the website address of a registrar. Also the profile view (/admin/registrars/_xxx_) does not return the value of url cell from the registrar table.

Add the option to enter and change website address field 
* /admin/registrars/_xxx_/edit
* /admin/registrars/new

and return the value from db in the registrars profile view in the contact box
* /admin/registrars/_xxx_

**Comment by artur-beljajev** [comment]
Is it optional attribute?

**Comment by vohmar** [comment]
@artur-beljajev yes, the webpage attribute is optional

**Comment by vohmar** [comment]
cannot merge to staging: https://github.com/internetee/registry/pull/379

**Comment by artur-beljajev** [comment]
Merged

**Comment by vohmar** [comment]
in production, branch deleted
