### ISSUE TITLE
Relax EPP security restrictions for dev env to allow manual debugging

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#284]
- Eliminate EPP session timeout. This is needed to be able to manually test and debug without having to relogin every 5 mins.
- Allow using EPP without a certificate

It's definitely worth looking for another solution later, since all those environment checks can potentially lead to security holes and sporadic errors.

**Comment by artur-beljajev** [comment]
@vohmar Perhaps you want it to be configurable? If so, how often it is expected to change it? I am not sure every config should be present in admin.

**Comment by artur-beljajev** [comment]
Timo, please review it and merge to master ASAP

**Comment by vohmar** [comment]
I really do not feel comfortable with creating security holes in the system. How do you test that certificate based security is still working or debug certificate auth issues? I can go with configurable timeouts and thus enabling to set higher values for dev env.

**Comment by artur-beljajev** [comment]
The last paragraph was more in general, for your info. Currently there is no another quick solution.

**Comment by artur-beljajev** [comment]
Temporary solution is in master. Proper one will be implemented later.
