### ISSUE TITLE
Validation error when optional "voice" attribute is not provided on EPP contact:create

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#289]
https://github.com/internetee/registry/blob/cf93e77845503222be1c19584a6dab2bb0212239/lib/schemas/contact-eis-1.0.xsd#L84-L84 declares "voice" attribute as optional, however, https://github.com/internetee/registry/blob/183c2bb82c6e491bc9cf8d5736989188b673ced5/app/controllers/epp/contacts_controller.rb#L104 validates its presence, so I get this error message when trying to create new contact without it http://prntscr.com/diqs0f.

**Comment by vohmar** [comment]
according to .ee policy voice is always required. Schema files do not represent the whole picture of domain regulations, it often gives broader choice to support configuration options ie to support postal address to be configurable (required vs not required) it is easier to make addr element in schema always optional to escape the requirement to update the files on every configuration change.

**Comment by vohmar** [comment]
Not an issue as phone nr is mandatory by policy for .ee registrations
