### ISSUE TITLE
filter out base64 of legaldoc from syslog

### ISSUE THREAD

**Issue by teadur** [internetee/registry#314]
Like implemented in epp xml log:
https://github.com/internetee/registry/blob/16ebdc6c900ddbce7990205da327a627f4f2dcae/app/controllers/epp_controller.rb#L364

Legaldoc xml should be filtered out from syslog logging.

**Comment by teadur** [comment]
If possible original size of the removed string would be nice to have, [FILTERED] (403538409 kbyte)

**Comment by vohmar** [comment]
we also need to think where is a more suitable place to log/save the whole incoming query with base64 intact

**Comment by teadur** [comment]
I would split it to two issues, your proposed one as enchantment and the current one bug, because current solution brakes syslog logging.

**Comment by artur-beljajev** [comment]
Can you show me some examples of log strings?

**Comment by teadur** [comment]
https://git.tld.ee/Register/probleemid/blob/master/create.legaldoc.ee#L21

**Comment by artur-beljajev** [comment]
Why do we need to send plain and hard-to-read "frame" parameter of EPP query (http://prntscr.com/ed5dv5) to syslog, if we have beautifully formatted EPP log (/admin/epp_logs/)? I could just exclude this parameter from logging.

**Comment by teadur** [comment]
@artur-beljajev because we want todo log analytics on syslog we really need the data in syslog and thats the problem with current solution as it brakes syslog logging.

So sadly no we cant just exclude everything from syslog, we should only exclude the base64 of legaldoc but really need the rest.

**Comment by artur-beljajev** [comment]
Based on first link, "eis:legalDocument" should be filtered out, whereas in the 2nd link there is "ns3:legalDocument" entry. I cannot find any info about ns:legalDocument attribute. What other entries should be filtered out then?

**Comment by teadur** [comment]
@artur-beljajev all fields that contain base64 format of legaldoc should be filtered out (epp legaldocument element). I dont know whats the difference of eis:legaDocument and ns3:legalDocument, the last request was made from registrar portal, maybe its source gives some light why its using ns3 prefix rather then eis.

**Comment by artur-beljajev** [comment]
Only log raw request XML.

**Comment by artur-beljajev** [comment]
Only `raw_frame` param is passed though filtering

**Comment by vohmar** [comment]
unable to merge to staging: https://github.com/internetee/registry/pull/399

**Comment by artur-beljajev** [comment]
Merged

**Comment by teadur** [comment]
In production
