### ISSUE TITLE
Redirect debug messages from STDOUT to default logger

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#316]
http://prntscr.com/dovx24

**Comment by artur-beljajev** [comment]
@ratM1n FYI

**Comment by ratM1n** [comment]
ok, log is directed to syslog:
Jan 25 13:23:38 staging ADMIN[24642]: -----> Duplicates fixed for 0 rows in 1.13 seconds

**Comment by artur-beljajev** [comment]
Great!

**Comment by vohmar** [comment]
in production
