### ISSUE TITLE
Update EPP request-response examples

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#326]
EPP request-response examples are outdated
registry/doc/epp-examples.md

for example:
https://github.com/internetee/registry/blob/master/doc/epp-examples.md#epp-contact-with-valid-user-create-command-successfully-creates-a-contact
this request should return code 1100 not 1000 in the light of current .ee domain regulations.

there should also be an example of request without \<contact:addr> element that returns code 1000. As this doc is generated from model tests we should add also note about settings in case non-default values are used - address processing disabled for example.

**Comment by artur-beljajev** [comment]
#351

**Comment by artur-beljajev** [comment]
Those examples were previously generated using `test:epp_doc` rake task from the specs located at spec/epp. Those were not model specs (which are in `spec/models` folder).

**Comment by vohmar** [comment]
Please update the examples. Will create separate ticket for fully automated solutions.

**Comment by vohmar** [comment]
in production, branch deleted
