### ISSUE TITLE
Domain in exp pending list whithout the state present

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#328]
We have this kind of errors in production:

`2017-01-03 09:20:10 UTC - ISSUE: DOMAIN _dom_id_: _domainname.ee_ IS IN EXPIRED PENDING LIST, but no pendingDelete/pendingUpdate state present!`

this means that there is data in registrant_verification_asked_at column in domains table of registry db, but the appropriate pending status is missing from the statuses column.

this happens when registrant change request is made that changes the active registrant object to it self
info: https://staging-adm.infra.tld.ee:444/admin/epp_logs/42476
update: https://staging-adm.infra.tld.ee:444/admin/epp_logs/42484

the result is 
statuses = ok and 
registrant_verification_asked_at "2017-01-03 09:56:12.653799" together with token and pending_json colums filled

no status change is present because epp understands that it is an empty request - verification columns should be left untouched as well

**Comment by artur-beljajev** [comment]
How this kind of request is handled (what code and description is returned) now and how it should be?

**Comment by vohmar** [comment]
There is no special result code for this case so the correct result code is 1000 Command completed successfully. System must detect that the request is changing current registrant object for it self so actually nothing is changed and therefor no confirmation is necessary. In general it works like that but unfortunately registrant_verification_asked_at, _token and pending_json get still filled.

**Comment by artur-beljajev** [comment]
@vohmar Double-check the specs, please

**Comment by vohmar** [comment]
in production
