### ISSUE TITLE
Que errors on pending update notifications

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#330]
Test:
"DomainMailer", "pending_update_expired_notification_for_new_registrant", _000_
error in Que:
```
undefined method `pending_update_expired_notification_for_new_registrant' for DomainMailer:Class
/home/registry/registry/releases/107/vendor/bundle/ruby/2.2.0/gems/actionmailer-4.2.5.2/lib/action_mailer/base.rb:569:in `method_missing'
/home/registry/registry/releases/107/vendor/bundle/ruby/2.2.0/bundler/gems/que-mailer-32156f258993/lib/que_mailer.rb:27:in `method_missing'
```

Prod:
"DomainMailer", "registrant_updated_notification_for_old_registrant", _12345, 567890, 876543,_ true
"DomainMailer", "registrant_updated_notification_for_new_registrant", _12345, 567890, 876543,_ true
error in Que:
```
undefined method `name' for nil:NilClass
/home/registry/registry/releases/63/app/views/mailers/domain_mailer/registrant_updated_notification_for_old_registrant.html.erb:15:in `_app_views_mailers_domain_mailer_registrant_updated_notification_for_old_registrant_html_erb__4593693694363182006_69930414084780'
```
```
undefined method `name' for nil:NilClass
/home/registry/registry/releases/63/app/views/mailers/domain_mailer/registrant_updated_notification_for_new_registrant.html.erb:15:in `_app_views_mailers_domain_mailer_registrant_updated_notification_for_new_registrant_html_erb___3069649069915637467_69930415448720'
```

**Comment by artur-beljajev** [comment]
> "DomainMailer", "pending_update_expired_notification_for_new_registrant", 000
> error in Que:

It must be some old queue record. There isn't any `DomainMailer#pending_update_expired_notification_for_new_registrant` method call in master branch.

**Comment by artur-beljajev** [comment]
> Prod:
> "DomainMailer", "registrant_updated_notification_for_old_registrant", 12345, 567890, 876543, true
> "DomainMailer", "registrant_updated_notification_for_new_registrant", 12345, 567890, 876543, true
> error in Que:

I cannot debug on prod. Based on error description there must be some non-existing record in DB.

**Comment by vohmar** [comment]
the prod problem is fresh - today's error messages for four different domains.

**Comment by artur-beljajev** [comment]
@ratM1n I either production DB clone or access. I cannot debug otherwise.

**Comment by vohmar** [comment]
we managed to reproduce the bug on staging env. The error appears if the receiving registrant object does not have postal address.

https://staging-adm.infra.tld.ee:444/admin/que/jobs/350680

**Comment by artur-beljajev** [comment]
@vohmar What do you think if we hide the address from those email templates?

**Comment by vohmar** [comment]
yes, I agree.

**Comment by vohmar** [comment]
in production, branch deleted, ticket closed
