### ISSUE TITLE
All places with pagination should show result count

### ISSUE THREAD

**Issue by teadur** [internetee/registry#339]
All places that have pagination, should show the result count on the line where you can change pages.

     1 2 3 Next › Last »  (numcount)

**Comment by artur-beljajev** [comment]
@teadur Isn't this feature already in place? https://prnt.sc/prj4ym

**Comment by teadur** [comment]
@artur-beljajev i dont know, anyone hasnt referenced this issue in any commits as you can see.

**Comment by vohmar** [comment]
most of the views do have record count present, but not all. Examples of such pages - Admin (registrars, api and admin users, bank statements, invoices etc), Registrar (billing).
