### ISSUE TITLE
Load JS in async mode in admin area

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#341]
Fix translations

**Comment by artur-beljajev** [comment]
#268

**Comment by artur-beljajev** [comment]
Cache purge may be needed after this change

**Comment by artur-beljajev** [comment]
Updated

**Comment by vohmar** [comment]
the role info is broken admin user detail view (/admin/admin_users/ID_HERE)
![image](https://cloud.githubusercontent.com/assets/7734747/22098676/59007fee-de30-11e6-84c8-becd13a6a748.png)
in that example the real value for role is admin

**Comment by artur-beljajev** [comment]
Fixed

**Comment by vohmar** [comment]
in production, branch deleted
