### ISSUE TITLE
Directo: admin missing directo_handle

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#343]
In the admin interface there is no option to fill directo_handle information for regsitrars. It is also not returned in UI to see the effective value. 

directo_handle is part of Directo integration - necessary to match registrars in registry system to companies in accounting system.

* add a field to enter and edit directo handle value in create and edit registrar forms
* return directo handle value in registrar profile view

in generic view we should try to redesign directo integration into separate integrator module as a non standard EIS specific feature.

**Comment by artur-beljajev** [comment]
How current registrars in production got their values? Manually?

**Comment by vohmar** [comment]
imported from FRED and new registrars by manual intervention

**Comment by artur-beljajev** [comment]
> directo_handle is part of Directo integration - necessary to match registrars in registry system to companies in accounting system.

so "directo_handle" is a kind of registrar's uid (unique id) in Directo?

**Comment by ratM1n** [comment]
Yes, some do match with registrar 'code' in our system. I suggest to handle it so, that if 'directo_handle' is present, use 'directo_handle', if not, use 'code'

**Comment by artur-beljajev** [comment]
> [11:47:59] Georg: osadel erineb
> [11:48:56] Georg: osadel on selleks üldse mingi kood (näiteks 1001 ja 1002) mitte sama mis neil code väljas on
> [11:49:13] Artur Beljajev: okei
> [11:49:17] Georg: ja tihti on see directo_handle lühem versioon CODE-ist
> [11:49:34] Georg: näiteks code=EESTIDOMEENID directo_handle=EEDO

**Comment by artur-beljajev** [comment]
Decided to always require that Directo handle (which is now more abstract `accounting_customer_code`)

**Comment by artur-beljajev** [comment]
@teadur or @ratM1n Please make sure production env has no empty or NULL values.

**Comment by artur-beljajev** [comment]
Added under "Miscellaneous" section.

**Comment by artur-beljajev** [comment]
#376 has been merged with this ticket since in addition to having dead code, that rake task modifies standard rake tasks in a way that prevents `rake test` from running.

**Comment by artur-beljajev** [comment]
I am moving this ticket to "Testing" section so I know it is done. It's good idea to wait until #509 is done.

**Comment by artur-beljajev** [comment]
Once this ticket in review, it may be better to merge #626 first, to make diff of this ticket smaller.

**Comment by artur-beljajev** [comment]
Test Directo export.
