### ISSUE TITLE
EPP: deleteCandidate does not block all epp operations

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#355]
deleteCandidate status stands for deleted domain that is not yet released for re-registration. No EPP operations are possible when this status is set.

This does not seem to be the case any more. A registrar was able to make registrant change on a domain with deleteCandidate status. It looks like only the renew is currently blocked by deleteCandidate status.

error code for any epp request must be as it is for renewals

```
    <result code="2105">
      <msg lang="en">Object is not eligible for renewal</msg>
    </result>
```

**Comment by artur-beljajev** [comment]
- update
- transfer
- delete

**Comment by vohmar** [comment]
@artur-beljajev 
Merge conflict with staging: https://github.com/internetee/registry/pull/356

**Comment by artur-beljajev** [comment]
Fixed

**Comment by artur-beljajev** [comment]
btw, you can fix changelog issues right from the browser.

**Comment by vohmar** [comment]
@artur-beljajev please revert staging branch merge from this branch as we have commits in staging not yet ready for master.

**Comment by artur-beljajev** [comment]
Done

**Comment by artur-beljajev** [comment]
Merged to registry-269

**Comment by vohmar** [comment]
in production, branch deleted
