### ISSUE TITLE
Admin: epp log heading - <span class="translation_missing...

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#358]
Translation missing message for the heading of epp_log details view

![image](https://cloud.githubusercontent.com/assets/7734747/22324422/e28b9eb6-e3b1-11e6-9b8c-75b1ac36c53e.png)

/admin/epp_logs/43477

The same kind of error is on the browser tab heading

**Comment by teadur** [comment]
fixed with https://github.com/internetee/registry/commit/9d68bea42bb9299cd817289a42e2cb70f8b91fcc
