### ISSUE TITLE
EPP: registrant change with verified=yes fails

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#359]
Tested on staging

registrant change with verified=yes value succeeds with code 1001 ie action pending although it should not as the request is pre-approved and verified by the current registrant.

The domain is set to pendingUpdate status

confirmation request email is sent out

And te registrant is never changed regardless of current registrant approving the change additionally or not.

staging
1. update request and response: admin/epp_logs/43496
2. info request: /admin/epp_logs/43500
3. poll message for registrant confirmation: /admin/epp_logs/43508
4. info request after confirm: /admin/epp_logs/43512

Expected result:
verified=yes for both update registrant and delete domain must result in auto approved transform. No confirmation emails must be sent.

**Comment by artur-beljajev** [comment]
Did you try to change registrant "timo-nons2.ee" to "REG2:TIMO"?

**Comment by artur-beljajev** [comment]
This spec passes, but I suspect it is wrong https://gist.github.com/artur-beljajev/849730268739c98b408280699f74b934

Can you explain in details how this feature works?

**Comment by artur-beljajev** [comment]
#328

**Comment by vohmar** [comment]
cannot reproduce any more.

@artur-beljajev the spec you referenced seems good and should pass as it is.

**Comment by artur-beljajev** [comment]
Spec is added for this case. No code changes was made.

**Comment by vohmar** [comment]
cannot merge to staging: https://github.com/internetee/registry/pull/385

**Comment by artur-beljajev** [comment]
Conflict fixed

**Comment by vohmar** [comment]
in production
