### ISSUE TITLE
Fix typo in setting name

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#371]
`Setting.request_confrimation_on_registrant_change_enabled` (notice "conf**ri**mation").

**Comment by artur-beljajev** [comment]
@vohmar Is there any default for this setting according to EPP spec?

**Comment by vohmar** [comment]
this is custom setting specific to us. The idea is to protect registrant from admin contact. There are two tipes of requests for this model - registrant change and domain delete. In registry system the default state is disabled, it is configurable using admin interface and for .ee it is enabled for both registrant change and delete. How to use verified parameter/element related to these settings is described in epp doc in github

**Comment by artur-beljajev** [comment]
> the default state is disabled

Actually it is enabled:

https://github.com/internetee/registry/blob/e051784e4cbc10a520f8c0cc87e01bb962d58b60/config/app.yml#L20
