### ISSUE TITLE
Consider improving registrant change confirmation UI in registrant area

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#372]
http://prntscr.com/e8f172

How about changing"reject" button's color to red and move swap it with "confirm" button? I bet many folks will click on "reject" intuitively since usually so called "OK" button is on the right side (for example, notice buttons' placement on this page).

**Comment by vohmar** [comment]
we are hiring UX specialist to work out new design to all our user interfaces including that one. Pre-analysis in currently in progress.

**Comment by artur-beljajev** [comment]
Sounds cool.
