### ISSUE TITLE
Upgrade to Rails 5.0

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#377]

**Comment by teadur** [comment]
Currently upgrade to Rails5 is blocked by paper_trail #426

**Comment by artur-beljajev** [comment]
It is also blocked by lack of decent test coverage. For now this ticket is just to collect all feature/fixes I might need.

**Comment by artur-beljajev** [comment]
https://hashrocket.com/blog/posts/how-to-upgrade-to-rails-5

**Comment by artur-beljajev** [comment]
@maciej-szlosarczyk FYI

**Comment by artur-beljajev** [comment]
https://github.com/rails/rails/pull/13157

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/pull/868

**Comment by artur-beljajev** [comment]
https://github.com/ruby-i18n/i18n/releases/tag/v1.1.0

**Comment by artur-beljajev** [comment]
https://github.com/rspec/rspec-rails/issues/1530#issuecomment-177883299

**Comment by artur-beljajev** [comment]
`paper_trail` support for Rails 5 has been added in version 5.0.0 (https://github.com/paper-trail-gem/paper_trail/blob/master/CHANGELOG.md#500-2016-05-02)

**Comment by artur-beljajev** [comment]
`constraints: {:id => /[^\/]+(?=#{ ActionController::Renderers::RENDERERS.map{|e| "\\.#{e}\\z"}.join("|") })|[^\/]+/}`

**Comment by vohmar** [comment]
* Registrar - Contact create and update fails. Result:
![image](https://user-images.githubusercontent.com/7734747/68020242-910f9900-fca6-11e9-8b2b-4365b28a217a.png)
Query does not reach registry - there is no record in epp log
* EPP  - contact update resulted in 2400 command failed (https://st-adm.infra.tld.ee/admin/epp_logs/76985). Update fails for contacts that are linked to a domain. Unlinked contacts update OK.

**Comment by artur-beljajev** [comment]
> Registrar - Contact create and update fails

create, update and delete controller actions are fixed.

**Comment by vohmar** [comment]
* contact create, update and delete are OK

Admin:
* Domain versions do not open (not all domains have this problem, but a lot on staging do):
![image](https://user-images.githubusercontent.com/7734747/68046579-e2d71400-fce4-11e9-8c38-f27953951e79.png)
* account activities return error;
![image](https://user-images.githubusercontent.com/7734747/68047236-8aa11180-fce6-11e9-9325-c547f86903af.png)

Registrant:
* nameserver and dnssec key cells are red for some reason
![image](https://user-images.githubusercontent.com/7734747/68048480-52e79900-fce9-11e9-8b86-b47337b256bc.png)

**Comment by vohmar** [comment]
registrant portal returns an error on accessing domain info view
![image](https://user-images.githubusercontent.com/7734747/68664028-50d2d500-0548-11ea-870c-55671df83ae9.png)

**Comment by artur-beljajev** [comment]
Something wrong with database deployment.

**Comment by artur-beljajev** [comment]
Branch is now updated to reflect recent bug fixes from master.
