### ISSUE TITLE
Remove bullet gem

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#378]
- This gem addresses quite rare case and leads to premature optimization
- The code below tries to adjust itself to gem's requirements, which is unnecessary effort

I see a very little benefit of having this dependency.

```
  # optimization under children loop,
  # otherwise bullet will not be happy
  def domains_present?
    return @domains_present if @domains_present
    domain_contacts.present? || registrant_domains.present?
  end
```

`regt = Registrant.find(registrant.id) # temp for bullet`

```
# all includes for bullet
@domain = Epp::Domain.where(id: @domain.id).includes(nameservers: :versions).first
```

**Comment by teadur** [comment]
Reading from the gem's homepage it doesnot actualy change behviour only report places where you could improve your code, or i misunderstood something ? 

https://github.com/flyerhzm/bullet

So what you are sayng is that the optimization suggested by bullet is wrong  ?

**Comment by artur-beljajev** [comment]
No, I don't say they are wrong. Please study the description above for the reasons. I just updated it. 
Initially I started doing with this because of continuous errors when running specs http://prntscr.com/ebwqw, but eventually concluded that it is not needed.

**Comment by teadur** [comment]
Your screenshot link is broken, i still  dont understand if the optimization suggested by bullet make sense, why using them doesnot ?

**Comment by artur-beljajev** [comment]
Because of № 1.

**Comment by artur-beljajev** [comment]
Also, please note № 2: it **is** a problem introduced by the gem.
