### ISSUE TITLE
Rename "ZonefileSetting" model

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#381]
- It is against the convention (it should be ZoneFileSetting then)
- It consists of 3 words (which makes it quite difficult to use)

Consider the following names:
- ZoneFile
- Zone

https://en.wikipedia.org/wiki/Zone_file

**Comment by vohmar** [comment]
ZonefileSetting references to the fact that it is configured in admin portal under settings>zonefile.
ZoneFile would also be OK if it improves readability and development somehow.

**Comment by artur-beljajev** [comment]
Fixed by #475
