### ISSUE TITLE
Improve test processes

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#388]
Problem:
Impossible to test feature branches in isolation:
- Unverified feature branches get merged with staging before testing
- If some bug is discovered, it's hard to understand which branch has introduced it
- It's cumbersome to revert feature branch from staging (multiple merge commits, multiple migrations)

Solution:
#547 

It probably also requires some `dev:prime` rake task tuning, but for this we must either agree on some common convention or allow customization of initial (and possibly dummy) data.

---
https://martinfowler.com/bliki/FeatureBranch.html

**Comment by artur-beljajev** [comment]
@vohmar Is there a requirement to continue using registrar testing area?

**Comment by vohmar** [comment]
@artur-beljajev what do you mean by registrar testing area

**Comment by artur-beljajev** [comment]
Perhaps I call it wrong. I am mean deployment instance that has been previously used by registrars for testing purposes.

**Comment by teadur** [comment]
Yes we have one enviroinment deployed for registrars to test their systems.
We continue offering this env to registrars.

**Comment by artur-beljajev** [comment]
db/schema-read-only.rb vs db/structure.sql

**Comment by artur-beljajev** [comment]
http://www.bradapp.com/acme/branching/branch-creation.html#PolicyBranch

**Comment by vohmar** [comment]
waiting for #547 to complete

**Comment by vohmar** [comment]
we still have a problem with merging non production branches into other branches in development. Will solve this by improving go live process - speed up testing and buggy solutions taking priority over other work in progress.
