### ISSUE TITLE
Remove config/initializers/autolabel.rb

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#407]
app/assets/stylesheets/shared/general-bootstrap.sass

.required:after
  content: "*"
  margin: 0 0 0 1px

.not-required:after
  content: ''

app/views/admin/admin_users/_form.haml
app/views/admin/api_users/_form.haml

**Comment by artur-beljajev** [comment]
@vohmar As a consequence of this change, forms that do not have `required` class set on a label tag explicitly will not have that `*` symbol near required fields. This is however pure UI thing. No validation is affected. Please create a new ticket to address this issue if needed.

**Comment by teadur** [comment]
Could you reference the ticket what will fix the UI once you have created to here.
