### ISSUE TITLE
Registrar: mimetype error on valid legaldocs

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#432]
There is an inconsistent error condition with uploading legaldocs. There are reports of problems with bdoc, pdf and zip files. Chrome seems to be more error prone here.

error message in the portal: "Please enter a value with a valid mimetype."

**Comment by artur-beljajev** [comment]
Tested in latest Firefox and Chrome.

**Comment by artur-beljajev** [comment]
Changes from branch "registry-432" affect front-end validation of registrar area. Would be good to double-check it.

**Comment by vohmar** [comment]
in production
