### ISSUE TITLE
Investigate deprecation warnings

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#448]
artur@registry:~/registry$ bin/rake db:migrate
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.7.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /home/artur/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/railtie.rb:57)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /home/artur/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/railtie.rb:58)

**Comment by artur-beljajev** [comment]
@teadur FYI

**Comment by teadur** [comment]
should be fixed with pull  #450

**Comment by teadur** [comment]
Needs some testing before merge to master (digidoc_client logging)

**Comment by teadur** [comment]
Fixed and in Master.
