### ISSUE TITLE
Decouple registry app

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#472]
- Extract all EIS-specific code to gem
- Extract admin area to engine (what are the benefits?)
- Registrar and Registrant areas decoupling options:
  - Use json-based API
    - Rails API-mode http://edgeguides.rubyonrails.org/api_app.html?utm_source=rubyweekly&utm_medium=email
    - http://json-schema.org/
  - Implement them as engines and include shared functionality as a gem
---
https://martinfowler.com/articles/microservices.html

#280

**Comment by vohmar** [comment]
the goal is to leave only core functionality to registry project all public access will be done using APIs (limited legacy (epp, whois) and more functional modern (rest-epp, rest-whois) APIs). Public access interfaces like portals for registrars and registrants are our complementary implementations on functional UI that do not have any features not available using these APIs.

Admin interface is part of registries core functionality.

**Comment by artur-beljajev** [comment]
This is one of the examples of what I mean by EIS-specific code:

https://github.com/internetee/registry/blob/d3b275f85077369f1fd7bd0cd8e3083bfe14a30f/lib/tasks/import.rake#L615-L615

**Comment by vohmar** [comment]
agreed - this is an example of code not having little benefit for others unless they are also migrating from FRED. We might still need it though as we do not have everything imported to the new system yet.

**Comment by teadur** [comment]
I dont think we gain any value from moving import to separate gem, more work then value gained from it.
