### ISSUE TITLE
Hardcoded zones

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#473]
Zone list is hardcoded `CATEGORIES = %w(ee pri.ee fie.ee med.ee com.ee)` at app/models/pricelist.rb:18.
If I have .tld zone in `zonefile_settings` db table, I still see `ee`, `pri.ee` etc in zone dropdown when adding/editing price list.

http://prntscr.com/ewswgd

http://prntscr.com/ewswyk

**Comment by vohmar** [comment]
I would call this a bug. System should allow creating pricelists only for domains managed by the registry system.

**Comment by artur-beljajev** [comment]
Fixed by #475.

P.S. Zones are still hardcoded in directo.rb, but I would deal with this in another ticket.
