### ISSUE TITLE
Delete old migrations

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#479]

**Comment by teadur** [comment]
I would vote against it, i think it gives good overview of changes and when they are made to db, much better overview then to search git history.

**Comment by maciej-szlosarczyk** [comment]
A fairly common practice is to move old migrations to different folders separated by year, so that db/migrate is not cluttered, but the history still remains intact. Becomes a bit of a problem when you create a new database/instance and run migrations instead of loading the structure, but you should not do it anyway.

**Comment by artur-beljajev** [comment]
Git has all history anyway. I don't see a point keeping more than 1-2 months old ones.

**Comment by maciej-szlosarczyk** [comment]
Using pickaxe is multiple times more difficult than `ag`, not to mention that you need to know what you are looking for. I encourage you to use git pickaxe to find what type was column `domains.status` when it was first introduced to get familiar with the experience.

Also, I'd like to point out that our git history is too long to `git grep` it:

```
git grep "ns_set_id" $(git rev-list --all)

zsh: argument list too long: git
```

There are ways around it, but that's just asking for trouble.

**Comment by teadur** [comment]
Using magic (git history) to find the migrations seems like wasted time.

i don't mind having them in the migration directory but if it's more cleaner when we move them to yearly directories inside migration dir that would work for me.

**Comment by teadur** [comment]
Closing for now, we can always re-open if we get new ideas about the problem.
