### ISSUE TITLE
DEPRECATION WARNING: You didn't set `secret_key_base`

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#508]
artur@registry:~/registry$ bundle exec puma -b tcp://192.168.56.2 -p 3000 -w 2
[3399] Puma starting in cluster mode...
[3399] * Version 3.8.2 (ruby 2.2.7-p470), codename: Sassy Salamander
[3399] * Min threads: 0, max threads: 16
[3399] * Environment: development
[3399] * Process workers: 2
[3399] * Phased restart available
[3399] * Listening on tcp://192.168.56.2
[3399] * Listening on tcp://0.0.0.0:3000
[3399] Use Ctrl-C to stop
[3399] - Worker 0 (pid: 3428) booted, phase: 0
DEPRECATION WARNING: You didn't set `secret_key_base`. Read the upgrade documentation to learn more about this new config option. (called from validate_secret_key_config! at /home/artur/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/railties-4.2.7.1/lib/rails/application.rb:530)[3399] - Worker 1 (pid: 3431) booted, phase: 0

DEPRECATION WARNING: You didn't set `secret_key_base`. Read the upgrade documentation to learn more about this new config option. (called from validate_secret_key_config! at /home/artur/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/railties-4.2.7.1/lib/rails/application.rb:530)

**Comment by artur-beljajev** [comment]
`config/secrets-example.yml` removed as unused.

@ratM1nconfirmed, that no env has `config/secrets.yml`.

**Comment by artur-beljajev** [comment]
@ratM1n or @teadur It's also worth checking that application.yml has "secret_key_base" key filled on every env

**Comment by artur-beljajev** [comment]
In prod, branch removed, but the ticket is still not closed. Would be good to get some feedback from @ratM1n

**Comment by teadur** [comment]
@artur-beljajev if there would be application missing secret_key_base filling it it after users have been created would brake all the user logins , so not sure what checking of filled secrety_key_base would give. I would close this ticket.
