### ISSUE TITLE
EPP: incorrect error message on domain update with delete prohibited status set

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#512]
If a domain has serverDeleteProhibites status set together with pendingUpdate and registrar tries another update request this message is returned:

> Object status prohibits operation - serverDeleteProhibited [code: 2304]

instead of:

> Object status prohibits operation - pendingUpdate [code: 2304]

**Comment by artur-beljajev** [comment]
1. How can I reproduce it?
2. Please provide a list of all possible ways to trigger this bug (if many)
3. By "serverDeleteProhibites" you mean "serverDeleteProhibite**d**", right?

**Comment by vohmar** [comment]
1. set servedDeleteProhibites status on a domain via admin interface; initiate registrant change to set pendingUpdate; request any domain object update to get the incorrect error message
2. not aware of any other ways to trigger this bug. You might need to research this to be sure.
3. yes - there is not such status as serverDeleteProhibites in the registry system

**Comment by artur-beljajev** [comment]
```
<result code=\"2304\">\n      <msg lang=\"en\">Object status prohibits operation</msg>
...
<domain:status s=\"serverDeleteProhibited\">serverDeleteProhibited</domain:status>\
```

**Comment by artur-beljajev** [comment]
@vohmar kind reminder

**Comment by vohmar** [comment]
codeclimate — 16 new issues!
merged to master

**Comment by vohmar** [comment]
in production
