### ISSUE TITLE
Add dummy data generation rake task

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#515]
`rake dev:prime` 
`rake dev:prime[random]`

Also, seeds.rb purpose it to have default values, not initial as it currently is. I suggest that we move its contents to some rake task and update installation guide.
`rake bootstrap` task is added.

**Comment by artur-beljajev** [comment]
@vohmar Please notice an update.

For some reason, this ticket was merged to master, but still is present in "Testing" column.

**Comment by artur-beljajev** [comment]
Branch "registry-515" is removed.

**Comment by vohmar** [comment]
in production
