### ISSUE TITLE
Consider removing `epp_sessions.registrar_id` db column

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#544]
- Consider extracting `api_user_id` key from `epp_sessions.data` (TEXT) column and removing `epp_sessions.registrar_id`
- Registrar id can be obtained by looking at `users.registrar_id`

**Comment by teadur** [comment]
Why would it be better to extract api_user_id key from epp_sessions.data ?
From what is epp_Sessions.data made out of ? seems to be same value for one registrar, whats the point of that field ?

**Comment by artur-beljajev** [comment]
Done in some other ticket
