### ISSUE TITLE
Ruby upgrade

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#546]
Current version is 2.2.7 (https://github.com/internetee/registry/blob/master/.ruby-version).

> We are planning to end the support of the Ruby 2.2 series at the end of March 2018.
https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/

May or may not be connected to #377

Needed features:
- https://stackoverflow.com/a/3725154
- https://bugs.ruby-lang.org/issues/8976#note-30
- https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc

**Comment by teadur** [comment]
Before upgrading ruby new ruby version should be installed to all affected instances of code.
Once we have decided on new ruby version we should start installing correct versions to envs (done by rbenv ansible role)

**Comment by maciej-szlosarczyk** [comment]
If we are to update to 2.5 (currently latest version), here's a quick checklist of things that need to be done before:

---
[ ] Upgrade Rails to 4.2.10 #826 
[ ] Upgrade Devise (currently latest 4.4.3 worked just fine)
[ ] Upgrade Grape, as it throws multiple deprecation warning on Fixnum/Bignum -> Integer issue. I know we have #691, but getting on a Ruby version with security update is far more critical.

**Comment by teadur** [comment]
It should be fairly easy to change ruby version from ops view aswell, so i dont see problem moving to 2.3.x now and to 2.5 later.

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, please hold off with testing, as code climate pointed out that we require multiple code styling changes. I shall do them until early next week.

**Comment by vohmar** [comment]
Deployed on stagind. Registrar portal billing view returns error 500

`May  2 12:38:21 staging REGISTRAR[30712]: [staging-rar.infra] [cf004a93-3ac4-4877-bb2e-83fff989f08e] [192.168.6.34] #012ActionView::Template::Error (missing attribute: total):#012    67:                 %td{class: 'text-danger'}= t(:unpaid)#012    68: #012    69:               %td= l(x.due_date, format: :date_long)#012    70:               %td= currency(x.total)#012    71: .row#012    72:   .col-md-12#012    73:     = paginate @invoices#012  app/models/invoice.rb:163:in total'#012  app/views/registrar/invoices/index.haml:70:inblock in _app_views_registrar_invoices_index_haml___2664407200773425463_68452360'#012  app/views/registrar/invoices/index.haml:59:in `_app_views_registrar_invoices_index_haml___2664407200773425463_68452360'`

**Comment by maciej-szlosarczyk** [comment]
It seems like some migration on staging was not applied. `total` is a required field on Invoices since some time ago:

https://github.com/internetee/registry/commit/fb35ec5cbb6dbc2ea9848733923447165c591ec8

**Comment by maciej-szlosarczyk** [comment]
Now we need to update ansible scripts to install Ruby 2.3 @teadur.
