### ISSUE TITLE
Setup isolated environment for feature branch testing

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#547]
- Setup isolated env
  - Every branch should have its own databases 
https://mislav.net/rails/branching-the-database-along-with-your-code/
  - Here is the database.yml file I use for development https://gist.github.com/artur-beljajev/7f33c5730a6c268d3bbf7d269faab63f (leave only needed envs)
- Branch switcher should allows each tester to choose a branch (some bash script, no web UI)
  1. git fetch
  2. git checkout origin/registry-xxx
  3. git pull origin registry-xxx
  3. bundle install
  4. rake db:setup:all (it's worth checking how it behaves if run repeatedly, i.e. a tester selects same branch multiple times). I guess it's needed running db:drop:all before db:setup, since new migrations can appear once branch is selected. Or check if databases already exist and run db:migrate
  5. Import default data (users, domains, contacts, epp sessions, etc)
  6. Restart app server

I usually run those feature branch tests using `development` Rails env. Also, there is no need to generate assets.

### Limitations:
- It turns out that max length of database name is 63, so branch name "refactor-some-super-feature-in-admin-and-registrar-and-registrant-areas" means database name of "registry_api_log_development_refactor-some-super-feature-in-admin-and-registrar-and-registrant-areas", which it turn means it will be truncated to 63 chars (100 to 63). 

### Open questions:
- How and when to purge unused databases

**Comment by artur-beljajev** [comment]
@ratM1n I wonder if there is any way to bypass database name max length limitation.

**Comment by artur-beljajev** [comment]
@vohmar How many simultaneous testes we plan to support initially?

**Comment by teadur** [comment]
i think using issue id makes more sense for db name

**Comment by artur-beljajev** [comment]
Not all branches have ids

**Comment by vohmar** [comment]
mina script based test solution is ready - it deploys specified branch on staging env
waiting for something to test

**Comment by vohmar** [comment]
tested and works with mina scriptis - simpler solution that in description but still move in right direction. will colse the ticket for now
