### ISSUE TITLE
Activemodel not validating object throws wrong error

### ISSUE THREAD

**Issue by teadur** [internetee/registry#569]
Expected return is Activemodel errors shown in EPP.

Contact object validation fails:

irb(main):009:0> a.validate
USER MSG: ACTIVEMODEL: Contact [ident] Required parameter missing - ident
USER MSG: ACTIVEMODEL: Contact [ident_type] is missing
USER MSG: ACTIVEMODEL: Contact [ident_type] Object status prohibits operation: ident_type of contact CID:XXXX:xxxx is invalid
USER MSG: ACTIVEMODEL: Contact [ident] Ident country code is not valid, should be in ISO_3166-1 alpha 2 format
USER MSG: ACTIVERECORD: Contact #117517 ["Ident Required parameter missing - ident", "Ident Ident country code is not valid, should be in ISO_3166-1 alpha 2 format", "Ident type is missing", "Ident type Object status prohibits operation: ident_type of contact CID:XXXX:xxxx is invalid"] []
=> false

When user wants to update that object over epp non clear error is thrown:

Request XML is

<?xml version="1.0" encoding="UTF-8"?>

<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd">

       <command>

              <update>

                     <contact:update xmlns:contact="https://epp.tld.ee/schema/contact-ee-1.1.xsd">

                           <contact:id>CID:XXXXX:xxxxx</contact:id>

                           <contact:chg>

                                  <contact:postalInfo>

                                         <contact:name>New Contact name</contact:name>

                                  </contact:postalInfo>

                                  <contact:voice>+327.12345/contact:voice>

                                  <contact:email>email@domain.tld</contact:email>

                           </contact:chg>

                     </contact:update>

              </update>

              <extension>

                     <eis:extdata xmlns:eis="https://epp.tld.ee/schema/eis-1.0.xsd">

                           <eis:ident cc="CH" type="org">CHE-XXXXX</eis:ident>

                     </eis:extdata>

              </extension>

              <clTRID>XXXX:xxxx:784991809977051</clTRID>

       </command>

</epp>

 

Response XML is

<?xml version="1.0" encoding="UTF-8"?>

<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

       xsi:schemaLocation="lib/schemas/epp-ee-1.0.xsd">

       <response>

              <result code="1">

                     <msg lang="en">handle_errors was executed when there were actually no errors</msg>

              </result>

              <trID>

                     <clTRID>XXXX:xxxx:784991809977051</clTRID>

                     <svTRID>ccReg-5352543179</svTRID>

              </trID>

       </response>

</epp>

**Comment by artur-beljajev** [comment]
For some reason, the value of "ident" column from EPP request ("CHE-XXXXX") is not set on EPP contact:update. As I understand the code misses `at.merge!(ident: ident_frame.text)`
here https://github.com/internetee/registry/blob/d3b1a23e92bc1dc8ca80e9057a0fac47eab6b10a/app/models/epp/contact.rb#L187 but I need a confirmation

**Comment by artur-beljajev** [comment]
Also I need business rules, describing a case, when a user sends EPP contact:update request with the following part:
`<eis:ident cc="CH" type="org">CHE-XXXXX</eis:ident>`

**Comment by vohmar** [comment]
Rule 1: ident cannot be updated
Rule 2: ident_cc and ident_type can be updated if ident set does not validate and validates as a result of the update

**Comment by vohmar** [comment]
error code for invalid update request trying to change ident data

2308    "Data management policy violation" + validation rule based specification ie. 
_2308    "Data management policy violation: update of ident not allowed, please consider creating new contact object."_

other possible specifications
update of ident_cc not allowed, please consider creating new contact object.
update of ident_type not allowed, please consider creating new contact object.

**Comment by artur-beljajev** [comment]
If "ident" column cannot be updated, perhaps it's worth mentioning that in https://github.com/internetee/registry/blob/master/doc/epp/contact.md?

Something like "ident tag content is ignored".

**Comment by artur-beljajev** [comment]
As of now, to update "ident_type" or "ident_country_code", "ident" tab in EPP request must be empty:
`<eis:ident cc="CH" type="org">CHE-XXXXX</eis:ident>` fails
whereas
`<eis:ident cc="CH" type="org"></eis:ident>` succeeds.

**Comment by artur-beljajev** [comment]
Ident modification login must be completely retested.

**Comment by vohmar** [comment]
* contact update to a contact that had no ident_type and ident_cc values was successful with respective values of "birthday" and "ee" - birthday is not allowed in case of ee (not a valid Estonian identity format)
* contact update to a contact that had no ident type, valid date as an ident value and ident_cc as ee resulted in wrong error message 2308 on setting type to "birthday". Should have been 2005 (not valid Estonian identity)
* contact update to a contact that had no ident type, valid date as an ident value and ident_cc as ch resulted in error 2308  on setting type to "birthday" . Should have been 1000
* contact update to a contact that had no ident type, invalid date as an ident value and ident_cc as ch resulted in error 2308 on setting type to "birthday". Should have been 2005 (not valid birthday format)
* contact update to a contact that had no ident type, invalid date as an ident value and ident_cc as ee resulted in error 2308 on setting type to "birthday". Should have been 2005 (not valid Estonian identity format / not valid birthday format)
* contact update to a contact that had no ident_cc, valid date as an ident value and ident_type as birthday was successful with ident_cc values of "ee". Should have been 2005  (not valid Estonian identity format)
* contact update to a contact that had invalid ident_cc, valid date as an ident value and ident_type as birthday was successful with ident_cc value of  "ee". Should have been 2005  (not valid Estonian identity format)
* contact update to a contact that had invalid ident_type, valid date as an ident value and ident_cc as ee was successful with ident_type value of  "birthday". Should have been 2005  (not valid Estonian identity format)
* contact update to a contact that had no ident_cc, valid ident and ident_type as priv resulted in error 2308 on setting ident_cc to "EE". Should have been 1000
* contact update to a contact that had no ident_cc, valid ident and ident_type as priv resulted in error 2308 on setting ident_cc to "US". Should have been 1000
* contact update to a contact that had invalid ident_cc, valid ident and ident_type as priv resulted in error 2308 on setting ident_cc to "EE". Should have been 1000
* contact update to a contact that had invalid ident_cc, invalid ident and ident_type as priv resulted in error 2308 on setting ident_cc to "EE". Should have been 2005  (not valid Estonian identity format)
* contact update to a contact that had no ident_cc, invalid ident and ident_type as priv resulted in error 2308 on setting ident_cc to "EE". Should have been 2005  (not valid Estonian identity format)
* same problems as with ident_type priv apply to ident_type org as well

all the validation applied to contact create must apply to contact update as well (at the resulting object)

**Comment by artur-beljajev** [comment]
Database has some 17-char phone and fix numbers.

**Comment by artur-beljajev** [comment]
@vohmar 
Please provide the following for № 12:
- EPP request
- Expected behaviour

**Comment by artur-beljajev** [comment]
Fix unhanded error:
let(:contact) { build(:contact, code: 'TEST', ident: nil, ident_type: 'invalid', ident_country_code: nil) }

**Comment by artur-beljajev** [comment]
Why `ident_country_code` is not validated if `ident_type` is "birthday"?

https://github.com/internetee/registry/blob/master/app/models/contact.rb#L32

**Comment by vohmar** [comment]
@artur-beljajev 
No12:  https://staging-adm.infra.tld.ee:444/admin/epp_logs/46588
Expected behavior is as said in the error reports error 2005 as the current ident code is not valid EE personal identity code.
As specified in rule 1 the ident code cannot be updated - that means value of ident element can not be updated under any circumstance.
Rule 2 specifies that ident_cc and ident_type can be updated in case of invalid ident and the update results with valid one
So in the case where country code and type are missing and user attempts to update ident code the result is error 2308
If ident element is emtpy then the only way to fix the contact is to create a new object and replace the current one because of rule 1

ident_country_code was not initially required if the ident_type was set as birthday. Currently the country_code is always required and thus it should also be validated - so this is a bug.

**Comment by artur-beljajev** [comment]
Additional testing for all places where it's possible to add a contact is needed.

**Comment by artur-beljajev** [comment]
Fixes #179

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/issues/569#issuecomment-316840687 is still actual. I guess it's also needed to document the fact, that a user must provide currently valid `ident` to be able to update invalid type or country.

**Comment by vohmar** [comment]
failed tests:

*Create contact*

* ident type: org, ident cc: EE, ident: invalid. Result: error code 1 - should have been 2005 invalid Estonian ident format  (/admin/epp_logs/46852)
* ident type: birthday, ident cc: FI, ident: invalid. Result: error code: 2005, error message: Ident code does not conform to ISO 8601 standard. That is an unintuitive user hating message. Telling the ISO standard number is cool, but the important part is to say what is the actual format that is expected as it was with the original message "Ident not in valid birthady format, should be YYYY-MM-DD [ident]". So the message could be for example "Ident code is not in valid date format YYYY-MM-DD (ISO8601) [ident]" (/admin/epp_logs/46864). This goes for any contact create and update requests dealing with ident code or validating the ident set of existing contact object (ie domain renew)

*Update contact*

* initial state - ident type: org, ident  cc: invalid, ident: invalid (by Estonian rules ie 3 char long). Update - ident cc = EE. Result: error code 1 - should have been 2005 Invalid Estonian ident format for org (/admin/epp_logs/47100)
* initial state - ident type: org, ident  cc: missing, ident: invalid (by Estonian rules ie 3 char long). Update - ident cc = EE. Result: error code 1 - should have been 2005 Invalid Estonian ident format for org (/admin/epp_logs/47104)

*Other concerns:*

* are messages like "Ident type "birthday" is invalid for Estonia" dyamic. Meaning that if we introduce rules for Latvia for example describing their personal identity code format and disallowing birthday identity type will this message still work taking LT from the query and decrypting this into Latvia for the message?
* the message in case of attempt to change ident code and in case of attempt to change anything on a valid ident set is identical (2308 Data management policy violation: update of ident not allowed, please consider creating new contact object). This is confusing. There must be a separation to identify the source of problem.  IE the message must identify eis:ident element and ident code.

**Comment by artur-beljajev** [comment]
№ 5: Yes, it is extendable and error message is dynamic. https://github.com/internetee/registry/blob/3de5a0b51bc85d02ae9a07c9df66a1fbca61eace/app/models/contact/ident.rb#L38

**Comment by vohmar** [comment]
No 1, 3, 4 OK
No 2 OK

**Comment by vohmar** [comment]
No 6: error messages still need improvements

case1: contact:update ident - 2308: Invalid ident. Only ident type and country can be updated in case of invalid ident. Please create new contact object to update ident code.

case2: contact:update ident type/cc (ident data set validates) - 2308: Ident update is not allowed. Consider creating new contact object.

**Comment by artur-beljajev** [comment]
№ 6:
`errors.update_disallowed` What needs to be improved here?
`errors.wrong_ident` This error is displayed when user provides wrong `<ident></ident>` value in EPP request (I would use just "wrong" here to distinguish it from invalid by validating format of something). Why you want a user to create new contact?

**Comment by vohmar** [comment]
contact update:

case1: ident data set validates on an existing contact object - update of ident data not allowed. Attempt to update results "2308: Ident update is not allowed. Consider creating new contact object."

case2: ident data set is not valid on an existing contact object - update of ident_cc and ident_type is allowed in case the resulting data set validates
case2.1: attept to update ident code results in error (ident code cannot be changed in any condition) "2308: Only ident type and country can be updated in case of invalid ident. Please create new contact object to update ident code."
case2.*: different cases with handling updates of ident_country_code and ident_type of an invalid contact.

At the same time the general principle of detecting actual change still applies - if update includes data that matches the data already in db (in reality nothing is changed) it is not considered as attempt to change data and cannot result in error. For example

contact object with valid ident data set in registry
contact update with <ident type="same as in db", cc="same as in db">same as in db</ident>
results with code 1000

**Comment by vohmar** [comment]
* ident set is valid : if contact:update query includes eis:ident element with the same data as already in the system error 2308 is returned. Code 1000 is correct as nothing is changed with the ident data because of this query.

**Comment by artur-beljajev** [comment]
Fixed, spec added

**Comment by vohmar** [comment]
this branch includes changes from branch #231. As #231 is not ready I cannot merge this to master.

**Comment by vohmar** [comment]
FYI: merges reverted from master with this ticket:
https://github.com/internetee/registry/pull/605
https://github.com/internetee/registry/pull/586
https://github.com/internetee/registry/pull/575

**Comment by artur-beljajev** [comment]
See PR
