### ISSUE TITLE
Incorrect EPP response error code is returned if session limit per registrar is reached

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#587]
the system returns EPP code of 2501 in case EPP session limit reached
but EPP spec states that:

2502    "Session limit exceeded; server closing connection"

> This response code MUST be returned when a server receives
>               a <login> command and the command cannot be completed
>               because the client has exceeded a system-defined limit on
>               the number of sessions that the client can establish

Requires #543

**Comment by artur-beljajev** [comment]
@vohmar Does registrars' software rely on this somehow?

**Comment by vohmar** [comment]
@artur-beljajev not aware that it does. But we will let them know in advance before this is fixed in production
