### ISSUE TITLE
EPP: domain info and check to return info about in auction, reserved and blocked domains

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#597]
Problem: Currently EPP domain info and check queries return info only about registered domains. For this reason registrar will get informed about special conditions of certain domains over EPP only on the attempt to register it.

Solution: similarly to whois the epp info and check queries must return info on domain status if it is not registered but special conditions apply for registering.

There are two special conditions:
* reserved
* blocked

domain:info and domain:check queries must thus check domain status from reserved, blocked domains table and new delete candidate table in addition to domains table on the db.

domain:check
domain:name avail="0"
<domain:reason> messages:
Blocked

Reserved domains are actually available for registration requiring special code/password . So we cannot state these as avail = 0 and as domain:reason element is meant for stating the reason of unavailability check request will not reveal special conditions for registering such domains

domain:info
        `<domain:name>näide.ee</domain:name>`
        `<domain:roid>Auction-000001</domain:roid>`
        `<domain:status s="Reserved or Blocked"/>`
        `<domain:clID>NA</domain:clID>`

<domain:registrant> element is present only in case of reserved domains that have been reserved for auction winner. The element requires correct <domain:pw> value to be present in the query

**Comment by artur-beljajev** [comment]
> Problem: Currently EPP domain info and check queries return info only about registered domains.

In fact, reserved domains are handled in EPP domain:check, but currently `avail: 0` is returned for them.

**Comment by artur-beljajev** [comment]
`domain:roid` and `domain:clIDNA` in EPP domain:info are missing in auction spec: https://docs.google.com/document/d/1cBYPIDuOnQzHJ40kJsvSZXS-wVphR0-nVJu-OQbfIxI/edit?ts=5bfc525c#

**Comment by artur-beljajev** [comment]
> and new delete candidate table in addition to domains table on the db.

I guess it's rather part of #1067?

**Comment by vohmar** [comment]
@artur-beljajev fixed the github rendering issue for the epp xml example in the description, there is no such thing as clidna tag and roid is standard epp element and mandatory for info query response so need to return that one.

you are correct the reference to new delete candidate table refers to ticket #1067

**Comment by vohmar** [comment]
we need to revert the domain:info update - regsitrars prefer standard rfc solution for epp and getting info about reserved domains from whois. So

domain:info should return not found for both reserved and blocked domains and also domains in auction process once domain auctions go live.

check should return avail=1 once the domain is out of bidding step waiting for invoice payment and registration. Currently it remains unavailable.

* avail=1 for reserved domains and domains waiting for payment and registration in the auction process
* avail=0 for blocked domains and domains waiting for bids in auction process
