### ISSUE TITLE
Internal error on binding invoices

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#622]
/admin/bank_statements : bind payment to invoice
first try failed, second try succeeded (get vs post?)

error message:
`Oct 24 13:52:11 reg-l-epp ADMIN[7915]: [reg-l-adm.infra] [572aa675-4c57-4e87-a8d5-f3ee5d535cc8] [X.X.X.X] Completed 200 OK in 48ms (Views: 28.8ms | ActiveRecord: 6.1ms)
Oct 24 13:52:11 reg-l-epp ADMIN[7915]: [reg-l-adm.infra] [572aa675-4c57-4e87-a8d5-f3ee5d535cc8] [X.X.X.X] USER MSG: FLASH: {"notice"=>"Record created"}
Oct 24 13:52:13 reg-l-epp ADMIN[7915]: [reg-l-adm.infra] [e6f7cf5f-849f-472d-b5ed-8481f6ebc7c8] [X.X.X.X] Started GET "/admin/bank_statements/164/bind_invoices" for X.X.X.X at 2017-10-24 13:52:13 +0300
Oct 24 13:52:13 reg-l-epp ADMIN[7915]: [reg-l-adm.infra] [e6f7cf5f-849f-472d-b5ed-8481f6ebc7c8] [X.X.X.X] #012ActionController::RoutingError (No route matches [GET] "/admin/bank_statements/164/bind_invoices"):#012  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'#012  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'#012  
vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'#012  vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'#012  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'#012  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'#012  vendor/bundle/ruby/2.2.0/gems/
activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'#012  vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'#012  vendor/bundle/ruby/2.2.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'#012  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'#012  vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `
call'#012  vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'#012  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'#012  vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'#012  vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'#012  vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/application
.rb:165:in `call'#012  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'#012  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'#012  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'#012  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in 
start_threads'#012  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
Oct 24 13:53:26 reg-l-epp ADMIN[7915]: [reg-l-adm.infra] [7c00717a-ffdc-4a3a-a98e-e0ac6d932244] [X.X.X.X] Started POST "/admin/bank_statements/164/bind_invoices" for X.X.X.X at 2017-10-24 13:53:26 +0300
Oct 24 13:53:26 reg-l-epp ADMIN[7915]: [reg-l-adm.infra] [7c00717a-ffdc-4a3a-a98e-e0ac6d932244] [X.X.X.X] Processing by Admin::BankStatementsController#bind_invoices as HTML
Oct 24 13:53:26 reg-l-epp ADMIN[7915]: [reg-l-adm.infra] [7c00717a-ffdc-4a3a-a98e-e0ac6d932244] [X.X.X.X]   Parameters: {"authenticity_token"=>"[truncated]", "id"=>"164"}
Oct 24 13:53:26 reg-l-epp ADMIN[7915]: [reg-l-adm.infra] [7c00717a-ffdc-4a3a-a98e-e0ac6d932244] [X.X.X.X] Redirected to https://reg-l-adm.infra.tld.ee/admin/bank_statements/164
Oct 24 13:53:26 reg-l-epp ADMIN[7915]: [reg-l-adm.infra] [7c00717a-ffdc-4a3a-a98e-e0ac6d932244] [X.X.X.X] Completed 302 Found in 109ms (ActiveRecord: 61.7ms)`

**Comment by artur-beljajev** [comment]
That action is available only via POST. It can happen if JS has not been fully loaded, and therefore GET was used instead. Can you reproduce it?

`post 'bind_invoices', on: :member`

**Comment by vohmar** [comment]
no we are not able to systematically reproduce it. The problem has happened before, but does not occur most of the times.
