### ISSUE TITLE
Introduce registrar communication language

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#640]
Might be `en|et` at the beginning, though should not be limited to.

I think it makes sense to introduce registrar communication language. I see at least 2 places where it could be used: invoice PDF and Directo export. Perhaps it also could be used as UI language.

**Comment by artur-beljajev** [comment]
@vohmar "registrar communication language" is also needed for #205

**Comment by vohmar** [comment]
default et, required on the registrar profile in admin

**Comment by artur-beljajev** [comment]
The system default is set to "en". You will need to manually edit "Default language" setting once released.

**Comment by vohmar** [comment]
langugage selection exists in admin registrar data edit view (/admin/registrars/50/edit)
* effective setting is missing from registrar info view (/admin/registrars/50)
* selected language setting does not affect language of the invoice - all invoices are still only in english in the UI and downloaded PDF
* adding credit fails with "Failed to create record" (/registrar/deposits/new)

**Comment by artur-beljajev** [comment]
№ 1: Good catch, added
№ 2: See #641

**Comment by artur-beljajev** [comment]
Includes #343, #407

**Comment by vohmar** [comment]
No1: ugly, but will pass
No2: understood
No3: still persists - no sensible error message in UI.  No reference to the error displaied in UI in the log ("Failed to create record"). time based search revealed this error "INV
OICE NUMBER LIMIT REACHED, COULD NOT GENERATE INVOICE" But according to admin UI invoice list (/admin/invoices) there is not invoices in the allowed range of invoice nor directo monthly numbers.

**Comment by vohmar** [comment]
no3 is now in separate ticket: https://github.com/internetee/registry/issues/654
