### ISSUE TITLE
REPP: bulk change - registrar transfer

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#660]
Case1: a registrar sells its domain portfolio to another registrar. 
Case2: new accredited registrar wants to take over their domains previously registered through another accredited registrar (sub-contracted)

* Query should be made using REPP API
* Query transfers given list of domains from any registrar to the one running the query
* As registrar transfer operation requires individual transfer codes for each transferred domain the input for the query must contain the list of domains and their associated transfer codes
* To improve user experience form for registrar bulk transfer should be added to registrars' portal with domain list upload option in the CSV format. CSV file downloaded from registrars' portal domain list must be accepted
* Need to add transfer code column to the domain list CSV download file format.
~~* Need to add domain list CSV download option to admin interface (identical to registras' portal) #500~~
*  `contacts.auth_info` does not get regenerated on domain transfer

**Comment by artur-beljajev** [comment]
№ 5: What is a transfer code? CSV = http://prntscr.com/i0l34x?

**Comment by artur-beljajev** [comment]
> Need to add domain list CSV download option to admin interface (identical to registras' portal)

#500

**Comment by artur-beljajev** [comment]
"Download as CSV"

**Comment by artur-beljajev** [comment]
domains.auth_info

**Comment by vohmar** [comment]
Decisions from 15.01 sprint planning:
* Query to transfer a domain must reach registry system using REPP API
* UI form for mass transfer is realised in registrars' portal using CSV import
  * CSV is expected with heading row, domain name in first and transfer code in second column, the rest is ignored
* domain list download functionality in the registrars' portal must produce the mass transfer compatible CSV file (domain name first and transfer code in second column - current CSV is missing transfer code)
* mass transfer is always and only initiated by the "new" registrar
* functionality regarding registrants' portal and admin interface is out of this tickets scope.

PS: error handling - REPP must return human processible error messages in case of incorrect input file and list of domains that failed the transfer request (ie domain name not found, incorrect transfer code, ...)

**Comment by artur-beljajev** [comment]
> Need to add domain list CSV download option to admin interface (identical to registras' portal) #500

@vohmar I see no problem implementing this as a part of this ticket. Do you?

**Comment by artur-beljajev** [comment]
Fix JS exception at /registrar/domains/transfer

**Comment by artur-beljajev** [comment]
REPP /domains?details=true auth_info!

**Comment by artur-beljajev** [comment]
Bug: `contacts.auth_info` does not get regenerated on copy (domain transfer)

**Comment by artur-beljajev** [comment]
":coffee", datepicker is not set in registrar area

**Comment by artur-beljajev** [comment]
utf-8 file upload

**Comment by artur-beljajev** [comment]
EPP domain:update updates transfer_code

**Comment by artur-beljajev** [comment]
transfer without validation

**Comment by artur-beljajev** [comment]
Test:
- Registrar, Registrant area for UI anomalies
- EPP transfer, update (transfer code)

**Comment by ratM1n** [comment]
database migration script ends with error : 
https://gist.github.com/ratM1n/3edcefdd36ee9b45d801e5cca4703da3
mentioned contacts table id 238265 is new, last existing is 238264

**Comment by vohmar** [comment]
mass transfer fails with certificate error:
SSL_connect returned=1 errno=0 state=error: certificate verify failed

**Comment by artur-beljajev** [comment]
If fails because `verify_mode = OpenSSL::SSL::VERIFY_PEER` is used by default, and it seems API host `repp_url` is not trusted.

@teadur @ratM1n Can you take a look?

P.S. When accessing API I use `cert_path` and `key_path` keys in `application.yml`.

**Comment by ratM1n** [comment]
@artur-beljajev cert_path and key_path are set because they are also used by epp and epp works from same portal.

i did check apache side SSLCACertificateFile and itsa same as for epp.

i made epp and repp requests with same certificates from my pc and all works. My hypotesis is that registrar portal side doesnt use proper certificate or doesnt use it in proper way.

only error i can see from apache repp log is (debug is on):
`[Fri Jan 26 20:21:11 2018] [info] SSL Library Error: 336151576 error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca`

**Comment by artur-beljajev** [comment]
REST API & EPP documentation updated

**Comment by vohmar** [comment]
* REPP log record returns internal error in admin (/admin/repp_logs/545)
* masstransfered domains return internal error in history view (/admin/domains/86936/domain_versions)

**Comment by artur-beljajev** [comment]
The latter is actually applies to every archive-related page.

**Comment by artur-beljajev** [comment]
#689

**Comment by vohmar** [comment]
Registrar - adding/removing nameserver and contact fields (buttons 'add another' and 'delete') do not work  - /registrar/domains/new and /registrar/domains/edit?domain_name=

**Comment by artur-beljajev** [comment]
"do not work" tells me nothing about a problem. Can you provide additional information?

**Comment by vohmar** [comment]
bulk transfer deployed to live
