### ISSUE TITLE
Registrant: domain list is missing domains associated with user through an organisation

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#663]
On login query is made to business registry to get back the list of business registry codes that the user is associated with. 

Unfortunately the domains that the user does not have direct relation with as registrant, admin nor tech contact are missing from the list even though correct list of business registry codes is returned and saved.

**Comment by artur-beljajev** [comment]
Add country code "+372" to mobile-id login form

**Comment by artur-beljajev** [comment]
http://prntscr.com/hz20j4

**Comment by artur-beljajev** [comment]
http://prntscr.com/hz2dn1

**Comment by vohmar** [comment]
it appears that any domain that is associated with the user only by registrant object is missing from the list - so not only the ones registered to businesses.

**Comment by vohmar** [comment]
@artur-beljajev please describe changes made in associated branches #664 and https://github.com/internetee/registry/tree/registrant-area-cleanup

**Comment by artur-beljajev** [comment]
See #667 before!

**Comment by vohmar** [comment]
deployed only this branch on staging env and the problem with pendingUpdated confirmation is exactly the same as described under PR #667

**Comment by artur-beljajev** [comment]
Please provide exact reproducing steps incl. initial data you used.

**Comment by artur-beljajev** [comment]
I still cannot reproduce the error you described. If it still persists, I need more info.

**Comment by vohmar** [comment]
This problem was actually about not showing any domains that the user was associated only as a registrant. So by fixing that problem fixed also the scenario where user was associated with a domain through a management board membership in a company registered as a registrant of a domain
