### ISSUE TITLE
Restore object validations on all EPP transform requests except transfer and delete

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#678]
Currently domain and associated objects (contacts, hosts, dnssec records, registrar/client) are not validated on renew and transfer transform requests. It is necessary to restore validations on renew requests so that renew is successful only when domain and all the sub/associated object are valid ie it would not be possible to renew domain if registrant contact is missing ident country code.

The only transform requests that must not fail because of invalid data is delete and transfer - loosing registrar has no motivation to correct data of objects it's going to loose.

**Comment by artur-beljajev** [comment]
The title says "on all EPP requests", however only "renew" is mentioned in the description.
Should I turn on the validation for the following commands?
- Domain create/update/renew
- Contact create/update

**Comment by vohmar** [comment]
* renew is specifically mentioned because this is the only operation that has currently validations disabled. But other operations should be verified as well. List of validated operatsions is correct. 
* requirements for validations focus on the resulting object and child object data (ie if contact or host is replaced there is no need to validate the removed object)
  * validated object and child object must meet the same requirements applied on create object
    * contact data - ident, ident_cc, ident_type filled with valid values; valid email and phone; name not null  etc
    * domain data - required contacts exist (at least one registrant, admin and tech contact), host count 0 or at least 2, host glue records have ip address defined, ipv4 and ipv6 addresses conform standards, DNSKEY parameters if exist meet the standard requirements (glags, algotirhm, pub keys)

**Comment by artur-beljajev** [comment]
What is the expected behaviour if domain validation on EPP domain:renew fails?

**Comment by vohmar** [comment]
does not work.
tested renewing domain with invalid tech contact (ident_cc missing) - renew was successful (@staging /admin/epp_logs/52076)
tested registering new domain with invalid admin and tech contacts (ident_cc missing) - create was successful (@staging /admin/epp_logs/52092)

expected result in both cases is failure with 2304 error message pointing out invaid contact(s)

**Comment by artur-beljajev** [comment]
Basically, it is not validation restoring, but rather introducing.
