### ISSUE TITLE
Admin: all email templates mangeable on settings>mail_templates

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#679]
/admin/mail_templates

all email templates for all the emails sent out from the registry system must be listed and editable here

**Comment by artur-beljajev** [comment]
It will be extremely hard to implement it for HTML

#201

**Comment by artur-beljajev** [comment]
#201

**Comment by artur-beljajev** [comment]
https://github.com/basecamp/trix

**Comment by artur-beljajev** [comment]
@vohmar There will be tremendous effort to make proper solution that will never pay off, since templates are changed too rarely.

`/rails/mailers/` will eventually have all emails in read-only mode.
