### ISSUE TITLE
EPP session handling fails

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#698]
After the last update we have a lot of session related issued in production

sessions getting mixed up - registrar gets authorization error for renew - in the logs we see that system thinks it's another registrar

we also see a lot of authorization errors with api-public marked as a user - registrar did not log out (info, poll and check queries)

**Comment by artur-beljajev** [comment]
#700 Includes a countermeasure

**Comment by vohmar** [comment]
#699 fixed the session mixup problem, also have not spotted mysterious loss of sessions any more - all api-public requests seem to be caused by unauthenticated users that have not logged in.
