### ISSUE TITLE
Improve EPP session management

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#700]
- Add database constraints
- Refactor EPPSession model, EPP::SessionsController, EppController
- Refactor database structure
- Add basic EPP login/logout tests

**Comment by teadur** [comment]
Please consider env['HTTP_COOKIE'] as session source if cookies doesnot give any extra value.

**Comment by artur-beljajev** [comment]
@vohmar @ratM1n Special attention to `db/migrate/20180207071528_extract_user_id_from_epp_sessions_data.rb`

**Comment by artur-beljajev** [comment]
Test:
- EPP login/logout
- EPP session limit

**Comment by vohmar** [comment]
* session limit does not work - successfully created 10 simultaneous sessions under a single registrar

* epp login/logout works
* epp logs in admin seem OK

**Comment by artur-beljajev** [comment]
How can I reproduce № 1?

**Comment by artur-beljajev** [comment]
As far as I remember, we decided to postpone this issue anyway.

**Comment by teadur** [comment]
So the #710 shouldnot be reviewed before #711 is finished ?

**Comment by artur-beljajev** [comment]
@teadur That's up to @vohmar to decide. By "Test EPP session limit" I meant that exactly the same behaviour as in master branch should remain in place. I only did some refactoring concerning that part.
