### ISSUE TITLE
EPP session timeout does not end sessions

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#711]
There are millions of sessions still up in registry db indicating that session timeout is not ending idle sessions.

Expected behavior is that all sessions that are idle/inactive are ended after predefined period of time and the session record is deleted from the sessions table.

**Comment by teadur** [comment]
#1017

**Comment by vohmar** [comment]
epp:clear_expired_sessions kills all sessions including the ones not yet expired

**Comment by artur-beljajev** [comment]
@ratM1n What is the value of `epp_session_timeout_seconds` setting?

**Comment by teadur** [comment]
@artur-beljajev i cannot find this setting anywhere, is it something new ? 
Should it be in application.yml or database ?

**Comment by teadur** [comment]
@artur-beljajev 
application.yml:epp_session_timeout_seconds: '300'
