### ISSUE TITLE
ForceDelete: option to disable auto-email

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#727]
Applying forcedelete currently send out automatic email about invalid data of the domain in comparison to business registry or in the event of deceased registrant.  An option to disable auto-email on ForceDelete application is necessary to make ForceDelete process available to other scenarios. 

add checkbox to admin domain edit set force delete view (/admin/domains/_some_id_/edit)

**Comment by artur-beljajev** [comment]
Do you mean some checkbox in domain "force delete" dialog? http://prntscr.com/ih4q2o
If so, what is the default behaviour (and therefore state of the checkbox)?

**Comment by vohmar** [comment]
yes something like that. Also updated the ticket description
