### ISSUE TITLE
Session limit does not apply porperly per registrar

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#729]
Current session limit control uses constant parameter in code and counts open sessions in a specific timeframe.

The session limit setting for allowed number of parallel open sessions per registrar must be configurable (global setting)
All open session must be taken into account to - depends on fix of https://github.com/internetee/registry/issues/711

**Comment by teadur** [comment]
#1017

**Comment by vohmar** [comment]
fixed by #1314
