### ISSUE TITLE
EPP: disable mod-epp epp request validation functionality

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#730]
mod-epp is Apache web server plugin with main goal to reply to epp requests with proper epp format responses instead of http.

Unfortunately mod-epp also validates some of the epp request by it self and replies without forwarding the request to the application ie unauthenticated poll requests.

Our goal is to handle all properly formatted epp requests in application for proper logging and better control. For this we need to either modify mod-epp, find alternative solution or develop our own. First choice is to modify mod-epp

Discovered in #697

**Comment by artur-beljajev** [comment]
https://tools.ietf.org/html/rfc5734

**Comment by vohmar** [comment]
solved in epp-proxy project: https://github.com/internetee/epp_proxy
