### ISSUE TITLE
REPP: bulk transfer - must retain the number of contacts 

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#746]
Bulk transfer currently reuses the contacts only in context of one domain that is transferred. But in case multiple domains had the same contact object associated, the reuse is not retained and new objects are created for all the transferred domains. That creates a problem for the further updates ie bulk change of tech contact.

The number of contact objects must not be bigger as a result of bulk transfer in comparison to the number of contact objects that were associated with transferred domains with previous registrar.

Bonus points for reducing the number of contact objects - force re-usage of contact objects with identical data (name, ident, ident_type, ident_cc, phone nr, email address, statuses).

**Comment by artur-beljajev** [comment]
> Bonus points for reducing the number of contact objects - force re-usage of contact objects with identical data (name, ident, ident_type, ident_cc, phone nr, email address, statuses).

I think it's worth creating a new ticket for this.
- Reuse is possible only within the same registrar only, right?
- How about postal address?
- We could enforce same reuse logic in EPP (contact:create, domain:create/update)

**Comment by vohmar** [comment]
* automatic reuse is allowed only within the same registrar
* only the contacts that have identical data sets are considered identical - if address processing is enabled then that also includes postal address
* Enforcing reuse on domain/contact create/update is not trivial - topic for separate ticket

**Comment by artur-beljajev** [comment]
Is it ok to include reuse in EPP domain:transfer?

**Comment by vohmar** [comment]
current ticket is about repp bulk transfer but basically yes it is OK to reuse existing contacts on epp transfer as well - but it must be validated first how much this will slow down the transfer process

**Comment by artur-beljajev** [comment]
> only the contacts that have identical data sets are considered identical - if address processing is enabled then that also includes postal address

Is there anything else besides what is mentioned above incl. address?

**Comment by artur-beljajev** [comment]
Timo:

> fax, org_name

**Comment by artur-beljajev** [comment]
> if one contact has fax value of "", and another of NULL, they will not be considered identical, and therefore will not be reused.
#754

**Comment by artur-beljajev** [comment]
Performance metrics of contact reuse query:

`EXPLAIN ANALYZE  SELECT "contacts".* FROM "contacts" WHERE "contacts"."name" = 'test' AND "contacts"."email" = 'test@test.com' AND "contacts"."phone" = '+123.456789' AND "contacts"."ident" = '37605030299' AND "contacts"."ident_type" = 'priv' AND "contacts"."ident_country_code" = 'EE' AND "contacts"."fax" IS NULL AND "contacts"."org_name" IS NULL AND (statuses = '{}'::character varying[]) AND "contacts"."registrar_id" = 1 AND ("contacts"."id" != 111);`
