### ISSUE TITLE
Remove unused database tables

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#756]
- people 
- domain_statuses, log_domain_statuses
- countries, log_countries
- data_migrations 
- cached_nameservers 
- contact_statuses, log_contact_statuses

They are all empty on prod. "testreg" env has some remnants in some tables.

---
Test:
- EPP Domain/contact status update (if such feature exists)

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/blob/7c80577ef51ff18a22afa8bbda38008156b99280/db/migrate/20150105134026_drop_cached_nameservers.rb

**Comment by vohmar** [comment]
no anomalies spotted. Unable to test setting client side statuses - 

```
    <result code="2306">
      <msg lang="en">Parameter value policy error. Client-side object status management not supported: status [status]</msg>
```

client side status editing was set to enabled in admin . reated separate ticket for this (https://github.com/internetee/registry/issues/762)
