### ISSUE TITLE
Remove `invoices.invoice_type`

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#772]
Before it has been always hardcoded to "DEB".

**Comment by vohmar** [comment]
The branch has the same problem as described in ticket #774 and #642 

blocked by #774

**Comment by vohmar** [comment]
blocker resolved

**Comment by vohmar** [comment]
has merge conflicts with master
https://github.com/internetee/registry/pull/773

**Comment by artur-beljajev** [comment]
See PR

**Comment by vohmar** [comment]
it appears that not all commits of this branch are available on master. moving it back to testing (3 commits are missing from master)

**Comment by artur-beljajev** [comment]
Those are merge commits. This ticket can be closed along with its PR with no action.
