### ISSUE TITLE
Consider renaming "deleteCandidate" status of a domain

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#784]
@vohmar  Is there any reason why "candidate" word is used in `deleteCandidate` status? I didn't notice any circumstances under which a domain with that status does not get permanently deleted, so why to call it a candidate?

**Comment by vohmar** [comment]
deleteCandidate status is removable in admin
deleteCandidate means that the domain object in waiting to be deleted/archived/released thus it is candidate (it is not deleted yet)

no renaming necessary - consider unifying the term in code as well (using deleteCandidate universally)

**Comment by artur-beljajev** [comment]
"not yet deleted" has nothing in common with the word "candidate". I think "discard" is more suitable work to model this business logic. Currently this status is set by a CRON job (https://github.com/internetee/registry/blob/c1cb598da1fff8722d307c558abb9e2ec2f4a932/app/models/domain_cron.rb#L112) and I cannot find how to remove this status from admin area.

**Comment by vohmar** [comment]
we have decided no to proceed with renaming any statuses nor changing processes at the moment.
