### ISSUE TITLE
Remove unused `domains.valid_from`

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#787]
@vohmar I don't see that it is used, can you clarify the intention of it?

Additional info: https://github.com/internetee/registry/issues/235#issuecomment-259039980

**Comment by artur-beljajev** [comment]
Check live, can be removed if no big differences.

**Comment by artur-beljajev** [comment]
Test domain creation

**Comment by artur-beljajev** [comment]
I skipped introducing `domains_v2` API, and just added `valid_from` to return value from `registered_at` explicitly.

**Comment by vohmar** [comment]
Branch merge conflicts with master
https://github.com/internetee/registry/pull/793

**Comment by artur-beljajev** [comment]
Fixed
