### ISSUE TITLE
WHOIS: remove registration data from domains with deleteCandidate status

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#789]
deleteCandidate status means that domain is set to be deleted and is waiting for the proper moment. Policy wise the domain name does not belong to the previous registrant and no changes can be done to the registration while the status is set.

Currently domains with deleteCandidate status still display all the information in whois that was associated to it before raising confusion that registration still belongs to previous owner and it is possible to change the data if necessary.

To remove the confusion the whois output for domains with deleteCandidate status should be with all associated data removed and similarly to blocked and reserved domains display only the status of delete candidate

**Comment by artur-beljajev** [comment]
Makes no sense to covert with tests until #375 is done.

**Comment by vohmar** [comment]
Introducing new terms in code ie discarded that are not used anywhere in business processes in stead of the ones that are is far from ideal solution. Will probably need to refactor it in the future.
