### ISSUE TITLE
Admin: cancel force delete should not remove deleteCandidate status

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#791]
/admin/domains/_id_/edit

cancel force delete function should remove only the statuses that were set on schedule force delete. So deleteCandidate status should not be removed when force delete is canceled even if the status was set due to forceDelete process running to an end. Removing deleteCandidate status must be conscious decision as this is exceptional action.

Furthermore as deleteCandidate status represents domain waiting to be released and not being owned any more by previous registrant cancelling (nor setting for that matter) forceDelete should not be possible until deleteCandidate status is set.

**Comment by artur-beljajev** [comment]
> cancel force delete function should remove only the statuses that were set on schedule force delete
How can I set those statuses on force deletion? There is only one drop-down with template selection.

**Comment by vohmar** [comment]
Force delete it self is label/name for a procedure. It is set of statuses. By applying force delete one actually adds these statuses to a domain: serverRenewProhibited, serverTransferProhibited, serverUpdateProhibited, pendingDelete, serverManualInzone + serverForceDelete. So by canceling force delete procedure no other statuses should be automatically removed.

**Comment by artur-beljajev** [comment]
1. Why these statuses are removed on "force delete" action?
```
    statuses.delete(DomainStatus::CLIENT_DELETE_PROHIBITED)
    statuses.delete(DomainStatus::SERVER_DELETE_PROHIBITED)
    statuses.delete(DomainStatus::PENDING_UPDATE)
    statuses.delete(DomainStatus::PENDING_TRANSFER)
    statuses.delete(DomainStatus::PENDING_RENEW)
    statuses.delete(DomainStatus::PENDING_CREATE)

    statuses.delete(DomainStatus::FORCE_DELETE)
    statuses.delete(DomainStatus::SERVER_RENEW_PROHIBITED)
    statuses.delete(DomainStatus::SERVER_TRANSFER_PROHIBITED)
    statuses.delete(DomainStatus::SERVER_UPDATE_PROHIBITED)
    statuses.delete(DomainStatus::SERVER_MANUAL_INZONE)
    statuses.delete(DomainStatus::PENDING_DELETE)
```

**Comment by vohmar** [comment]
1. starting force delete procedure means there is something wrong with current data associated to the domain registration. Therefore we freeze the current set of data and stop any pending processes. As it is administrative delete procedure we also remove deleteProhibited statuses. The lower set is a bit trickier - as these are the statuses applied by forceDelete I would imagine that duplicate statuses are removed first to make the application process simpler. Not completely sure here.

2. yes the domain is kept in zone only if it was not already removed from zone at the time forceDelete was applied. This is expected behavior and you are correct this should have been mentioned above as well. 

3. validation is off because we do not want the ability to apply or remove the status dependent on the quality of data of the domain. Similarly to regular epp domain/contact delete request.

4. The domain might have had number of statuses set before forceDelete was applied - a lot of these statuses are removed on forceDelete application. We want to restore the previous domain state when we stop forceDelete process. So there should be a step on cancel force delete step that restores these statuses from the statuses_backup.

5. like with most of period calculations we have we do not take the running day when domain was registered, or in this case forceDelete was applied into account and start counting from the first full day hence +1. Why utc is specifically forced in this situation is I would guess developers decisions - all the dates should be stored in db similarly using the same tz in our case that is UTC.

**Comment by artur-beljajev** [comment]
> we do not want the ability to apply or remove the status dependent on the quality of data of the domain.
Not sure I understand this part

**Comment by artur-beljajev** [comment]
I think it makes sense to rename `statuses_backup` to something more meaningful, say to `statuses_before_force_delete`

**Comment by vohmar** [comment]
not sure about the necessity of returning backed up statuses with repp api. may be removed.

**Comment by artur-beljajev** [comment]
Can I solve https://github.com/internetee/registry/issues/812 along with this ticket?

**Comment by artur-beljajev** [comment]
How can I complete this ticket, which says 

> cancel force delete should not remove deleteCandidate status

if #812 says that 

> Force Deleted domains do not get deleteCandidate status 
?

**Comment by vohmar** [comment]
* deleteCandidate status should always be set by the same cron- i do not see the reason to have separate process to set deleteCandidate for regular expiration, domain:delete requests and force delete procedures. The cron task is supposed to set the status by looking at both delete_at and force_delete_at dates on basis which ever comes first.

**Comment by artur-beljajev** [comment]
1.  
Why
> stop any pending processes
=    
```
statuses.delete(DomainStatus::CLIENT_DELETE_PROHIBITED)
statuses.delete(DomainStatus::SERVER_DELETE_PROHIBITED)
```

what is pending if any of those statuses is set?
5. What is the expected value of `domains.force_delete_at` column after "force delete" operation? I guess 00:00 of the next day by local time (=Estonian in our case)?

If so, currently is it implemented incorrectly, since it is set to 03:00 (as of today; 00:00 by UTC = in the DB)

```
irb(main):010:0> d.force_delete_at = (Time.zone.now + (Setting.redemption_grace_period.days + 1.day)).utc.beginning_of_day
=> 2018-05-21 00:00:00 UTC
irb(main):011:0> d.save(validate: false)
irb(main):012:0> d.reload
irb(main):013:0> d.force_delete_at
=> Mon, 21 May 2018 03:00:00 EEST +03:00
irb(main):014:0> d.force_delete_at_before_type_cast
=> "2018-05-21 00:00:00"
```

**Comment by artur-beljajev** [comment]
> not sure about the necessity of returning backed up statuses with repp api. may be removed.

This requires new API version. Though, I am not sure if there is anyone who actually relies on this. Perhaps we can follow pragmatic approach and to just change it?

**Comment by artur-beljajev** [comment]
I see some restrictions connected to `forceDelete` status in EPP. Could you explain that part in detail?

https://github.com/internetee/registry/blob/96e2136c38f4501725a05f1ffe43018c67d6e184/app/models/domain.rb#L134

**Comment by artur-beljajev** [comment]
Can `domains.statuses` column be changed after "force delete" is initialised?

**Comment by artur-beljajev** [comment]
Can `domains.statuses` column change after "force delete" is initialised?

**Comment by vohmar** [comment]
1. *_delete_prohibited statuses have to be removed because force delete is administrative delete procedure. The domain has to be deleted if the process is not canceled in 30 days.
2.  force_delete_at value is calculated by adding length of redemption grace period and 1 day at time 00:00 (ie it is now 24.04.2018 10:14 - force_delete_at would be 24.05.2018 00:00 (+31days)) . The same way as delete_at value is calculated on domain.delete epp request.
3. REPP API is used by registrars - but in this case i believe we can make an exception and not add new API version
4. I am not sure I can understand the code correctly here
5. Yes admin can change list of statuses applied with force_delete - ie take the domain outzone or remove some prohibited statuses to allow registrant to correct invalid data. But these changes are usually directly connected to fixing the reason force delete process was applied. On canceling the process I cannot see the reason for merging any statuses. Remove all the statuses, restore statuses from backup and optionally recalculate outzone and delete dates and set statuses accordingly

**Comment by artur-beljajev** [comment]
> I am not sure I can understand the code correctly here
It effectively prohibits any manipulation with a domain if it has "force delete" operation scheduled. 
Extracted to #870

**Comment by vohmar** [comment]
ForceDelete by itself should not prohibit anything - there are *prohibited statuse for that.

**Comment by vohmar** [comment]
* Still possible to cancel force delete while deleteCandidate status is set
* Canceling forcedelete also removed deleteCandidate status from the domain

test process:
1. find a domain with deletecandidate status set and remove that status
2. apply force delete process to that domain
3. run DomainCron.destroy_delete_candidates to reset deletecandidate status
4. cancel forcedelete process - force delete canceled, deletecandidate removed

expected result:
* not possible to cancel force delete while deletecandidate status is set
* to cancel force delete, admin should first remove deletecandidate status and only then is able to cancel the force delete process

**Comment by artur-beljajev** [comment]
First you asked for:

> cancelling forceDelete should not be possible until deleteCandidate status is set.

I have implemented it and the following tests pass:
https://github.com/internetee/registry/blob/c2d5b7c7040b1ab6c7eafb1bef107fb5807508bb/test/models/domain/force_delete_test.rb#L76
https://github.com/internetee/registry/blob/c2d5b7c7040b1ab6c7eafb1bef107fb5807508bb/test/models/domain/force_delete_test.rb#L85

So now it's not possible to cancel "force delete" operation unless a domain has `DELETE_CANDIDATE` status, so If a domain _has_ `DELETE_CANDIDATE`, it _can_ be cancelled.

now you ask for the opposite:

> not possible to cancel force delete while deletecandidate status is set

**Comment by vohmar** [comment]
* deletecandidate basically prohibits any further change to the domain except deletion
* to make any change including stopping forceDelete procedure one must first remove deletecandidate status

**Comment by vohmar** [comment]
test results:
* was still able to add and remove forcedelete or any other status for that matter even though deleteCandidate status was set

**Comment by artur-beljajev** [comment]
Now you cannot cancel "force delete" procedure if a domain has `deleteCandidate` status.

**Comment by vohmar** [comment]
can still add force delete while domain has deletecandidate status set.  adding forcedelete to delete candidate, then removing delete candidate status to cancel forcedelete results with domain with reapplied deletecandidate status but no que job. Setting delete candidate status is a separate process so it should not be applied by anything else like canceling force delete process for example. (this would not be a problem if changing statuses by admin or registrar was disabled while deletecandidate status is applied.

**Comment by artur-beljajev** [comment]
Now you cannot schedule "force delete" procedure if a domain has `deleteCandidate` status.

Same check during cancellation is removed as being useless (if you cannot start the process, you obviously cannot end it).

**Comment by artur-beljajev** [comment]
Please retest.
