### ISSUE TITLE
Admin: present deleteCandidate status in red

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#792]
/admin/domains/_id_

Display deleteCandidate status in different color ie in red in admin (and other web interfaces if possible (registrar, registrant)) to stress this status being present and make it easily noticable

**Comment by artur-beljajev** [comment]
Perhaps you would also like to have some flag in domain list? Say, like this: http://prntscr.com/izk1fj

**Comment by artur-beljajev** [comment]
#784

**Comment by vohmar** [comment]
There is no need for separation on general domain list. Label idea got postive feedback - the goal is to make it easily noticable that the domain admin is working with is already waiting for deletion.

**Comment by artur-beljajev** [comment]
Perhaps you would also like to be able to "keep" it once a domain has been discarded (has `deleteCandidate` status)?

Say some link saying "This domain has been discarded and awaits deletion. Keep it" (where the latter is a link).

**Comment by vohmar** [comment]
we have status based processes - we set and remove statuses. No need to duplicate it by extra links . Furthermore we do not discard domains.

**Comment by artur-beljajev** [comment]
Well, from OOP point of view this approach is wrong.

**Comment by vohmar** [comment]
in production
