### ISSUE TITLE
WHOIS: GDRP disclaimer for whois responses

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#795]
Necessary to add Disclaimer to the beginning of whois query response informing user of limitations on the whois data use (example from .se: https://who.is/whois/internet.se)

As whois db is read only and replicated from registry db the source should be kept in registry db - 
* add table to registry db
* modify the postgresql db replication task for whois db
* drop text version of whois data (generation and replication) - dependent on https://github.com/internetee/whois/issues/25
* regenerate whois db

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, a couple questions:

- Should the disclaimer be present only in UNIX/text based whois or both UNIX and JSON?
- Can you update the following text with all the required legalese applicable to Estonia? I'm not very good with that, and it probably needs some reference to [PDP act](https://www.riigiteataja.ee/en/eli/512112013011/consolide):

```
Estonia .ee Top Level Domain WHOIS server
The information obtained through searches, or otherwise, is protected
by international conventions, including European Union regulations.
Any use of this material to target advertising or
similar activities is forbidden and will be prosecuted.
If any of the information below is transferred to a third
party, it must be done in its entirety. 
```

**Comment by vohmar** [comment]
* disclaimer should be in both unix and rest whois output
* current version of text:

> The information obtained through .ee WHOIS is subject to database protection according to the Estonian Copyright Act and international conventions. All rights are reserved to Estonian Internet Foundation. Search results may not be used for commercial, advertising, recompilation, repackaging, redistribution, reuse, obscuring or other similar activities. Downloading of information about domain names for the creation of your own database is not permitted. If any of the information from .ee WHOIS is transferred to a third party, it must be done in its entirety. This server must not be used as a backend for a search engine. Read more about the Rules of .ee WHOIS service here.

**Comment by maciej-szlosarczyk** [comment]
The disclaimer is added, but there's a slight problem with REST whois, at least locally. The disclaimer misaligns the whole text in HTML response. I can fix it in scope of https://github.com/internetee/rest-whois/issues/37

<img width="639" alt="screen shot 2018-04-30 at 09 59 16" src="https://user-images.githubusercontent.com/2331765/39417501-4802dd58-4c5d-11e8-8cea-9c0449f5018a.png">
