### ISSUE TITLE
Admin: domain_versions search returns internal error

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#830]
After the last live on 23rd of April the search in domain history view in admin (/admin/domain_versions) returns internal error to user with any  value in name, registrar name and action search values. 

Registrant search returns the same error unless the exact match is found including any wildcard search (ie string%).

Result per page work fine

The issue in reproducible also on staging and registrar test env with the latest master branch.

**Comment by virtualfeline** [comment]
Result per page does NOT work fine for any value over 117.

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, would it be possible to see the actual error message from either live or stage? I am unable to reproduce the issue locally. The usual suspect is an N+1 query, as it happens to be there:

```
app_1  |   CACHE (0.0ms)  SELECT  "registrars".* FROM "registrars" WHERE "registrars"."id" = $1 LIMIT 1  [["id", 1]]
app_1  |   CACHE (0.0ms)  SELECT  "contacts".* FROM "contacts" WHERE "contacts"."id" = $1 LIMIT 1  [["id", 1]]
```

**Comment by maciej-szlosarczyk** [comment]
The issue stems from the lack of handling of removed columns in the versions history. Since we can solve this issue both ways, a question to @vohmar:

When comparing versions (not only of domains, but anything) should we display all the columns that were there in the past or only those that are in the schema now? 
A concrete example is in `domains.valid_from` field, as Artur pointed out. Should we display history for `valid_from` up until the point of it being removed from schema or should we not display it at all?

**Comment by artur-beljajev** [comment]
I don't see any point displaying `valid_from` (more on this https://github.com/internetee/registry/issues/235#issuecomment-259039980)

**Comment by artur-beljajev** [comment]
Though I think it is really rare case, so out of `valid_from` context @maciej-szlosarczyk's question remains.

**Comment by vohmar** [comment]
Lets go with second option of checking current schema and not displaying anything that is missing from it.

**Comment by vohmar** [comment]
tested on staging
* name search - if search value has a match error 500 is returned
* registrant search - id search value has a match error 500 is returned
* action = destory results with error 500

error in log:
`Apr 25 15:22:41 staging ADMIN[21083]: [st-adm.infra] [9e0c0a4a-27fa-4ebf-b6be-2e35207a9637] [192.168.2.45] #012ActionView::Template::Error (unknown attribute 'valid_from' for Domain.):#012    55:         %tbody#012    56:           - @versions.each do |version|#012    57:             - if version#012    58:               - domain = Domain.new(version.object.to_h)#012    59:               - attach_existing_fields(version, domain)#012    60: #012    61:               %tr#012  app/views/admin/domain_versions/archive.haml:58:in block in _app_views_admin_domain_versions_archive_haml__1904814651035120074_41297320'#012  app/views/admin/domain_versions/archive.haml:56:in_app_views_admin_domain_versions_archive_haml__1904814651035120074_41297320'#012  app/controllers/admin/domain_versions_controller.rb:47:in `index'`

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, I made a mistake and solved the reverse bug. Please check, it should be better now.
