### ISSUE TITLE
Directo: invoices are not sent to directo

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#844]
There are currently 8 paied and waiting to be sent to Directo in production, but for some unknown reason it is not happening.

The directo XMLs are unfortunetely not logged (https://github.com/internetee/registry/issues/344) and there are no errors in any other logs.

We see 8 invoices in db with sent to directo parameter false. Running the cron job returns 8 of 8 invoices sent but in reality nothing gets to directo and all the invoices are still marked as not sent.

**Comment by maciej-szlosarczyk** [comment]
https://github.com/internetee/registry/pull/848 Does not fix the issue, but logs both Request and response we get from Directo. It should allow us to debug the actual issue.

**Comment by vohmar** [comment]
unfortunately we are still unable to figure out what is the issue. In test the invoice it self reaches Directo but the invoice content is missing.

To get a better idea what is going on we need
* XML sent to Direocto and the reply to it - there is a table called directos for this kind of data
* it would be also helpful if there was a debug option with the cron script Directo.send_receipts to force it to log everything that is going on for situations like this.

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, if you used the latest master, then since #848 is merged, all of that information should be in the logs, prefixed with `[Directo]`, both the XML request and the response Directo gives, including the HTTP code. I just added it. I'd need to see the logs to have an idea what is happening.

Before we'd add storing that info into database, I'd need to spend some time refactoring the cron jobs for sending invoices, as in it's current for it's unmaintainable and untested.

**Comment by vohmar** [comment]
Apparently the invoices got stuck in Directo queue for some reason. Directo cleared the queue, we tried to resend everything and it seem the invoices are stuck again for some reason. They still have not sent me schema files although Artur should have these from the time he added send vatcode functionality. Currently trying to work out the problem with Directo.

**Comment by vohmar** [comment]
here is the log from test env - the result of this was invoice in directo without records (body missing):

```
May 15 14:17:40 test-reg ADMIN[17004]: [DIRECTO] Will try to send 1 invoices
May 15 14:17:41 test-reg ADMIN[17004]: [Directo] XML request: <?xml version="1.0" encoding="UTF-8"?><invoices>  <invoice
 SalesAgent="JAANA" Number="3008355" InvoiceDate="2018-05-15T13:45:44" PaymentTerm="R" Currency="EUR" CustomerCode="EIS"
 TotalVAT="0.00">    <line ProductID="ETTEM06" Quantity="1" UnitPriceWoVAT="24.00" VATCode="EU87654321" ProductName="Ord
er nr. 3008355"/>  </invoice></invoices>
May 15 14:17:41 test-reg ADMIN[17004]: [Directo] Directo responded with code: 200, body:
```

**Comment by vohmar** [comment]
it apperas that what we handled as vat registry code is actually Directos internal vat rate code. There are currently these values in Directo

MOSS Läti   21%    kood 21
20% Eestis  20%    kood 10
EU käive      0%      kood 4
Teenuse eksport  0% kood 6

So we should replace vatcode value with one of these

* Latvian registrar with no vat registry code gets value 21
* All Estonian registrars get value 20
* EU registrs that have vat registry code get value 4
* Registrars outside of EU get value 6

**Comment by artur-beljajev** [comment]
How can we distinguish, say, Latvian registrar? Currently we only have contact address, as far as I remember. Good that the country part is required.

**Comment by vohmar** [comment]
Use the mandatory address country to determine the tax residency. So any registrar with address country set to Latvia and no VAT number set get VAT code 21 for invoice data for sending to Directo.

**Comment by artur-beljajev** [comment]
How often those values get changed?

**Comment by vohmar** [comment]
rarely, usually only once on the first entry.

**Comment by vohmar** [comment]
most of our registrars are Estonian, so if default value is necessary then that would be 10

**Comment by teadur** [comment]
Where is this directo internal vat rate code stored in our system ?

**Comment by artur-beljajev** [comment]
This ticket removes `VATCode`, `TotalVAT` as a quick fix. #880 is for long-term solution.

**Comment by vohmar** [comment]
in production
