### ISSUE TITLE
WHOIS in Registrant Portal should use REST API instead of accessing DB directly

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#852]
- [x] Replace WHOIS controller link to a link to Internet.EE website, where you can get the information about any domain.
- [x] When https://github.com/internetee/rest-whois/issues/64 is complete, replace the link created above with a link to search.
- [ ] Remove WHOIS controller from registrant or replace it with relying on API that fetches data from REST WHOIS and serves it to a registrant.

**Comment by vohmar** [comment]
in production
