### ISSUE TITLE
Admin: removing certificate should revoke it first

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#887]
/admin/api_users/_userid_/certificates/_certid_

Removing unrevoked certificate prevents reusing same certificate signing request as there is effective certificate for that csr already in system.  Deleting unrevoked certificate should first revoke the cert and only then delete it.

**Comment by maciej-szlosarczyk** [comment]
We have missing tests around certificates, part of this fix would be to also introduce a testing suite for certificates controller (and model, of course).

**Comment by vohmar** [comment]
removing PKI certs works fine. But removing EPP certs returns now error:

`Using configuration from /home/registry/registry/shared/config/openssl.cnf#012ERROR:name does not match /C=EE/ST=Harjumaa/O=EIS/OU=staging reg2/CN=reg2-martin/emailAddress=...`

PKI and EPP certs have different CAs

**Comment by maciej-szlosarczyk** [comment]
@vohmar, please try again, @ratM1n and @teadur suggested a fix that might just work.
