### ISSUE TITLE
Destory orphans cron task does not archive unlinked contacts

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#956]
Business requirement: all contacts that have not been linked to any domain for more than 6 months must be archived (removed from the list of active contact objects)

There is contact status linked that means that contact is associated with at least one domain. Linked status is assigned when contact is associated with a domain and the status is removed once the last domain association is removed.

For this purpose there is a cron job: Contact.destroy_orphans that should look for contacts with no relations to any registered domain name then determine the period contact has been unlinked and if that period is 6 months or more that contact object should be removed from contacts table (will remain in log_contacts table)

**Comment by artur-beljajev** [comment]
> removed from the list of active contact objects
= from `contacts` database table?

**Comment by artur-beljajev** [comment]
Can we avoid using `linked` status at all?

**Comment by artur-beljajev** [comment]
New rake task `contacts:clear_orphaned`

**Comment by artur-beljajev** [comment]
@vohmar 

Why 

https://github.com/internetee/registry/blob/a97728c0f39fa50ff1c1d8dc4caf202ad5be718d/config/schedule.rb#L20

**Comment by vohmar** [comment]
There is no particular reason for running the archive task only once in 6 months. It can be run once a day.

**Comment by artur-beljajev** [comment]
OK, I will change it then.

**Comment by vohmar** [comment]
the contac:archive rake task has suboptimal output - it logs object id's that is not helpful for audits and debugging. The task should record contact objects' code that are archived.

also it looks like the objects that have never been associated with any domains as registrant, admin nor tech contact are not being archived

**Comment by artur-beljajev** [comment]
> the contac:archive rake task has suboptimal output - it logs object id's that is not helpful for audits and debugging. The task should record contact objects' code that are archived.

I don't find it sub-optimal. ID is returned for consistency with other tasks. Why you cannot use ID? More importantly, how often you will be using this value? It should be extremely rare.

> also it looks like the objects that have never been associated with any domains as registrant, admin nor tech contact are not being archived
How you tested this?

**Comment by vohmar** [comment]
* contact objects that have never been associated with any domains are archived immediately. Orphaned contacts can be archived only after they have been unlinked for 6 months according to current policy - that means if contact has never been associated with any domains contact create date must be the basis to calculate the orphaned period length
* Please add contact ID to the contacts:archive rake task output
* according to current timing the contacts:archive task after the initial archivation takes about 3 to 4 minutes to run each time (there are 11k contact objects in staging) - trying to speed things up might be necessary here, but we can try it out on live setup before.

**Comment by artur-beljajev** [comment]
1.
2. Done.
3. Implementation changed.

**Comment by vohmar** [comment]
run it on staging for 1,5 days (about 160k contact objects) and it did not finish in that time. Also the active contact count did not go down. A technical issue is described in the PR (https://github.com/internetee/registry/pull/1146)
