### ISSUE TITLE
Establish default money format

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#972]
Currently it is diverse in some places.
http://prntscr.com/kshpgs

I would stick to `money` gem format:

```
irb(main):001:0> Money.from_amount(25500.25).format
=> "€25 500,25"

```

Some articles:
http://publications.europa.eu/code/en/en-370303.htm#position
https://ux.stackexchange.com/questions/9105/international-currency-formatting-guidelines-currency-codes

**Comment by vohmar** [comment]
In UI please use format  X XXX,XX € ie 1 234,56 €

http://publications.europa.eu/code/en/en-370303.htm

**Comment by artur-beljajev** [comment]
OK, same format is set in I18n:

https://github.com/internetee/registry/blob/37db2cca90e900ac80906e71a52b7354588f605d/config/locales/en.yml#L737

`Money` class format remains the same, since it is not clear whether we need it at all.

P.S. This ticket is to leave a trail of money format. No code has been changed.
