### ISSUE TITLE
Registrar: mID auth fails with IE

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#982]
In IE11 when user chooses to auth with mobile-ID instead of polling the server for authentication borowser tries to download a json file.

![image](https://user-images.githubusercontent.com/7734747/45673543-9b6ae400-bb33-11e8-87a0-9000baefd30b.png)

log:
[18/Sep/2018:10:50:11 +0300] "POST /registrant/mid HTTP/1.1" 200 1540 "https://registrant.internet.ee/registrant/login/mid" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/wiki/Browser-Support does not list IE as a supported browser.

Is that list outdated or it's just needed to fix Mobile ID auth? (only).

**Comment by vohmar** [comment]
@artur-beljajev yes we will only focus on getting the Mobile ID auth working if it is possible with reasonable effort. 

PS: IE11 is still most used MS browser out there

**Comment by artur-beljajev** [comment]
@vohmar #429 might help us discovering such errors faster (possibly before users notify us).
