### ISSUE TITLE
Registrant API: nameserver and registrar info is missing

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#991]
domain info query returns only registrar id and does not return nameserver info. There is no other option to query this info so domain details' query should return this info with other domain details. Registrar object id is not needed in the details in this case as there is no way to use it.

https://github.com/internetee/registry/blob/registry-849/doc/registrant-api/v1/domain.md

**Comment by vohmar** [comment]
please add ip addresses of nameservers as well

**Comment by vohmar** [comment]
and registrar url

**Comment by maciej-szlosarczyk** [comment]
@vohmar Please try again with #997

Nameservers should be returned as an array:

```json
// ...
  "nameservers": [
    {
      "hostname": "ns1.bestnames.test",
      "ipv4": ["173.245.58.41"],
      "ipv6": ["2400:cb00:2049:1::adf5:3a33"]
    },
    {
      "hostname": "ns1.bestnames.test",
      "ipv4": ["173.245.58.51"],
      "ipv6": ["2400:cb00:2049:1::adf5:3b29"]
    },
  ],
// ...
```

Registrar now is an Object, not a String:

```json
  "registrar": {
     "name": "Best Names",
     "website": "example.com"
  },
```

I also removed an abandoned database column, `domains.status`. It is empty in production database and never referenced in code either. Given that it was created in June 2014, I assume that's quite some legacy.
