### ISSUE TITLE
Registrant API: enable disclosing private user's name and email address

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#992]
Option for private user to disclose their name and/or email address in EIS's web whois just like before GDPR.

If a person decides to disclose their private data the output for general public whois queries should be similar to business contact data

Name - disclosed publicly ie also seen on public whois queries
Email - Not Disclosed - Visit www.internet.ee for webbased WHOIS

Disclosing query must also enable undisclosing already user disclosed data - not possible to undisclose data available by default (ie business contacts' name and email)

Current sketch of registrant portal on how this functionality will be used by domain contacts:
https://projects.invisionapp.com/share/N4K6NII3JYG#/screens/285863083_Kontakti_Muutmine

**Comment by artur-beljajev** [comment]
So only API and no UI? (which is being implement by a third-party, I guess?)

**Comment by vohmar** [comment]
The Ui functionality will be included in the new portal all ready in development - no reason to spend time on current one. So yer the functionality in regard of this ticket here is only focusing on Registrant Rest-API.

**Comment by vohmar** [comment]
yes, only Registrant Rest-API development in this ticket.

**Comment by teadur** [comment]
Are we going to do #325  at the same time ?

**Comment by artur-beljajev** [comment]
I guess it also involves changes in `whois` and `rest-whois` projects?

**Comment by artur-beljajev** [comment]
@vohmar What should be returned in `email` field of registrant, tech/admin contacts in JSON version (http://rest-whois.test/v1/shop.test.json)?

**Comment by artur-beljajev** [comment]
@vohmar https://github.com/internetee/rest-whois/pull/129#issuecomment-435413895

**Comment by artur-beljajev** [comment]
> Disclosing query must also enable undisclosing already user disclosed data

Before I was sure we don't have such feature, but it seems we do https://github.com/internetee/registry/pull/1038 (needs confirmation).

**Comment by vohmar** [comment]
run into an issue on staging with one of the contact objects. Getting noMethodError ehen I try to open the details of the object in admin 

https://st-adm.infra.tld.ee/admin/contacts/238421

```
NoMethodError in Admin::Contacts#show
Showing /home/registry/registry/releases/678/app/views/admin/contacts/partials/_general.haml where line #41 raised:

undefined method `admin_registrant_user_path' for #<#<Class:0x00007fc80050bcf0>:0x00007fc7e99216f8>
```

Extracted source (around line #51):
```
    # can be api user or some other user
    link_to(model.updator, ['admin', model.updator])
  end

  def currency(amount)
```

might be related to updating data using registrant api

**Comment by vohmar** [comment]
user is able to change disclose parameters of other person's contacts - user should be able to change only the contacts that belong directly to them  (personal identity code of logged in user and object matches). When querying contact data user is allowed to see details of all contacts associated with the domain objects associated with themselves, but the ability to change and disclose contact data should be available only for their own contact objects.

**Comment by artur-beljajev** [comment]
> user is able

How exactly?

**Comment by vohmar** [comment]
test are done by directly querying API (curl requests)
session is created with correctly filled ident, first and last name parameters.
also the contacts that were edited and now produce the NoMethodError have valid ident data

example contacts:
* https://st-adm.infra.tld.ee/admin/contacts/238421 (ident code matches the code used for auth)
* https://st-adm.infra.tld.ee/admin/registrants/238420 (ident code does not match the code used for auth)

example domain: https://st-adm.infra.tld.ee/admin/domains/86932

**Comment by artur-beljajev** [comment]
I need the complete bug report for this https://github.com/internetee/registry/issues/992#issuecomment-447800708.

**Comment by vohmar** [comment]
* getting Net::ReadTimeout in Registrant::ContactsController#update error in registrant on contact data update in registrant portal (https://github.com/internetee/registry/pull/1058 deployed on staging)
* also still able to update contacts and disclose atributes of contacts not belongig to me

**Comment by vohmar** [comment]
after separating registnrant portal and registrant api to separate instances new error is raised on contact data update: JSON::ParserError in Registrant::ContactsController#update

**Comment by artur-beljajev** [comment]
This has been fixed few days ago.

**Comment by vohmar** [comment]
done
